grain-lang/grain

src/lexer.mll, src/parser.mly, test/input/conditionals.gr
I'd add a test, but I figure we should probably clean up our tests.
=> First pass at else if

.gitignore, runtime/src/core/grain-module.js, runtime/src/index.js, runtime/src/runtime.js, runtime/src/utils/locators.js
I also cleaned up the code a little.
=> Fix browser runtime

LICENSE
=> Add LGPL license.

grainc/grainc.ml, src/grain_stdlib.ml, src/grain_stdlib.mli, src/typed/env.ml, src/utils/config.ml, src/utils/config.mli, src/wasm_runner.ml
=> Fix reading of GRAIN_ROOT

cli/bin/compile.js, cli/bin/run.js, grainc/grain_root.ml, grainc/grainc.ml, grainc/jbuild, grainc/root_utils.ml, runtime/package-lock.json, runtime/src/core/malloc.js, runtime/src/core/memory.js, runtime/src/runtime.js, test/input/fib-gc.gr
This PR pulls in the current changes on `gc`, which include fixes to the CLI tool. In order to get the CLI tool fixed ASAP, I figure we should pull these in as-is in lieu of waiting for further progress on garbage collection.
=> Malloc+CLI fixes

src/middle_end/analyze_tail_calls.ml, src/middle_end/analyze_tail_calls.mli, src/middle_end/optimize.ml, src/middle_end/optimize_tail_calls.ml, src/middle_end/optimize_tail_calls.mli, test/input/fib-better.gr, test/test_end_to_end.ml
=> Implement tail call optimization

script/package-lock.json, script/package.json
Avoid CVE-2017-16137 https://nvd.nist.gov/vuln/detail/CVE-2017-16137
=> Upgrade script dependencies

README.md
This didn't make it into the previous pull request. @ospencer, feel free to merge when approved.
=> Update README to include new OCaml version info

src/middle_end/anftree.ml, src/typed/cmi_format.ml, src/typed/ident.ml, src/typed/typedtree.ml, src/typed/types.ml
This clears out all of the warnings when building the compiler.
=> Switch to new usage of ppx_sexp_conv

test/runner.ml
Just trying to cleanup the things @ospencer had to do to make my PR work.
=> Mirror the grainc usage for tests

compiler/esy.json, compiler/esy.lock/index.json, compiler/esy.lock/opam/dune-configurator.2.5.1/opam, compiler/esy.lock/opam/dune-private-libs.2.5.1/opam, compiler/esy.lock/opam/dune.2.5.1/opam, compiler/esy.lock/opam/extlib.1.7.7/opam, compiler/esy.lock/opam/ocaml-migrate-parsetree.1.7.2/opam, compiler/esy.lock/opam/ppxfind.1.4/opam, compiler/esy.lock/opam/ppxlib.0.13.0/opam, compiler/package.json, package.json, yarn.lock
💥 Esy released a version with my patch to disable PNP support within the esy.json
This cleans things up a little!
=> Disable pnp

runtime/package.json, yarn.lock
This release pulls in all of the bugfixes to the WASI system calls.
=> Bump @wasmer/wasi to latest

compiler/dune-project, compiler/dune-workspace, compiler/esy.json, compiler/esy.lock/index.json, compiler/esy.lock/opam/base.v0.13.2/opam, compiler/esy.lock/opam/dune.2.5.0/opam, compiler/esy.lock/opam/ocaml-migrate-parsetree.1.7.3/opam, compiler/esy.lock/opam/ppx_expect.v0.13.1/opam, compiler/grain.opam, compiler/grain_codegen.opam, compiler/grain_middle_end.opam, compiler/grain_parsing.opam, compiler/grain_typed.opam, compiler/grain_utils.opam, compiler/grainc.opam, compiler/test/dune
I started working on `js_of_ocaml` stuff and found that a lot of the dune syntax I found was specific to dune 2, so I upgraded it! 🎊
=> Upgrade to dune 2

compiler/test/input/mixedPatternMatching.gr, compiler/test/stdlib/hash.test.gr, compiler/test/stdlib/lists.test.gr, stdlib/lists.gr, stdlib/sys.gr
Updating some functions in the stdlib. Closes #84
=> Snake_case to camelCase

cli/package.json, compiler/package.json, package.json, stdlib/package.json
=> Specify Node 14 as node engine

compiler/test/stdlib/arrays.test.gr, compiler/test/stdlib/lists.test.gr, stdlib/arrays.gr, stdlib/lists.gr
Added Array.mapi and List.mapi to stdlib
Added compiler to cover both functions
=> Implement Array.mapi and List.mapi #124

runtime/src/runtime.js
Doing this as a stop-gap measure until we get to #130.
=> Bump initial table size to 1024

compiler/src/parsing/lexer.mll, compiler/src/parsing/parser.dyp
=> Fix comment parsing

README.md
https://grain-lang.org/guide 404'd for me :smile: 
And I think it should be: https://grain-lang.org/docs/ ? :thinking: 
Awesome project by the way! Excited to start playing with this :smile:
=> Updated Grain Guide Link in README

compiler/src/codegen/compcore.ml, compiler/src/codegen/transl_anf.ml
These seem to be left over from GC implementation.
=> Remove unused variables

compiler/src/codegen/compcore.ml, compiler/src/codegen/compcore.mli
Wanted to get this out of the way before starting work on moving to Binaryen :)
=> Clean up heap top

.github/workflows/ci.yml
Did some general cleanup, like upgrading actions and some formatting stuff. It now runs on MacOS in addition to Linux.
Also, trying to set things up for doing things cross-platform if we are able to get Windows working.
Finally, the last step logs the grain version to make sure the copied grainc binaries work and stuff.
=> Some updates to CI

README.md
Wasn't sure if we do PRs for docs updates.
=> Update docs to ensure node 14

compiler/test/stdlib/arrays.test.gr, stdlib/arrays.gr
I need this for writing tests for my additions to Map.
=> stdlib: Add Array.contains

README.md
=> Update README with info on Binaryen, CMake

compiler/src/codegen/compcore.re, compiler/src/codegen/mashtree.re, compiler/src/codegen/transl_anf.re
This is a prerequisite for sourcemaps.
=> Include locations in Mashtree

.github/workflows/ci.yml, compiler/esy.json, compiler/package.json, compiler/src/codegen/dune, compiler/src/codegen/mashtree.re, compiler/src/compile.re, compiler/src/middle_end/dune, compiler/src/parsing/location.re, compiler/src/parsing/parser.dyp, compiler/src/typed/dune, compiler/src/typed/includecore.re, compiler/src/typed/parmatch.re, compiler/src/typed/typepat.re, compiler/src/typed/types.re
This formats the Reason code and then adds a format checking phase to our CI.
As you can probably tell, Reason has some issues with block comments and we should probably switch them to line comments (which it seems to handle much more elegantly).
Not sure if this is enough to satisfy all of #218 - Thoughts?
I'll push up a sample of the lint failing once it passes just as an example.
=> ReasonML formatting

stdlib/asconfig.json, stdlib/build.mjs, stdlib/package.json, stdlib/stdlib-external/equal.ts, stdlib/stdlib-external/hash.ts, stdlib/stdlib-external/tsconfig.json, yarn.lock
Hopefully updating asc won't cause unforeseen issues.
=> fix: update asc and add asconfig.json

stdlib/package.json, stdlib/stdlib-external/ascutils/primitives.ts, stdlib/stdlib-external/equal.ts, stdlib/stdlib-external/hash.ts, stdlib/stdlib-external/string.ts, stdlib/stdlib-external/sys/env.ts, stdlib/stdlib-external/sys/random.ts, yarn.lock
- update AssemblyScript to latest
- avoid some alloc / free by usings static memory (`memory.data`)
- minor fixes and style improvments
=> update AssemblyScript + minor fixes and improvments

compiler/src/compile.re
This was an old step from back in the day that's no longer used.
=> Remove WithLibraries step

compiler/test/stdlib/option.test.gr, compiler/test/stdlib/result.test.gr, compiler/test/test_end_to_end.re, stdlib/option.gr, stdlib/pervasives.gr, stdlib/result.gr
Closes #244 
~~This isn't complete yet. Please review API and give thoughts. Also I did `Err` instead of `Error` can switch if asked.~~
=> Add result type

compiler/test/stdlib/option.test.gr, stdlib/option.gr
A few changes to Option.
I broke it up into separate PRs to make it clear.
fyi @c0d3d Option.toResult argument order changed.
=> Option changes

yarn.lock
This should make the security alert go away.
=> Upgrade serialize-javascript to make security vuln disappear

docs/contributor/operator_precedence.md
=> Document string concat operator

compiler/test/stdlib/list.test.gr, stdlib/list.gr
=> Stdlib: add drop and dropWhile

stdlib/list.gr
Implement #319 and makes also `length` and `sum` tail-recursive
=> Stdlib: make sum, length and count tail-recursive

docs/contributor/compiler_walkthrough.md
Closes https://github.com/grain-lang/grain/issues/201.
=> Update compiler walkthrough with our use of Binaryen

compiler/src/parsing/lexer.mll, compiler/src/parsing/parser.dyp, compiler/test/test_end_to_end.re
=> Fix parsing of negative numbers

compiler/src/typed/oprint.re
Fixes #330 
```
This expression has type a -> Void
```
=> Fix printing of type vars

stdlib/stdlib-external/ascutils/dataStructures.ts
Just something I caught while reading the Numbers PR.
=> Small comment fix I saw while reviewing numbers PR

cli/bin/compile.js, compiler/grainc/grainc.re, compiler/src/typed/env.re, compiler/test/test.re, runtime/src/utils/locators.js, stdlib/build.mjs
This addresses #18. A softball first PR to the project for me 😅
=> replace .wasm extension with .gr.wasm

stdlib/sys/file.gr
Refactor out large if-else chain to pattern matching
Fixes #337
=> Refactor filetypeFromNumber in stdlib/File

compiler/test/stdlib/map.test.gr, stdlib/map.gr
Hi, this is my first contribution so do let me know if anything's wrong.
I'd like to say the contributing guide was great and everything worked right from the start.
The [understandable] weaker points are stack traces / error messages and test assertions that don't give much info why something failed.
=> Add Map.filter and Map.reject (fixes #193)

compiler/test/stdlib/array.test.gr, stdlib/array.gr
Implemented find and findIndex funcionality on array.
=> Implement Array.find and Array.findIndex

compiler/test/stdlib/array.test.gr, stdlib/array.gr
Add fill and fillRange methods. Closes #361
=> Add array fill and fillRange methods

stdlib/array.gr
I forgot to check if input array is not empty. Closes  #357
=> fix empty array as input in Array.find function

compiler/test/stdlib/array.test.gr, stdlib/array.gr
Implemented Array.count function. Closes #359
=> Implement Array.count

compiler/test/stdlib/array.test.gr, compiler/test/stdlib/list.test.gr, stdlib/array.gr, stdlib/list.gr
Implemented product function on array and list. Closes #362
=> Implement List.product and Array.product

compiler/test/stdlib/queue.test.gr, compiler/test/test_end_to_end.re, stdlib/queue.gr
Closes #363 
Adds a Queue library to the `stdlib`.
=> Add Queue to stdlib

compiler/src/parsing/lexer.mll, compiler/test/test_end_to_end.re
=> Fix handling of new lines

compiler/src/parsing/lexer.mll, compiler/test/test_end_to_end.re
=> Fix lone hash comment

compiler/test/stdlib/list.test.gr, stdlib/list.gr
Hey guys! 
Here is some initial work on the #125 - new methods for `List` module:
- `List.take(n, list)` - takes `n` first items from the list. 
- `List.takeWhile(fn, list)` - takes elements from the list until `fn` returns true.
- `List.sub(start, len, list)` - creates a sublist for `list` starting from `start` with `len` elements
=> Add couple of new functions to the list module that will help fix #125

compiler/src/typed/env.re, compiler/src/typed/env.rei, compiler/test/input/list.gr, compiler/test/test_end_to_end.re
=> Use full filenames for persistent structures

compiler/src/parsing/lexer.mll, compiler/src/parsing/parser.dyp, compiler/test/input/adtprint.gr, compiler/test/input/basicenum.gr, compiler/test/input/mixedPatternMatching.gr, compiler/test/input/oneBranchTail.gr, compiler/test/input/recursive-equal-box.gr, compiler/test/input/recursive-equal-mut.gr, compiler/test/stdlib/hash.test.gr, compiler/test/stdlib/map.test.gr, compiler/test/test-libs/tlists.gr, compiler/test/test_end_to_end.re, stdlib/array.gr, stdlib/list.gr, stdlib/map.gr, stdlib/option.gr, stdlib/pervasives.gr, stdlib/queue.gr, stdlib/result.gr, stdlib/sys/file.gr, stdlib/sys/process.gr
=> [BREAKING] Enum/Record syntax update

Dockerfile, compiler/package.json
Was able to get some really nice cleanup in here too!
=> Fix the dockerfile after my esy changes

compiler/src/parsing/asttypes.re, compiler/src/parsing/identifier.re, compiler/src/parsing/identifier.rei, compiler/src/parsing/parsetree.re
In Discord, we talked about adding yojson to more data structures. I did this to help me log some parsetree stuff to understand the structure a bit, so I figured I would submit it.
=> Begin adding yojson to structures in parsing

compiler/src/typed/oprint.re
=> Tidy up type printing

compiler/src/parsing/parser.dyp, compiler/test/test_end_to_end.re
=> Allow newline when creating array

compiler/test/stdlib/string.test.gr, stdlib/stdlib-external/ascutils/dataStructures.ts, stdlib/stdlib-external/string.ts, stdlib/string.gr
=> feat: Implement String.indexOf, String.explode, and String.split

compiler/test/stdlib/array.test.gr, stdlib/array.gr
Needed some Array methods for AoC. I'll open an issue to document and assign to myself right now.
=> feat: add reduce/flatMap/every/some to Array stdlib

compiler/test/stdlib/list.test.gr, stdlib/array.gr, stdlib/list.gr, stdlib/queue.gr
List method conversions, which let me clean up one Queue method too.
I snuck some trailing whitespace removal in too.
I plan to add a contributor doc for stdlib patterns and update the website docs too.
=> feat!: convert fallible List methods to return Option

compiler/test/stdlib/range.test.gr, compiler/test/test_end_to_end.re, stdlib/range.gr
Some very rudimentary Range stuff that I needed/wanted for AoC.
=> feat: add initial Range stdlib module

compiler/test/stdlib/list.test.gr, stdlib/list.gr
I hacked together a `List.init` method that I wanted for day 5 of AoC. I'm pretty sure there is a better way to implement the recursion so I put a TODO asking for help making it better.
=> feat: add List.init to stdlib

compiler/src/codegen/compcore.re, compiler/src/utils/config.re, compiler/src/utils/config.rei
Prevent reference counting with `no_gc` flag.
=> feat: add CLI option for no_gc

compiler/src/utils/wasm_utils.re
While debugging our random test failure, I was reading docs about `input` and the way we were using it in these cases was the exact same as the way `really_input` works. With these changes, we no longer need to raise `End_of_file` ourselves!
=> refactor: use really_input instead of input + raising ourselves

compiler/test/stdlib/array.test.gr, stdlib/array.gr
Add filter, unique, and index variant of reduce & count to Array stdlib module.
=> feat: add reducei/counti/filter/filteri/unique to Array stdlib

compiler/src/parsing/lexer.mll
=> fix: Multiline string locs

compiler/src/middle_end/linearize.re, compiler/src/middle_end/matchcomp.re, compiler/src/parsing/ast_helper.re, compiler/src/parsing/ast_helper.rei, compiler/src/parsing/ast_iterator.re, compiler/src/parsing/ast_mapper.re, compiler/src/parsing/parser.dyp, compiler/src/parsing/parsetree.re, compiler/src/typed/parmatch.re, compiler/src/typed/printpat.re, compiler/src/typed/typedtree.re, compiler/src/typed/typedtree.rei, compiler/src/typed/typedtreeIter.re, compiler/src/typed/typedtreeMap.re, compiler/src/typed/typepat.re, compiler/test/input/mixedPatternMatching.gr
This PR adds the ability to pattern match on Arrays.
Closes #212.
=> feat: Pattern matching on arrays

compiler/test/stdlib/string.test.gr, stdlib/stdlib-external/string.ts, stdlib/string.gr
=> chore(stdlib)!: Ensure string methods are data-last

docs/contributor/standard_library.md
This is a very rough draft of contributor docs for our standard library.
Closes #464 
@ospencer @peblair I think this needs a lot of input from you both. Maybe we can use Suggestions to collaboratively edit this!
=> docs: initial stdlib contributor docs

compiler/esy.json, compiler/esy.lock/index.json, compiler/esy.lock/opam/dot-merlin-reader.3.4.2/opam, compiler/esy.lock/opam/dune-build-info.2.8.2/opam, compiler/esy.lock/opam/dune-configurator.2.8.2/opam, compiler/esy.lock/opam/dune.2.8.2/opam, compiler/esy.lock/opam/ocaml-lsp-server.1.4.0/opam, compiler/esy.lock/opam/ppxlib.0.21.0/opam
@phated let me know if it's better to do this as two separate PRs or if a single dependencies PR is fine.
=> chore: Upgrade Binaryen.ml and ocaml-lsp-server

compiler/src/typed/typecore.re, compiler/src/typed/typepat.re, compiler/test/test_end_to_end.re, stdlib/array.gr
=> fix: loop body typechecking

compiler/src/compile.re, compiler/src/typed/env.re, compiler/src/typed/typemod.re, compiler/src/utils/config.re, compiler/src/utils/config.rei, stdlib/runtime/dataStructures.gr, stdlib/runtime/debug.gr, stdlib/runtime/equal.gr, stdlib/runtime/gc.gr, stdlib/runtime/malloc.gr, stdlib/runtime/numberUtils.gr, stdlib/runtime/numbers.gr, stdlib/runtime/string.gr, stdlib/runtime/unsafe/errors.gr, stdlib/runtime/unsafe/memory.gr, stdlib/runtime/unsafe/tags.gr, stdlib/runtime/unsafe/wasmf32.gr, stdlib/runtime/unsafe/wasmf64.gr, stdlib/runtime/unsafe/wasmi32.gr, stdlib/runtime/unsafe/wasmi64.gr
Closes #544.
@phated Why yes, I _did_ stay up until 4am getting this done.
=> chore: Allow setting compiler flags at the start of a file

compiler/src/codegen/compcore.re
=> feat: Enable Binaryen optimizations

stdlib/sys/file.gr
Closes #576 
See also: https://github.com/grain-lang/grain-lang.org/pull/166
=> chore: Update inline docs for sys/file

runtime/src/utils/utils.js
=> chore: Don't check for alignment of boxed numbers

stdlib/sys/file.gr
@ospencer I think I messed these up. Can you confirm?
=> chore: fix mistakes in my sys/file docs

cli/package.json, package.json, yarn.lock
I wanted to rebase pkg on upstream and then realized it was a pain to get yarn to sync those changes, so I just ended up publishing a scoped version of pkg. This also includes some improvements that I found while working on my PR for them.
Closes #591
=> chore: Switch to published scoped pkg

compiler/dune-project, compiler/esy.json, compiler/src/codegen/emitmod.re, compiler/src/compile.re, compiler/src/parsing/driver.re, compiler/src/parsing/driver.rei, compiler/src/typed/cmi_format.re, compiler/src/typed/cmi_format.rei, compiler/src/typed/dependency_graph.re, compiler/src/typed/dependency_graph.rei, compiler/src/typed/dune, compiler/src/typed/env.re, compiler/src/typed/env.rei, compiler/src/typed/module_resolution.re, compiler/src/typed/module_resolution.rei, compiler/src/typed/typemod.re, compiler/src/utils/config.re, compiler/src/utils/config.rei, compiler/src/utils/consistbl.re, compiler/src/utils/consistbl.rei, compiler/src/utils/fs_access.re
This has the added benefit of being far less harsh on the filesystem—the unit tests run about 40% faster.
=> fix(compiler): Implement proper dependency resolver

compiler/test/stdlib/queue.test.gr, compiler/test/stdlib/stack.test.gr, stdlib/queue.gr, stdlib/stack.gr
=> chore(stdlib)!: rename Queue/Stack lib methods

runtime/src/core/closures.js
=> chore(runtime): feed runtime into jsFunc

stdlib/runtime/numberUtils.gr
=> chore(runtime): remove dtoa_buffered

compiler/src/parsing/ast_helper.re
=> chore: Use Option.value with default instead of switch statements

compiler/src/parsing/lexer.mll
=> Remove extra PIPE

compiler/test/stdlib/queue.test.gr, compiler/test/stdlib/stack.test.gr, stdlib/queue.gr, stdlib/stack.gr
Reopening this one now that #632 is merged. Closes #493
=> feat: Rename Queue/Stack functions & deprecate old ones

compiler/test/stdlib/queue.test.gr, compiler/test/stdlib/stack.test.gr, stdlib/queue.gr, stdlib/stack.gr
Fixes #627 
---
Adds `size` method in `Queue` and `Stack`.
=> feat(stdlib): add `Queue.size` and `Stack.size`

stdlib/pervasives.gr, stdlib/runtime/numbers.gr
=> feat: Export number runtime functions as operators & deprecate old identifiers

compiler/test/stdlib/sys.file.test.gr, compiler/test/test_end_to_end.re, stdlib/sys/file.gr
=> fix(stdlib): fdWrite range error

compiler/test/test_end_to_end.re, stdlib/runtime/equal.gr, stdlib/runtime/numbers.gr
=> fix(compiler): properly handle special float equality

compiler/test/stdlib/range.test.gr, stdlib/range.gr
=> feat(stdlib): add Range.map

CONTRIBUTING.md
=> Fix broken discord link

compiler/src/parsing/parser.dyp, compiler/test/test_end_to_end.re
=> fix: else clause on new line

compiler/test/stdlib/array.test.gr, stdlib/array.gr
This adds an `Array.reverse()` function that takes a source array and returns a new array with the elements reversed. It also adds a test in the compiler tests.
This helps bring `Array` and `List` closer to parity.
I am not sure where to put the documentation for this function.
Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>
=> feat(stdlib): Add Array.reverse() function

docs/contributor/commits_pull_requests_and_merging.md
First draft of core team docs for commits, pull requests, and merging. Please make suggestions!
Closes #685
=> chore(docs): Add contributor docs for commits, PRs & merging

compiler/test/stdlib/string.test.gr, stdlib/string.gr
This contains String.charAt - however, I've reversed the arguments to be "data-last" because we haven't made a decision on it yet and it is better to be consistent.
=> feat(stdlib): Add String.chatAt function

compiler/src/parsing/ast_helper.re, compiler/src/parsing/ast_helper.rei, compiler/src/parsing/ast_iterator.re, compiler/src/parsing/ast_mapper.re, compiler/src/parsing/parser.dyp, compiler/src/parsing/parsetree.re, compiler/src/typed/typemod.re, compiler/test/__snapshots__/enums.ae26523b.0.snapshot, compiler/test/__snapshots__/records.60c0a141.0.snapshot, compiler/test/suites/enums.re, compiler/test/suites/records.re
This pulls the compiler change commit directly from that PR and adds tests for the feature.
@ospencer Oh god of `wat`, can you check over the snapshots?
=> feat: Support mutually recursive data definitions

compiler/test/stdlib/float32.test.gr, compiler/test/stdlib/float64.test.gr, stdlib/float32.gr, stdlib/float64.gr
This contains the NaN and Infinity constants for Float32 and Float64.
=> feat(stdlib): Add Float32/Float64 constants for infinity/nan

compiler/test/stdlib/array.test.gr, stdlib/array.gr
Hello. I tried to solve the problem from issue #694. This PR adds Array.unzip function and some tests for Array.zip and Array.unzip.
=> add Array.unzip and tests for zip and unzip

.gitignore, cli/bin/compile.js, cli/bin/doc.js, cli/bin/exec.js, cli/bin/grain.js, cli/bin/graindoc.js, cli/bin/lsp.js, compiler/dune-project, compiler/esy.json, compiler/graindoc/docblock.re, compiler/graindoc/dune, compiler/graindoc/graindoc.re, compiler/graindoc/jsoo_hacks.js, compiler/graindoc/jsoo_header.re, compiler/graindoc/runtime.js, compiler/src/diagnostics/comments.re, compiler/src/typed/cmi_format.re, compiler/src/typed/types.re, compiler/src/utils/markdown.re, compiler/src/utils/range.re
Rebased #410 on top of `main` instead of `master`
I believe this needs to be changed a bunch from my original implementation so marking it as Draft.
=> feat: Add GrainDoc for markdown generation using doc comments

compiler/src/diagnostics/comments.re
While writing some docs, I noticed that the sections were not ordered by source location, and it seems to be due to Hashtbl not doing a normal `int` compare, so I switched them to just an `IntMap` and that seems to solve the issue I hit.
=> fix(graindoc): Correctly order sections from source code

stdlib/array.gr
This adds GrainDoc for the Array module in our standard library. I skewed a fair bit from what was on the website, so please review with focus and make any suggestions for changes you want!
Also helpful to generate the markdown with GrainDoc and view it in vscode markdown preview (It helped me catch a few weird issues for which I've submitted PRs).
=> feat(stdlib): Add GrainDoc to Array module

compiler/src/diagnostics/comments.re
While implementing `@since` I ran into an issue where as soon as the `Str.global_replace` didn't match the group `([ ]+([^:]+):)?`, it stopped trying to match that group at all for future attributes. This meant that `@since` wouldn't be parsed after `@returns` attribute.
I fixed this by changing the way we parse attributes to parse **just** the attribute name and content into 2 groups, and then we use a custom regexp parser for each attribute's contents. This solves this issue I encountered, but allows us to more easily allow custom formats for attribute contents.
=> fix(graindoc): Correctly parse attributes, no matter the order

compiler/graindoc/docblock.re, compiler/graindoc/graindoc.re, compiler/src/diagnostics/comments.re, compiler/src/utils/html.re, compiler/src/utils/version.re, stdlib/range.gr
=> feat(graindoc): Support `@since` and `@history` attributes

stdlib/range.md
This is just the generation of the docs for our Range module that I've been using for my examples.
=> chore(stdlib): Generate markdown for Range docs

compiler/src/parsing/lexer.mll, compiler/test/runner.re, compiler/test/suites/strings.re
=> fix(compiler): Return full string locations from parsing

compiler/graindoc/config/dune, compiler/graindoc/config/flags.re, compiler/graindoc/dune
Added the missing Dune magic to make the Windows version of the Graindoc exe link properly
=> fix(compiler): Added the link time fixes for Windows to Graindoc

compiler/test/stdlib/int32.test.gr, compiler/test/stdlib/int64.test.gr, stdlib/int32.gr, stdlib/int64.gr
=> feat(stdlib): Int32/64 clz, ctz, popcnt, rotl, rotr, eq, ne, eqz

stdlib/queue.gr, stdlib/runtime/numbers.gr, stdlib/stack.gr
Closes #642
Drafting this in preparation for 0.4.0
=> chore(stdlib)!: Remove deprecated functions

compiler/test/stdlib/buffer.test.gr, compiler/test/suites/stdlib.re, stdlib/buffer.gr
Closes #707 
More detailed description to come soon!
=> feat(stdlib): Add buffer module

compiler/src/typed/translprim.re, compiler/src/typed/typed_well_formedness.re, compiler/test/__snapshots__/basic_functionality.1bf5759c.0.snapshot, compiler/test/input/unsafeWasmGlobals.gr, compiler/test/test-libs/unsafeWasmGlobalsExports.gr, stdlib/array.gr, stdlib/buffer.gr, stdlib/bytes.gr, stdlib/int32.gr, stdlib/int64.gr, stdlib/runtime/string.gr, stdlib/string.gr
Implementation based on strategy discussed on Discord. Marking this as a draft until we decide that this is the approach we want to take.
(Blocked by #771)
=> feat(compiler)!: Add typed well-formedness pass which forbids usage of WasmXX values outside of `@disableGC` context

stdlib/array.md, stdlib/buffer.md, stdlib/number.md, stdlib/sys/file.md
Updates the "next" to 0.4.0 and also generate buffer docs
=> chore(stdlib): Regenerate markdown docs

.github/workflows/release.yml
Casual breaking changes all over this tool....
Trying to figure out where they broke us and fix on our side.
=> chore(ci): Fix releaser

compiler/test/suites/print.re, stdlib/runtime/string.gr
=> fix(stdlib): Fix memory issue in list printing

cli/bin/exec.js, cli/bin/grain.js
Just need to specify that this needs to be forwarded.
=> fix(cli): Forward stdlib option to lsp and graindoc

js-runner/LICENSE, js-runner/README.md, js-runner/package.json, stdlib/LICENSE, stdlib/README.md, stdlib/package.json
Closes #619
I'll ask some questions inline.
=> chore: Improve js-runner & stdlib as npm packages

compiler/src/parsing/parser.dyp, compiler/test/suites/arrays.re
=> fix(compiler): Parse array set with newline correctly

compiler/test/stdlib/char.test.gr, stdlib/char.gr
=> fix(stdlib): Fix Char.code memory issue

compiler/grainformat/reformat.re, compiler/test/formatter_inputs/enums.gr, compiler/test/formatter_inputs/function_params.gr, compiler/test/formatter_outputs/enums.gr, compiler/test/formatter_outputs/function_params.gr
Fixes enum indentation, spacing for functions that return lambdas
=> fix(grainfmt): fix some spacing issues with the formatter

stdlib/array.gr
Replace while loops where it makes sense with for loops satisfying #1009
=> chore(stdlib): Convert while loops to for loops in Array (#1009)

compiler/test/stdlib/array.test.gr, stdlib/array.gr, stdlib/array.md
Implement Array.sort via the quicksort algorithm as talked about here: #125
=> feat(stdlib): Add sort function to Array module (#125)

compiler/grainformat/reformat.re, compiler/test/formatter_inputs/enums.gr, compiler/test/formatter_inputs/matches.gr, compiler/test/formatter_inputs/nested_matches.gr, compiler/test/formatter_outputs/enums.gr, compiler/test/formatter_outputs/matches.gr
Fixes #1025 
Fixes #1024
Resugars pattern match strings properly
Prints recursive enum declarations properly
Extra tests added
=> fix(grainfmt): Resugar match lists properly

compiler/test/stdlib/array.test.gr, stdlib/array.gr, stdlib/array.md
Signed-off-by: Itay Dafna <i.b.dafna@gmail.com>
Addresses #795 
Usage: 
```reason
let myarray = [> 1, 2, 3, 4, 5]
Array.rotate(myarray, 2)
print(myarray) // [> 4, 5, 1, 2, 3]
let myarray2 = [> 1, 2, 3, 4, 5]
Array.rotate(myarray2, -1)
print(myarray2) // [> 2, 3, 4, 5, 1]
```
TODO:
=> feat(stdlib): Add rotate function in Array module

stdlib/range.md, stdlib/regex.md
The GrainDoc on the regex libary was out of date.
=> chore(stdlib): Regenerate GrainDoc For stdlib.

compiler/test/__snapshots__/stdlib.24cb9bbf.0.snapshot, compiler/test/__snapshots__/stdlib.323e410a.0.snapshot, compiler/test/__snapshots__/stdlib.5fe88631.0.snapshot, compiler/test/__snapshots__/stdlib.648f406e.0.snapshot, compiler/test/__snapshots__/stdlib.6bf88430.0.snapshot, compiler/test/__snapshots__/stdlib.6de47be2.0.snapshot, compiler/test/__snapshots__/stdlib.8300ad7c.0.snapshot, compiler/test/__snapshots__/stdlib.91a94037.0.snapshot, compiler/test/__snapshots__/stdlib.a70e79ca.0.snapshot, compiler/test/__snapshots__/stdlib.d28dee65.0.snapshot, compiler/test/__snapshots__/stdlib.d4faa5bf.0.snapshot, compiler/test/__snapshots__/stdlib.e306600a.0.snapshot, compiler/test/__snapshots__/stdlib.e6349872.0.snapshot, compiler/test/stdlib/list.test.gr, stdlib/list.gr
Implement List.sort with a mergesort algorithm.  Result returns a new list.
=> feat(stdlib): List.sort via a mergesort (#125)

compiler/test/stdlib/string.test.gr, stdlib/string.gr, stdlib/string.md
Adds a new reverse() function to the String standard library.
Signed-off-by: Matt Butcher <matt.butcher@fermyon.com>
=> feat(stdlib): Add reverse function to String module

stdlib/set.gr, stdlib/set.md
chore(stdlib): Add GrainDoc To Set Library
related tp #702.
=> chore(stdlib): Add Graindoc to Set library

stdlib/number.md
=> chore: Regenerate Number docs

compiler/src/typed/module_resolution.re
=> fix(compiler): Consider invalid CMIs as out of date and recompile

stdlib/option.gr, stdlib/option.md
Add GrainDoc to option Library.
related: #702.
=> chore(stdlib): Add GrainDoc to option Library

stdlib/float64.gr, stdlib/float64.md
Add GrainDoc to float64 Library.
related: #702.
=> chore(stdlib): Add GrainDoc to float64 Library.

stdlib/regex.gr, stdlib/regex.md
=> chore(stdlib)!: Add Types Aliases to regex lib

compiler/src/compile.re, compiler/src/typed/ctype.re, compiler/src/typed/ctype.rei, compiler/test/__snapshots__/functions.6eacded0.0.snapshot, compiler/test/__snapshots__/functions.7a8986a5.0.snapshot, compiler/test/__snapshots__/functions.b632a2ab.0.snapshot
This further stabilizes snapshots, and should unblock #1151!
=> chore(compiler): Reset Ctype between compilations

compiler/test/stdlib/random.test.gr, compiler/test/stdlib/sys.random.test.gr, stdlib/random.gr, stdlib/random.md, stdlib/sys/random.gr, stdlib/sys/random.md
This PR adds support for pseudo-random number generation in Grain. I'm marking it as a draft so that we can discuss what other APIs would be good to have in here.
=> feat(stdlib): Add library for pseudo-random number generation

compiler/esy.json, compiler/esy.lock/index.json
It'd be great to have @ospencer rebase on this and test the branch that needed the v107 fix in CI.
=> chore(compiler): Upgrade to binaryen 107

compiler/grainformat/format.re, compiler/test/formatter_inputs/ifthenelse.gr, compiler/test/formatter_outputs/ifthenelse.gr
Fixes an edge case where if/then/else where then is a block and else is a single line
=> fix(grainfmt): Properly handle if/then/else line breaks

stdlib/set.gr, stdlib/set.md
Update set to match the wording used in the Map documentation.
=> chore(stdlib): Update docs in Set module

compiler/src/language_server/hover.re
This reworks the hover pattern match so we can look up type definitions on idents. This allows us to use the compiler machinery to avoid any bespoke printing code while also supporting the following hovers:
We should also expand this pattern match to handle let-bindings because I'd like to see the record definition where the variable is defined too.
=> Rework hovers to show record/enum types on ident hover

stdlib/set.gr, stdlib/set.md
We shouldn't be leaking the "Bucket" record.
=> chore(stdlib): Correct docs for Set module

compiler/grainformat/grainformat.re, compiler/src/language_server/hover.re, compiler/src/language_server/sourcetree.re
This PR displays the declaration of any type that has a declaration.
=> feat(lsp): Display type declarations on hover

compiler/src/middle_end/linearize.re, compiler/src/typed/ctype.re, compiler/src/typed/type_utils.re, compiler/test/suites/types.re
=> fix(compiler): Fix compilation of functions annotated with alias

stdlib/array.gr, stdlib/array.md, stdlib/number.gr, stdlib/number.md, stdlib/regex.gr, stdlib/regex.md, stdlib/stack.gr, stdlib/stack.md
This updates some stdlib documentation for consistency.
=> chore(stdlib): Update some docs for consistency

stdlib/buffer.gr, stdlib/buffer.md, stdlib/runtime/numbers.gr, stdlib/string.gr, stdlib/string.md
While working on the Pervasives docs, I found a few things that could be cleaned up.
=> chore(stdlib): Cleanup some docs and comments

stdlib/pervasives.gr, stdlib/pervasives.md
This relies on a bunch of the other PRs that I submitted, so marking it as draft until I can rebase.
This updates the Pervasives module with graindoc so we don't wipe away the docs when we auto-generate them for the website.
=> chore(stdlib): Add docs to the Pervasives module

compiler/test/stdlib/bigint.test.gr, compiler/test/stdlib/int32.test.gr, compiler/test/stdlib/int64.test.gr, stdlib/runtime/numbers.gr
=> fix(stdlib): Make toNumber functions respect Number invariants

compiler/test/__snapshots__/stdlib.24cb9bbf.0.snapshot, compiler/test/__snapshots__/stdlib.5fe88631.0.snapshot, compiler/test/__snapshots__/stdlib.648f406e.0.snapshot, compiler/test/__snapshots__/stdlib.6bf88430.0.snapshot, compiler/test/__snapshots__/stdlib.6de47be2.0.snapshot, compiler/test/__snapshots__/stdlib.8300ad7c.0.snapshot, compiler/test/__snapshots__/stdlib.91a94037.0.snapshot, compiler/test/__snapshots__/stdlib.a70e79ca.0.snapshot, compiler/test/__snapshots__/stdlib.d28dee65.0.snapshot, compiler/test/__snapshots__/stdlib.d4faa5bf.0.snapshot, compiler/test/__snapshots__/stdlib.e306600a.0.snapshot, compiler/test/__snapshots__/stdlib.e6349872.0.snapshot, compiler/test/stdlib/array.test.gr, compiler/test/stdlib/list.test.gr, stdlib/array.gr, stdlib/array.md, stdlib/list.gr, stdlib/list.md
- Added zip and unzip to list to bring it up to parity with array
- Added reduceRight to array
- Added zipWith to both array and list
=> feat(stdlib): Implement List.zip, List.unzip, List.zipWith, Array.reduceRight, Array.zipWith

compiler/graindoc/docblock.re, compiler/graindoc/graindoc.re, compiler/src/codegen/compcore.re, compiler/src/formatting/format.re, compiler/src/formatting/res_doc.re, compiler/src/middle_end/anftree.re, compiler/src/middle_end/anftree.rei, compiler/src/middle_end/matchcomp.re, compiler/src/middle_end/optimize.re, compiler/src/typed/includemod.re, compiler/src/typed/module_resolution.re, compiler/src/typed/typecore.re, compiler/src/typed/typedtree.rei, compiler/src/typed/typemod.re, compiler/src/typed/typetexp.re, compiler/src/utils/config.re, compiler/src/utils/fs_access.re, compiler/src/utils/wasm_utils.re, compiler/test/formatter_inputs/infix.gr, compiler/test/formatter_outputs/infix.gr, compiler/test/stdlib/map.test.gr, compiler/test/stdlib/set.test.gr, js-runner/src/core/closures.js, js-runner/src/runner.js, stdlib/array.gr, stdlib/map.gr, stdlib/pervasives.gr, stdlib/regex.gr, stdlib/runtime/numbers.gr, stdlib/set.gr
Standardize The Style Of TODOs throughout the compiler and stdlib.
Closes #1193
=> chore: Make style of TODOs consistent

compiler/src/utils/literals.re, compiler/test/stdlib/number.test.gr, compiler/test/suites/numbers.re, stdlib/number.gr, stdlib/number.md, stdlib/runtime/numbers.gr, stdlib/runtime/numbers.md
I discovered a bug in bigint literals that didn't let me write a test the way I wanted to, so I went ahead and fixed it in this PR (different commit).
Closes #1392
=> feat(stdlib): Implement `isFloat`, `isInteger` & `isRational` in Number module

stdlib/runtime/numbers.gr
Closes #304 
The operations have been validated as safe and the rational operations are overflow proof.
=> chore(stdlib): Resolve #304

compiler/src/formatting/format.re, compiler/test/formatter_inputs/records.gr, compiler/test/formatter_outputs/records.gr
=> fix(grainfmt): Fixed the formatting of comments within a record

compiler/src/formatting/format.re, compiler/test/formatter_inputs/list_sugar.gr, compiler/test/formatter_outputs/list_sugar.gr
Comments within lists were being discarded.
Fixes #1417
=> fix(grainfmt): Handle comments within lists

compiler/test/stdlib/immutablepriorityqueue.test.gr, compiler/test/stdlib/priorityqueue.test.gr, stdlib/immutablepriorityqueue.gr, stdlib/immutablepriorityqueue.md, stdlib/priorityqueue.gr, stdlib/priorityqueue.md
Minor improvements to `PriorityQueue` & `ImmutablePriorityQueue`
- Implemented `fromArray` on both modules for parity with other data structures
- Implemented more efficient algorithm for constructing a mutable PQ from a list/array, with worst-case O(n) asymptotic running time up from O(nlog(n))
=> feat(stdlib): Implement PriorityQueue.fromArray and ImmutablePriorityQueue.fromArray

compiler/test/stdlib/number.test.gr, stdlib/number.gr, stdlib/number.md
This pr adds tests and fixes a few functions to not fial on `NaN` and `Infinity`
=> fix(stdlib): Fix handling of `NaN` and `Infinity` in Number stdlib

compiler/test/stdlib/number.test.gr, stdlib/runtime/numbers.gr
Resolves the bug discovered in #1443
=> fix(runtime): Handle bigint mul/div within Number correctly

compiler/test/__snapshots__/basic_functionality.711a4824.0.snapshot, compiler/test/input/letMutForLoop.gr, compiler/test/input/memoryBase/asserts.gr, compiler/test/input/patternMatchUnsafeWasm.gr, compiler/test/stdlib/array.test.gr, compiler/test/stdlib/wasmf32.test.gr, compiler/test/stdlib/wasmf64.test.gr, compiler/test/stdlib/wasmi32.test.gr, compiler/test/stdlib/wasmi64.test.gr, compiler/test/test-libs/unsafeWasmGlobalsExports.gr, stdlib/array.gr, stdlib/buffer.gr, stdlib/bytes.gr, stdlib/exception.gr, stdlib/int32.gr, stdlib/int64.gr, stdlib/map.gr, stdlib/pervasives.gr, stdlib/runtime/bigint.gr, stdlib/runtime/equal.gr, stdlib/runtime/numbers.gr, stdlib/runtime/stringUtils.gr, stdlib/runtime/unsafe/conv.gr, stdlib/runtime/unsafe/conv.md, stdlib/runtime/unsafe/printWasm.gr, stdlib/runtime/utils/printing.gr, stdlib/string.gr, stdlib/sys/time.gr
=> chore(stdlib): Replace most `@disableGC` annotations with `@unsafe`

compiler/src/typed/typemod.re, compiler/test/suites/exports.re
=> fix(compiler): Raise appropriate error on unbound export

cli/bin/grain.js, compiler/graindoc/graindoc.re, compiler/src/compile.re, compiler/src/compile.rei, compiler/src/language_server/code_file.re, compiler/src/middle_end/linearize.re, compiler/src/parsing/driver.re, compiler/src/parsing/driver.rei, compiler/src/typed/dependency_graph.re, compiler/src/typed/dependency_graph.rei, compiler/src/typed/module_resolution.re, compiler/src/typed/module_resolution.rei
=> fix(compiler): Prevent stack overflows when compiling long blocks

stdlib/stack.gr, stdlib/stack.md
Add Since Documenation And History To Stack Libary
Closes #1497
=> chore(graindoc): Add `since` attributes to Stack module

compiler/test/stdlib/pervasives.test.gr, stdlib/number.gr, stdlib/number.md, stdlib/runtime/compare.gr, stdlib/runtime/numbers.gr, stdlib/runtime/numbers.md
=> fix(stdlib): Fix NaN comparisons

compiler/src/compile.re, compiler/src/parsing/driver.re, compiler/src/parsing/driver.rei
Closes #599 
Provides about a 10% compilation speedup in JS.
=> feat(compiler): Cache parsetrees during compilation process

compiler/src/middle_end/matchcomp.re, compiler/test/__snapshots__/pattern_matching.0fa61137.0.snapshot, compiler/test/__snapshots__/pattern_matching.25930935.0.snapshot, compiler/test/__snapshots__/pattern_matching.9ffaa7a7.0.snapshot, compiler/test/__snapshots__/pattern_matching.be46eb0e.0.snapshot, compiler/test/suites/pattern_matching.re
=> feat(compiler): Add ability to match on low level wasm types

cli/bin/grain.js, compiler/src/utils/config.re, compiler/src/utils/config.rei
Please, feel free to request any changes
=> chore!: Remove --parser-debug-level (#1311)

compiler/test/stdlib/array.test.gr, stdlib/array.gr, stdlib/array.md
=> feat(stdlib)!: Support zipping arrays of different sizes

compiler/src/parsing/lexer.re, compiler/test/__snapshots__/basic_functionality.31e0d562.0.snapshot, compiler/test/__snapshots__/basic_functionality.4d1501b9.0.snapshot, compiler/test/__snapshots__/basic_functionality.8e01d666.0.snapshot, compiler/test/suites/basic_functionality.re
This pr implement `Infinity` and `NaN` syntax as I was talking about in dms with Oscar.
Closes: #693
=> feat(compiler)!: Implement `Infinity` and `NaN` syntax

stdlib/array.gr, stdlib/priorityqueue.gr, stdlib/regex.gr, stdlib/runtime/atoi/parse.gr, stdlib/runtime/exception.gr, stdlib/runtime/string.gr, stdlib/runtime/unsafe/conv.gr, stdlib/string.gr, stdlib/sys/file.gr, stdlib/sys/process.gr, stdlib/sys/random.gr, stdlib/sys/time.gr
This PR refactors the std lib to use early returns where it's ergonomic/applicable.
=> chore(stdlib): Utilize early return where beneficial

compiler/src/formatting/format.re, compiler/src/middle_end/anf_helper.re, compiler/src/middle_end/anf_helper.rei, compiler/src/middle_end/linearize.re, compiler/src/parsing/ast_helper.re, compiler/src/parsing/ast_helper.rei, compiler/src/parsing/ast_iterator.re, compiler/src/parsing/ast_mapper.re, compiler/src/parsing/parser.mly, compiler/src/parsing/parser_header.re, compiler/src/typed/parmatch.re, compiler/src/typed/translprim.re, compiler/src/typed/typecore.re, compiler/src/typed/typedecl.re, compiler/src/typed/typetexp.re, compiler/test/suites/arrays.re, compiler/test/suites/basic_functionality.re, compiler/test/suites/blocks.re, compiler/test/suites/chars.re, compiler/test/suites/parsing.re, compiler/test/suites/strings.re
=> chore(compiler): Use meaningful names in ast_helper

compiler/src/codegen/compcore.re, compiler/src/codegen/transl_anf.re, compiler/src/middle_end/anf_utils.re, compiler/src/middle_end/linearize.re, compiler/src/typed/translprim.re, compiler/src/typed/typed_well_formedness.re, compiler/src/typed/typedtree.re, compiler/src/typed/typedtree.rei, compiler/src/typed/typemod.re, compiler/src/typed/typetexp.re, compiler/test/suites/optimizations.re
=> feat(compiler): Propagate attribute locations to Anftree

compiler/test/__snapshots__/stdlib.179d20b9.0.snapshot, compiler/test/__snapshots__/stdlib.24cb9bbf.0.snapshot, compiler/test/__snapshots__/stdlib.323e410a.0.snapshot, compiler/test/__snapshots__/stdlib.5fe88631.0.snapshot, compiler/test/__snapshots__/stdlib.648f406e.0.snapshot, compiler/test/__snapshots__/stdlib.6bf88430.0.snapshot, compiler/test/__snapshots__/stdlib.6de47be2.0.snapshot, compiler/test/__snapshots__/stdlib.8300ad7c.0.snapshot, compiler/test/__snapshots__/stdlib.91a94037.0.snapshot, compiler/test/__snapshots__/stdlib.a70e79ca.0.snapshot, compiler/test/__snapshots__/stdlib.c09a513a.0.snapshot, compiler/test/__snapshots__/stdlib.d28dee65.0.snapshot, compiler/test/__snapshots__/stdlib.d4faa5bf.0.snapshot, compiler/test/__snapshots__/stdlib.d887bb04.0.snapshot, compiler/test/__snapshots__/stdlib.dae8b12a.0.snapshot, compiler/test/__snapshots__/stdlib.e306600a.0.snapshot, compiler/test/__snapshots__/stdlib.e6349872.0.snapshot, compiler/test/suites/stdlib.re
=> chore(compiler): Don't arbitrarily import List in stdlib tests

stdlib/runtime/atoi/parse.gr
=> feat(stdlib): Remove parseInt dependency on Pervasives

compiler/src/parsing/well_formedness.re, compiler/test/__snapshots__/provides.2a5f527b.0.snapshot, compiler/test/suites/includes.re, compiler/test/suites/provides.re, compiler/test/test-libs/sameProvide.gr, stdlib/runtime/numbers.gr
=> fix(compiler)!: Disallow multiple `provide`s of the same value

compiler/src/codegen/transl_anf.re, compiler/src/middle_end/linearize.re, compiler/src/middle_end/matchcomp.re, compiler/src/parsing/ast_helper.re, compiler/src/parsing/ast_helper.rei, compiler/src/parsing/asttypes.re, compiler/src/parsing/lexer.re, compiler/src/parsing/parser.mly, compiler/src/parsing/parsetree.re, compiler/src/parsing/well_formedness.re, compiler/src/typed/checkertypes.re, compiler/src/typed/parmatch.re, compiler/src/typed/printpat.re, compiler/test/stdlib/rational.test.gr, compiler/test/suites/numbers.re, compiler/test/suites/stdlib.re, stdlib/rational.gr, stdlib/rational.md, stdlib/runtime/numbers.gr, stdlib/runtime/numbers.md
Implements rational number type and stdlib. Literals are suffixed with `r` (like `1/4r`) and stdlib contains basic arithmetic and comparison operations.
Closes #1524
=> feat(compiler): Rational number type

compiler/src/diagnostics/modules.re, compiler/src/language_server/hover.re, compiler/src/language_server/sourcetree.re, compiler/src/middle_end/linearize.re, compiler/src/typed/env.re, compiler/src/typed/env.rei, compiler/src/typed/typecore.re, compiler/src/typed/typedtree.re, compiler/src/typed/typedtree.rei, compiler/src/typed/typedtreeIter.re, compiler/src/typed/typedtreeMap.re, compiler/src/typed/types.re
=> feat(grainlsp): Provide hovers on use statements

compiler/src/codegen/compcore.re, compiler/src/language_server/sourcetree.re, compiler/src/middle_end/linearize.re, compiler/src/parsing/ast_helper.re, compiler/src/parsing/ast_helper.rei, compiler/src/parsing/parser.mly, compiler/src/typed/ctype.re, compiler/src/typed/datarepr.re, compiler/src/typed/env.re, compiler/src/typed/includemod.re, compiler/src/typed/mtype.re, compiler/src/typed/path.re, compiler/src/typed/path.rei, compiler/src/typed/printtyp.re, compiler/src/typed/subst.re, compiler/src/typed/typed_well_formedness.re, compiler/src/typed/typemod.re, compiler/src/typed/types.re, compiler/test/suites/exceptions.re
=> fix(compiler): Inline record exception constructors

compiler/src/typed/typecore.re, compiler/test/__snapshots__/functions.0b8146ea.0.snapshot, compiler/test/suites/functions.re
=> fix(compiler): Allow early return in let bindings

stdlib/uint16.gr, stdlib/uint16.md, stdlib/uint8.gr, stdlib/uint8.md
While working on #1738 I noticed some of the docs were incorrect, this pr corrects them.
=> chore(stdlib): Correct Uint docs

cli/bin/grain.js
Turns out when i did up #1589 I forgot to update the cli information. Small pr to update that.
=> chore(cli): Change cli option info on tail calls

compiler/test/stdlib/rational.test.gr, stdlib/rational.gr, stdlib/rational.md
This adds `toIntegerRation` and `fromIntegerRation`, to the `rational` library.
This doesnt close #1672, but it adds a few of the functions for it.
=> feat(stdlib): Add `toIntegerRatio` and `fromIntegerRatio`  to Rational Library

compiler/test/stdlib/option.test.gr, compiler/test/stdlib/result.test.gr, stdlib/marshal.gr, stdlib/option.gr, stdlib/option.md, stdlib/result.gr, stdlib/result.md
=> feat(stdlib)!: Replace `Result`/`Option` `and`/`or` functions with operators

compiler/src/typed/typemod.re, compiler/test/suites/includes.re, compiler/test/test-libs/provideType.gr, compiler/test/test-libs/reprovideType.gr
=> fix(compiler): Re-providing types

compiler/src/middle_end/linearize.re, compiler/src/typed/typemod.re, compiler/test/suites/includes.re, compiler/test/suites/provides.re, compiler/test/test-libs/provideContents.gr, compiler/test/test-libs/provideType.gr, compiler/test/test-libs/reprovideContents.gr, compiler/test/test-libs/reprovideType.gr
=> fix(compiler): Allow reproviding from submodules

compiler/src/typed/typemod.re
Very small pr to fix the style of a `TODO` to line up with the rest.
=> chore(compiler): Change todo comment to match style in project

stdlib/buffer.gr, stdlib/buffer.md
Small pr to update the wording on `Buffer.addchar` to be more similar to the rest of the stdlib docs.
=> chore(stdlib): Update wording of `Buffer.addChar` docs

compiler/src/typed/typed_well_formedness.re, compiler/test/suites/provides.re
=> fix(compiler): Allow providing values of types provided later

compiler/esy.json, compiler/package.json
Trying to build our JS version with 2 jobs on Windows in the hopes we stop OoM flakes.
=> chore(compiler): Build JS version with 2 jobs on Windows

cli/bin/grainrun.js
Thanks @av8ta for catching this!
=> fix(cli): Correct typo in printing stack

stdlib/README.md
This pr updates the example code in the stdlib `readme` for `v0.6`. While I was it, I figured a `contributing` section in the `readme` would be helpful.
=> chore(docs): Update stdlib README

compiler/test/stdlib/int64.test.gr, stdlib/int64.gr, stdlib/int64.md
This pr adds a power function to the `Int64` library. This pr will need to be updated after #1935 is merged.
=> feat(stdlib): Add `**` operator to `Int64` module

compiler/src/typed/printtyp.re
=> fix(lsp): Fix lsp crash when hovering on function with default arg

stdlib/array.gr, stdlib/array.md
Small pr to cleanup the array library a bit and fixes a few spelling mistakes.
=> chore(stdlib): Fix spelling mistakes in Array library docs

compiler/test/stdlib/queue.test.gr, stdlib/queue.gr, stdlib/queue.md
adds `toList` and `fromList` to the queue and Immutable queue modules.
Blocked by: #1865
=> feat(stdlib): Add `toList` and `fromList` functions to `Queue` module

stdlib/buffer.gr, stdlib/buffer.md
This pr adds examples to the `Buffer` library.
=> chore(stdlib): Add examples to `Buffer` module

stdlib/rational.gr, stdlib/rational.md
This pr adds examples to the docs for `rational`
=> chore(stdlib): Add examples to `Rational` module

compiler/esy.json, compiler/esy.lock/index.json, compiler/esy.lock/opam/chrome-trace.3.11.1/opam, compiler/esy.lock/opam/dune-build-info.3.11.1/opam, compiler/esy.lock/opam/dune-configurator.3.11.1/opam, compiler/esy.lock/opam/dune-rpc.3.11.1/opam, compiler/esy.lock/opam/dune.3.11.1/opam, compiler/esy.lock/opam/dyn.3.11.1/opam, compiler/esy.lock/opam/ordering.3.11.1/opam, compiler/esy.lock/opam/stdune.3.11.1/opam, compiler/esy.lock/opam/xdg.3.11.1/opam, compiler/esy.lock/opam/yojson.2.1.1/opam, compiler/test/suites/basic_functionality.re
Checking 114 before we merge https://github.com/grain-lang/binaryen.ml/pull/198
=> chore(compiler): Update to binaryen 114

compiler/test/stdlib/char.test.gr, compiler/test/stdlib/string.test.gr, stdlib/char.gr, stdlib/char.md, stdlib/string.gr, stdlib/string.md
Add ASCII utilities to `String` and `Char` modules
=> feat(stdlib): Add ASCII utilities to String, Char

compiler/src/parsing/ast_helper.re, compiler/src/parsing/ast_helper.rei, compiler/src/parsing/lexer.re, compiler/src/parsing/parser.mly, compiler/src/typed/checkertypes.re, compiler/src/typed/checkertypes.rei, compiler/src/utils/dune, compiler/src/utils/literals.re, compiler/test/suites/basic_functionality.re, compiler/test/suites/strings.re
Drafting for questions to @ospencer
=> WIP string and bytes refactor

compiler/src/formatting/fmt.re, compiler/src/middle_end/linearize.re, compiler/src/parsing/ast_helper.re, compiler/src/parsing/ast_helper.rei, compiler/src/parsing/ast_mapper.re, compiler/src/parsing/parser.mly, compiler/src/parsing/parsetree.re, compiler/src/parsing/parsetree_iter.re, compiler/src/parsing/well_formedness.re, compiler/src/typed/typecore.re, compiler/src/typed/typedtree.re, compiler/src/typed/typedtree.rei, compiler/src/typed/typedtreeIter.re, compiler/src/typed/typedtreeMap.re, compiler/test/grainfmt/arrays.expected.gr, compiler/test/grainfmt/arrays.input.gr, compiler/test/suites/arrays.re
=> fix(compiler): Fix array infix assign semantics

compiler/graindoc/docblock.re
Reduces time to run `grain doc stdlib -o stdlib --current-version=$(grain -v)` by 42%.
With #2101, reduces time by by 75%. If modules are already built, reduces time by 85%.
=> feat(graindoc): Cache module comments

stdlib/int16.gr, stdlib/int16.md
This pr adds examples to the `Int16` docs.
=> chore(stdlib): Add examples to the `Int16` docs

compiler/test/stdlib/float64.test.gr, stdlib/float64.gr, stdlib/float64.md
This pr adds `Float64.abs`, `Float64.neg`, `Float64.isInfinite` and `Float64.isNaN` to the `Float64` module. This is work towards bringing the various number modules closer inline to the main `Number` module's api.
=> feat(stdlib): Add `abs`, `neg`, `isNaN`, `isInfinite` to `Float64`

compiler/test/stdlib/float32.test.gr, stdlib/float32.gr, stdlib/float32.md
This pr adds `Float32.abs`, `Float32.neg`, `Float64.isInfinite` and `Float32.isNaN` to the `Float32` module. This is work towards bringing the various number modules closer inline to the main `Number` module's api.
=> feat(stdlib): Add `abs`, `neg`, `isNaN`, `isInfinite` to `Float32`

compiler/src/language_server/driver.re, compiler/src/language_server/goto.re, compiler/src/language_server/goto.rei, compiler/src/language_server/hover.re, compiler/src/language_server/initialize.re, compiler/src/language_server/message.re, compiler/src/language_server/message.rei, compiler/src/language_server/protocol.re, compiler/src/language_server/protocol.rei, compiler/src/language_server/sourcetree.re, compiler/src/typed/env.re, compiler/src/typed/env.rei
=> feat(lsp): Goto type definition

compiler/src/language_server/code_action.re, compiler/src/language_server/sourcetree.re, compiler/src/middle_end/linearize.re, compiler/src/typed/typecore.re, compiler/src/typed/typed_well_formedness.re, compiler/src/typed/typedtree.re, compiler/src/typed/typedtree.rei, compiler/src/typed/typedtreeIter.re, compiler/src/typed/typedtreeMap.re
=> feat(lsp): Use argument label code action

stdlib/uint8.gr, stdlib/uint8.md
This pr adds examples to the `Uint8` library.
=> chore(stdlib): Add examples to `Uint8` docs

stdlib/uint16.gr, stdlib/uint16.md
This pr adds examples to the `Uint16` documentation.
=> chore(stdlib): Add examples to `Uint16` docs 

compiler/src/language_server/code_action.re, compiler/src/language_server/code_file.re, compiler/src/language_server/log.re, compiler/src/language_server/utils.re, compiler/test/runner.re, compiler/test/suites/dune, compiler/test/suites/grainlsp.re, compiler/test/test-libs/compileError.gr
* Add LSP test harness, test most major LSP functionality
* Make some improvements to LSP behavior according to expected behavior in tests
=> fix(lsp): Add test harness, update named arg code action title, fix code action trigger points, do not print LSP warnings

docs/contributor/commits_pull_requests_and_merging.md, docs/contributor/compiler_walkthrough.md, docs/contributor/memory_management.md, docs/contributor/string.md
=> chore(docs): Fix typos

stdlib/LICENSE
Updated the copyright year from 2024 to 2025 in the LICENSE file
=> chore(stdlib): Update LICENSE copyright year

compiler/src/typed/env.re, compiler/test/suites/provides.re
=> fix(compiler): Resolve Not_found for use statements with module aliases

README.md
Just a quick pr to update the license year from 2024 to 2025.
=> chore: Update license year
