- README.md
Hi all. I have updated the README with the proper versions needed to build the grain compiler as discussed as an action item in #31. I tried to mirror the other build steps closely.
I changed ocaml version to `4.05`. This seems to be the only version that `grainc` can be built with. I have `grainc` building under Ubuntu in docker, as you can see here #37, making it really simple to swap between ocaml versions. Unfortunately, `4.05` seemed to be the only one to work for me. 
Opam version is less relevant, just needs to be v2. 
I also removed the note about `jbuilder`. It seems insignificant if the user runs `opam install . --deps-only`. There seemed to be no need to worry about installing `jbuilder`/`dune` beforehand, as its listed as an opam dependency.
Hope this helps. Looking forward to …
> Update README with versions used for building grainc

- runtime/src/core/malloc.js
- runtime/src/core/memory.js
This clears out the `Invalid asm.js: Imported function args must be type extern` message that appears in new versions of Node.
> Fix malloc asm.js for newer versions of Node

- src/typed/ctype.ml
This should fix the issue some of us were seeing when importing data constructors.
> Don't worry about expanding abbreviations for type constructors

- runtime/src/core/primitives.js
- runtime/src/core/tags.js
- runtime/src/lib/print.js
- runtime/src/utils/utils.js
- src/codegen/compcore.ml
- src/codegen/mashtree.ml
- src/codegen/value_tags.ml
- src/grain-stdlib/lists.gr
- src/grain-stdlib/pervasives.gr
- src/middle_end/anftree.ml
- src/middle_end/anftree.mli
- src/parsing/ast_helper.ml
- src/parsing/ast_helper.mli
- src/parsing/ast_iterator.ml
- src/parsing/ast_mapper.ml
- src/parsing/lexer.mll
- src/parsing/parser.dyp
- src/parsing/parsetree.ml
- src/typed/typecore.ml
- src/typed/typedtree.ml
- src/typed/typedtree.mli
- src/typed/typemod.ml
- test/input/counter.gr
- test/input/forward-decl.gr
- test/test_end_to_end.ml
Semicolons are no longer required. If a statement is followed by a semicolon, its type is ignored in a manner similar to OCaml's `ignore` function.
Type annotations (constraints) may now be placed on any expression:
```grain
let add5 = (x) => {
(x : Number) + 5
}
```
Curly braces may now be omitted for lambdas that only return one expression:
```grain
let add = (a, b) => a + b
```
Parens around the argument of a single-argument lambda may now be omitted:
```grain
let identity = x => x
```
Curly braces are no longer required around the `then` or `else` branches of an `if`:
```grain
if (bool) this else that
```
`if`/`else if` blocks are now supported.
Boolean `and`, `or`, and `not` have been renamed to `&&`, `||`, and `!`, respectively.
`print` now has type `a -> Void`.
> Quality-of-life syntax adjustments

- src/codegen/transl_anf.ml
- src/middle_end/linearize.ml
- src/parsing/ast_helper.ml
- src/parsing/ast_helper.mli
- src/parsing/ast_iterator.ml
- src/parsing/ast_mapper.ml
- src/parsing/asttypes.ml
- src/parsing/parser.dyp
- src/parsing/parsetree.ml
- src/parsing/well_formedness.ml
- src/typed/parmatch.ml
- src/typed/printpat.ml
- src/typed/typedtree.ml
- src/typed/typedtree.mli
- src/typed/typedtreeIter.ml
- src/typed/typedtreeMap.ml
- src/typed/typemod.ml
- test/input/toplevelStatements.gr
- test/test_end_to_end.ml
This PR allows any expression to appear at the top level, so multiple expression statements don't have to all appear in a block at the bottom of the file.
Here's an example (valid) program:
```grain
let one = 1
let two = 2
print(one)
print(two)
let three = 3
print(three)
let four = 4
let five = two + three
print(four)
print(five)
```
> Allow arbitrary toplevel expressions

- src/grain-stdlib/lists.gr
- src/middle_end/matchcomp.ml
- test/input/mixedPatternMatching.gr
- test/test_end_to_end.ml
There was a bug in our pattern-matching implementation that caused nested patterns to be treated as catch-alls. For example,
```grain
match (...) {
| Cons(a, Cons(b, Empty)) => ...
...
}
```
was treated as though it were
```grain
match (...) {
| Cons(a, b) => ...
...
}
```
This PR resolves this, and adds extensive tests around pattern matching.
> Support deeply-nested pattern matching

- grain_parsing.opam
Building the project against itself failed because these depends were missing in for `grain_parsing`
> Fix: Add missing yojson depends

- src/middle_end/linearize.ml
- src/parsing/lexer.mll
- src/parsing/parser.dyp
- stdlib/pervasives.gr
- test/test_end_to_end.ml
This PR adds a shorthand syntax for unboxing: `^box`. It also adds four new utilities for `Box<Number>`:
```grain
box += 6
box -= 6
box *= 6
box /= 6
```
These should make working with the most common uses for boxes much nicer.
> Implement new Box utilities

- src/parsing/well_formedness.ml
- test/test_end_to_end.ml
There's currently an issue with creating recursive data types using `let rec`, and there isn't _currently_ an easy fix. For the time being, we'll disallow non-functions on the right side of `let rec`.
> Ban nonfunctions from letrec

- CONTRIBUTING.md
- README.md
- compiler/esy.json
- package.json
- stdlib/package.json
When I was updating the contributor docs and was trying to outline gotchas, I felt that was kinda dumb instead of just fixing them, so I did.
Two new things happen now:
1. Post `yarn compiler:install` we now clean the stdlib, so the stdlib will get recompiled will with the new installed compiler.
2. The tests now run with `dune runtest --force`, which always runs the test binary, not just if the dependencies changed.
> Update README and contributor docs; fix gotchas

- CONTRIBUTING.md
- docs/README.md
- docs/contributor/README.md
- docs/contributor/compiler_walkthrough.md
- docs/contributor/data_representations.md
This sets up the `docs/contributor` folder, and adds a general compiler walkthrough and information on how data is represented in memory in Grain.
> Add contributor docs

- compiler/src/middle_end/linearize.ml
- compiler/src/typed/datarepr.ml
- compiler/test/input/adtprint.gr
- compiler/test/test_end_to_end.ml
We were double-tagging constructor tags and specially tagging non-constant constructors, and our match/allocation implementations don't depend on that. We also didn't use separate numbers for constant/tuple constructors which caused printing to be dependent on the order in which the type variants were defined, i.e.
```grain
export data Option<a> = None | Some(a)
print(Some(9))
print(None)
```
correctly prints
```
Some(9)
None
```
but
```
export data Option<a> = Some(a) | None
print(Some(9))
print(None)
```
casually prints
```
None
Some(0)
```
Nothing is wrong with the data in memory (so pattern matching and whatnot still works properly) but the printing is busted. Also, if you define more than one tuple constructor or more than one constant constructor, that doesn't work at all 😬
But now …
> Fix ADT printing

- runtime/src/core/heap.js
- runtime/src/runtime.js
- runtime/src/utils/utils.js
`toString`, `stringSlice`, and `stringAppend` haven't been working since we had real malloc. This actually calls malloc for those methods.
> Heap allocate should call malloc

- stdlib/package.json
Happens when the stdlib has already been cleaned.
> Fix postinstall error

- compiler/src/codegen/compcore.ml
- compiler/src/codegen/transl_anf.ml
- compiler/test/test-libs/sameExport.gr
- compiler/test/test_end_to_end.ml
- stdlib/sys.gr
We had a bug when exporting multiple values with the same name.
In this example:
```grain
export *
let foo = () => true
let foo = () => foo()
foo()
```
calling `foo` results in an infinite loop. Fortunately, there was no typechecking issue, just a codegen issue.
> Fix export scoping

- CONTRIBUTING.md
Old link was pointing to grain-lang.org/guide/, which seems to be now in grain-lang.org/docs
Fixes #132
> Updated link to getting grain in CONTRIBUTING.md

- .github/workflows/ci.yml
- README.md
- compiler/package.json
- package.json
This makes the development `grainc` available via `yarn workspace @grain/compiler link`, which I think is a good solution until we decide if we want to bundle the compiler with the CLI.
> Make compiler subpackage linkable

- compiler/src/middle_end/analyze_tail_calls.ml
- compiler/test/input/oneBranchTail.gr
- compiler/test/test_end_to_end.ml
Basically, if a function was tail-callable and contained a branch with a tail position recursive call and another branch with a non-tail position recursive call, the non-tail position call would still be transformed as though it were in tail position.
The bug is a bit more obvious to see by the unconditional call to `push_tail_call`.
The fix is to only mark tail calls if they're in tail position. For sequences, only the last item is marked. A binding is never in tail position, but we do mark bindings to recursive functions as in tail position to properly analyze nested definitions.
Writing a test for the optimized AST would be a little brittle, so I just added a test with the code where we found the bug.
> Fix tail-call analysis for branches

- compiler/src/codegen/compcore.ml
- compiler/test/test_end_to_end.ml
Fixes a small issue when calculating negative modulus. This PR _does_ touch compcore, but it's quite small and I don't think it'll conflict with any of the GC work.
> Fix modulo codegen

- .gitignore
- cli/bin/compile.js
- cli/bin/grain.js
- compiler/esy.json
- package.json
This adds another step to the "compiler:build" command that copies the generated binary of `grainc.exe` into the `cli/bin` directory and then the execSync calls use the absolute path to that binary.
This should avoid people having to install the grainc binary. There might be a possible issue with that absolute path on Windows, but we'll need to get something in CI to check it.
This is also phase 1 in getting a publishable CLI that people can just use.
> Copy the grainc binary to the CLI directory

- compiler/src/utils/warnings.ml
- compiler/test/stdlib/option.test.gr
- compiler/test/test_end_to_end.ml
- stdlib/option.gr
- stdlib/pervasives.gr
This adds the `Option` data type to pervasives, and additionally adds an `option.gr` module to the standard library that shamelessly reimplements APIs I've liked from OCaml, BuckleScript's Belt library, and Rust.
I also added `peek` because I think it is useful once there's currying and you can chain things with `|>` or similar.
One glaring omission from this implementation is converting to/from Result because that doesn't exist yet.
> Add Option to stdlib

- stdlib/package.json
- yarn.lock
This uses a node module to have cross-platform cleaning of the wasm files in the stdlib. It uses globs and supports negative globbing for `stdlib-external`
> Use del-cli to clean with globs

- stdlib/build.mjs
- stdlib/package.json
- yarn.lock
This adds a cross-platform build script that generates all wasm files based on assemblyscript files in `stdlib-external`.
I also fixed a globbing issue with my clean script.
> Adds a build script to run assemblyscript

- compiler/dune-project
- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/esy.lock/opam/dune-build-info.2.5.1/opam
- compiler/grainc.opam
- compiler/grainc/dune
- compiler/grainc/grainc.ml
This uses `dune-build-info` to inline the version number into the grainc binary.
More information on dune-build-info at https://dune.readthedocs.io/en/stable/dune-libs.html?highlight=build-info#build-info
While making these changes, I noticed we didn't have grainc in the esy.json, which I think was just an oversight. Also, the grain compiler version number didn't match the rest of the project 😉
> Utilize dune-build-info for grainc version

- .github/workflows/ci.yml
- CONTRIBUTING.md
- README.md
- cli/package.json
- compiler/package.json
- package.json
This changes the scripts from all being defined as `package:command` to being proxied through `yarn workspace` into the package that defines the build script. It also moves the `esy` commands into the package.json of the compiler so we can utilize them from the CI.
A really neat trick is that you can use `yarn run` to navigate into packages and select a command because they all spawn `yarn run` commands. Here's an example of me navigating from the root into the compiler package where I can select a new command:
> Proxy the root scripts to packages

- .gitignore
- .vscode/setup-ocaml-lsp.js
- README.md
- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/esy.lock/opam/ppx_yojson_conv_lib.v0.14.0/opam
- package.json
We have all sorts of issues with the reason-vscode extension and development on the OCaml Platform extension seems to be moving quickly, so I added some quick-and-dirty scripts to get contributors set up with using it.
> Add OCaml LSP w/ setup script

- compiler/test/stdlib/map.test.gr
- compiler/test/test_end_to_end.re
- stdlib/map.gr
- stdlib/option.gr
This is a base implementation of Map (aka HashMap) for the stdlib. It was heavily influenced by [BuckleScript's Belt.HashMap](https://github.com/BuckleScript/bucklescript/blob/3b317c4784e5e4b4bbe47893241aed8a873a9a76/jscomp/others/belt_HashMap.ml).
There's still a ton of work to do but I wanted an initial review because I've never implemented something like this before. 🙏
> Implement a Map module for stdlib

- compiler/test/stdlib/map.test.gr
- stdlib/map.gr
I went to implement `Map.isEmpty` and I found a bug with the size starting out at the initial buckets size, but it is supposed to represent how many elements are in the Map.
> stdlib: Add Map.isEmpty & fix size bug

- compiler/test/stdlib/map.test.gr
- stdlib/map.gr
This adds a bunch of methods to the Map stdlib, and also improves the original implementation by resizing it once the amount of nodes exceeds double the size of the buckets.
There are still improvements to be made but I will open issues for some right now!
> stdlib: Add more methods to Map

- stdlib/package.json
Re: conversation in Discord. I missed this in the `del` README when I added it here.
fyi @JohnnyRidout
> script: del is already a Windows command

- compiler/src/parsing/parser.dyp
- compiler/test/test_end_to_end.re
Ref #182
I only implemented the Record syntax because it is a pain-point for me, but this should also give guidance on how someone could add it to the other balanced-syntax data structures mentioned there.
> lang: Support trailing commas in records

- compiler/test/stdlib/arrays.test.gr
- compiler/test/stdlib/hash.test.gr
- compiler/test/stdlib/lists.test.gr
- stdlib/arrays.gr
- stdlib/lists.gr
- stdlib/map.gr
- stdlib/option.gr
- stdlib/sys/file.gr
These are some breaking changes to the stdlib that:
* Renames some methods to make things more clear (`foldLeft` -> `reduce`, `hd` -> `head`, etc)
* Updates some methods that didn't adhere to the collection-last style
* Prefers longer variable names to make the stdlib easier for non-FP people to contribute
After this is approved, I will get all the docs changed on the website before merging.
> Stdlib consistency

- stdlib/map.gr
While trying to recreate a `decRef` issue on master, I found some ways to streamline the Map implementations.
> stdlib: Streamline some Map method implementations

- cli/bin/compile.js
- cli/bin/grain.js
- cli/package.json
- compiler/test/runner.re
- yarn.lock
Adds some subcommands to make things easier to do with just the `grain` CLI
By moving people to use one CLI, any underlying changes we make to structure shouldn't affect the majority of users, like when I started copying `grainc.exe` into the CLI directory.
> cli: Add compile & run subcommands (closes #223)

- compiler/src/typed/types.re
I was doing some general cleanup (and getting to know the compiler internals better) and I ran across an old issue by @belph to ppx_sexp_conv linked from a workaround in the code. 
I believe ppx_sexp_conv both fixed the opaque bug, and refactored a bunch of the code since that issue was filed. I didn't see any place where opaque was used or needed, so I added yojson to the deriving and was able to remove the workaround code.
@belph Maybe you can let me know if `[@sexp.opaque]` needs to be added anywhere.
> cleanup: Remove workaround for old ppx_sexp_conv bug

- compiler/src/middle_end/anftree.re
- compiler/src/parsing/asttypes.re
- compiler/src/parsing/parsetree.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/src/typed/types.re
This is just some cleanup I had lying around related to some config work I'm hoping to tackle.
I also noticed that `refmt` handled the OCaml comments really weird, so I did some spelunking and re-aligned them correctly. I plan to do this whenever something seems off during refactoring.
> cleanup: Refactor sexp_locs_enabled access & adjust comments

- compiler/src/compile.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
While poking around for JSOO stuff, I noticed that `output_enabled` was a config option but @ospencer said that it isn't actually used.
I think it would be an awesome feature to have in the future, but it is confusing to exist right now because disabling it breaks a bunch of assumptions the compiler makes.
When merged, I'll open a feature request to make the compiler work without filesystem access.
> cleanup: Remove output_enabled config since not used

- compiler/src/parsing/parser.dyp
- compiler/test/test_end_to_end.re
This adds support for parsing list literals with a trailing comma, given they aren't empty and don't end with a spread.
I also added tests for the list syntax because they didn't seem to exist. I also discovered that lists are heterogeneous?!!?
There is an additional commit here that cleans up trailing whitespace in the parser file because I'm sick of dodging it in my PRs 🤣 
Ref #182
> lang: Support trailing comma in list literals

- compiler/src/typed/typecore.re
- compiler/test/test_end_to_end.re
> Allow wildcard pattern for lambda function argument

- .gitignore
- compiler/src/codegen/compcore.re
- compiler/src/codegen/emitmod.re
- compiler/src/typed/translprim.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
Source map support is here! 🎉 
Wasm source maps are currently supported in Chrome and Firefox. I'm going to look for some options for Node until there's support, like using `node --inspect`, but that's not important for this initial pass.
Here's what it looks like:
(The example program does `assert 1 == 2` on line 5 in `hello.gr`, and `assert` is defined in `pervasives.gr` on line 30.)
We can do some things to make it nicer, like using the original source names in the wasm output—but this is a great start.
Made #273 to track the above ☝️
> Source Map Support

- compiler/src/typed/printpat.re
Funny enough, I tried to show examples of this working, but there's another bug that I fixed in #286 that's preventing me from doing so in all cases, but once that's merged everything should be all set. Based on the code though, I'm sure you can probably see how this fixes the issue we were having. 😛 
Closes #291.
> Fix printing of constructors for exhaustiveness checking

- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/middle_end/linearize.re
- compiler/src/middle_end/matchcomp.re
- compiler/src/parsing/ast_helper.re
- compiler/src/parsing/ast_helper.rei
- compiler/src/parsing/ast_mapper.re
- compiler/src/parsing/lexer.mll
- compiler/src/parsing/parser.dyp
- compiler/src/parsing/parsetree.re
- compiler/src/typed/parmatch.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/test/test_end_to_end.re
Closes #283.
This PR adds the ability to "guard" a match pattern with a condition, like so:
```grain
data Example = Foo(Number) | Bar
match (Foo(6)) {
| Foo(n) when n == 2 => print('it was two')
| Foo(n) when n == 6 => print('it was six')
| Foo(_) => print('it was not two or six')
| Bar => print('it was bar')
}
```
> Support pattern matching with guards

- docs/contributor/operator_precedence.md
Closes #287. I'm going to open a few issues as well.
@phated added `isnt`.
> Add operator precedence document

- compiler/src/codegen/compcore.re
- compiler/src/codegen/mashtree.re
- compiler/src/codegen/transl_anf.re
- compiler/src/parsing/asttypes.re
- compiler/src/parsing/parser.dyp
- compiler/src/parsing/well_formedness.re
- compiler/src/typed/checkertypes.re
- compiler/src/typed/parmatch.re
- compiler/src/typed/printpat.re
- compiler/src/utils/literals.re
- compiler/test/test_end_to_end.re
- stdlib/stdlib-external/numbers.ts
This PR bakes in support for rational literals instead of only creating them via division. This will make it possible to do pattern matching on rational constants (as well as be slightly more performant than having to perform the division/factoring at runtime).
Requires #326.
> Literal rational literals

- Dockerfile
The way we are currently building the dockerfile fails if you don't have a previous cache because the checksum/SHA changes between building the dependencies and building the project. Calling `esy install` one time before we compile the project regenerates the checksum so we don't get the "needs an esy install" error.
Note: this won't be an issue anymore when we can use the `esy` command directly, which is the recommended way to use the project these days.
> Add an extra install call to update checksum

- compiler/src/typed/typemod.re
- compiler/src/utils/files.re
Fixes #329.
With program
```grain
import * from './test2'
Foo(5) + 5
```
You now get error
```
Error: This expression has type Test2.Foo
but an expression was expected of type Number
```
> Fix generated module names

- Dockerfile
This makes it so if you `docker run` without any command, you're in a shell where `grain` works rather than the node repl. It also sets the default directory to the Grain repo rather than just `/`.
> Update docker working directory and default command

- compiler/src/codegen/compcore.re
- compiler/src/codegen/mashtree.re
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/middle_end/matchcomp.re
- compiler/src/parsing/parser.dyp
- compiler/src/parsing/parsetree.re
- compiler/src/typed/parmatch.re
- compiler/src/typed/translprim.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/test/test_end_to_end.re
- stdlib/pervasives.gr
This PR adds the ability to do pattern matching on constant patterns:
```grain
match (('foo', 5, true)) {
| ('bar', _, false) => false
| ('foo', 5, _) => true
| _ => false
}
```
Ended up going with the desugaring into guards (after typechecking) approach since I believe it is more performant than checking constants on the fly (though this seems to only be true for matches with many cases with constant patterns—I believe it's faster to check them on the fly if there are few cases with constant patterns).
Tests are light since they're just exercising already-tested guarded branches.
Closes #284.
> Implement pattern matching on constants

- compiler/test/stdlib/list.test.gr
- stdlib/list.gr
Note I'm not familiar with how to catch exceptions, so I don't know how to test the failure cases.
> Add `List.find`, `List.findIndex`

- stdlib/stdlib-external/numbers.ts
For some reason, I thought `boxedNumberTag` checked for simple numbers.
> Fix small number coercion bug

- compiler/src/parsing/parser.dyp
- compiler/test/stdlib/array.test.gr
- compiler/test/test_end_to_end.re
Partially addresses https://github.com/grain-lang/grain/issues/182
> add support for trailing commas in arrays

- compiler/src/parsing/parser.dyp
- compiler/test/test_end_to_end.re
> add support for trailing commas in tuples

- runtime/package.json
- runtime/src/core/grain-module.js
- stdlib/build.mjs
- yarn.lock
This makes it so if you run Grain via `node --inspect`, you can see a properly source-mapped call stack in the Chrome Node Debugger:
You can even set breakpoints and they work:
This doesn't fix the issue with the mappings not showing in the actual stack trace, though, since those are generated by Node and not the Chrome debugger. 😞 
The mappings still work properly if you're running directly in Chrome, though.
> Slightly better node source map support

- compiler/src/typed/oprint.re
Fixes #380.
```
Error: This expression has type Foo<a> 
but an expression was expected of type Number
```
> Fix printing of types

- stdlib/map.gr
This makes the Map type referenceable as `Map.Map<k, v>` (tbd on if it should be `Map.T`) instead of `Map.Container<Map.Bucket<k, v>>`.
Side note: I would love syntax for optional types, like `Array<Bucket<k, v>?>` or `Array<?Bucket<k, v>>` (and also shorthands for list and maybe array types)!
> Update Map type

- compiler/src/typed/translsig.re
- compiler/test/test_end_to_end.re
- stdlib/result.gr
Fixes #315.
In addition to linking type variables for imported values, we now also do it for imported types (which includes variants and records).
Fixing this made some of the Result tests fail, and after reviewing the code it made perfect sense. I updated the implementations to have the behavior the tests expected. 😄
> Fix imported ADT typechecking

- cli/bin/grain.js
- cli/bin/lsp.js
- compiler/grainc/grainc.re
- compiler/src/parsing/location.re
- compiler/src/parsing/location.rei
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
(works with https://github.com/ng-marcus/lsp-grain which isn't a published extension yet so you need to run it in debug mode)
I've modified the cli and compiler to support an lsp mode where the cli passes through stdin as the content to compile,  and reports back the errors (it any) on stdout in a form of
startline startchat endline endchar
Error message 
over multiple lines
The assumption is the compiler stops after the first error so there's only one to report.
I'm not really sure what's happening in location.re (report exception) so I just copied it and sprintfed the result, I assume it's to do with nested exceptions.   It works for now, but I'm not confident in the code.
Your feedback on approach (modifying the compiler in this way, method of reporting back) would be appreciated.
> Added an LSP mode for use with vscode lsp implementation.

- compiler/src/parsing/parser.dyp
- compiler/test/test_end_to_end.re
> add support for trailing commas in ADT constructors and function arg lists

- compiler/src/parsing/location.re
Stop re-raising lex/parse/compile errors in LSP mode to stop them causing the LSP server to report them on trace output
> Don't re-raise exceptions when printing compiler errors in LSP mode

- compiler/src/typed/oprint.re
Functions now always print with parens around the arguments and tuples print as... tuples.
`(Number, Number) -> Number`
`(Bool, Number)`
> Fix type printing for functions and tuples

- compiler/src/codegen/compcore.re
In Binaryen.ml v0.3.0, we added the `Memory.unlimited` constant which is the value `-1` which seems to be the way Binaryen expects you to specify unlimited memory (hooray C code).
This switches our OCaml `max_int` to that constant.
> Use proper unlimited memory instead of max_int

- cli/package.json
- compiler/dune-project
- compiler/esy.json
- compiler/package.json
- package.json
- runtime/package.json
- stdlib/package.json
I believe we are at a point where we should bump the language's version again. We've introduced a lot of features (`let mut`, number system) and breaking changes (`enum`, `record`, comment syntax).
Bumping the version will indicate to anyone coming back from a break that things have changed and their code might not compile.
@ospencer can you merge this and tag a release? I think we might want to editorialize some release notes with the highlights too.
> Bump Grain version to 0.2.0

- runtime/src/core/grain-module.js
- runtime/src/core/runner.js
This allows Grain's browser runtime to be executed with an `ArrayBuffer`
of compiled Web Assembly code, which is extremely useful for bundling Grain apps (e.g. Webpack) rather than depending
on the WASM being hosted somewhere for `readURL`.
> Add support for loading Grain modules directly from an ArrayBuffer

- compiler/src/codegen/compcore.re
- compiler/src/codegen/transl_anf.re
- compiler/src/middle_end/anf_helper.re
- compiler/src/middle_end/anf_helper.rei
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/middle_end/linearize.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/src/typed/typemod.re
We were exporting everything that was global in a module rather than just things that are explicitly exported. This wasn't a huge deal, since the compiler won't let you import them, but this is the first step to some wasm cleanup.
> Remove unnecessary wasm exports

- .github/workflows/ci.yml
- Dockerfile
- README.md
- compiler/package.json
- package.json
Yarn supports the [`prepare` script](https://classic.yarnpkg.com/en/docs/package-json#toc-scripts), which is a lifecycle script that is run after `yarn` or `yarn install` is run.
By renaming our `setup` to `prepare`, it will reduce the initial setup to 2 commands, instead of 3.
> Switch the setup command to prepare

- compiler/grainc/grainc.re
While working on the base structure for `graindoc`, I noticed some cmdliner config in grainc that isn't used. This removes it.
> Remove some unused cmdliner stuff in grainc

- Dockerfile
When switching our setup command to `yarn prepare`, I broke the docker container creation. This was due to the caching strategy we were trying to employ, which didn't allow for the stdlib or runtime scripts to be executed immediately after `yarn install` (which is when `yarn prepare` is guaranteed to run).
Since this container is mostly consumed from container registries, I've just reduced the dockerfile to have no caching. We should consider a better strategy for our lifecycle scripts going forward, but I think that will require some changes to the compiler itself.
> fix: ensure Dockerfile works with `yarn prepare` command

- README.md
We've fielded some of these questions in discord, but we should have a proper note in the readme.
> docs: add message about not building on Windows

- compiler/test/stdlib/map.test.gr
- stdlib/map.gr
Closes #192 
This implements the `Map.update` method that sets, updates, or removes the value at a given key in a Map data structure. The updater function receives an `Option` of the existing (or not) value and must return an `Option` indicating whether to set or remove the value.
> feat: add update method to map stdlib

- compiler/src/parsing/lexer.mll
- compiler/src/parsing/parser.dyp
- compiler/test/test_end_to_end.re
- stdlib/pervasives.gr
We've had a few scenarios where the `^` being used for unboxing has caused problems, specifically around ambiguity (see #183 & #425) in the parsetree.
In this PR, I remove the `^` operator as the unbox operator but left the token in the lexer/parser for use as a bitwise operator in #425. I also removed the operator from Pervasives and cleaned up the tests.
> fix!: remove ^ as unbox operator (fixes #183)

- stdlib/build.mjs
- stdlib/package.json
Windows doesn't know what to do with an executable `.mjs` file, so I just switched the build script to be exec'd with node directly.
> fix: use direct node call instead of executable file

- runtime/src/utils/locators.js
This allows us to create filesystem specific paths in our default filesystem locator, which fixes module lookups on Windows.
> fix: utilize path.join to create filesystem paths in default locator

- compiler/src/utils/dune
- compiler/src/utils/files.re
Until https://github.com/facebookexperimental/reason-native/pull/251 lands, we need to convert any `\` in a Windows path to `/` to use with reason-native's Fp library.
> fix: normalize filesystem paths to always be / character

- cli/bin/grain.js
- cli/package.json
- yarn.lock
The hashbang as it is currently written doesn't work on Windows, because npm creates wrappers that are informed by the hashhang. When it sees `/usr/bin/env node`, it just replaces the call with something like `%PATH%\node.exe` but if you try to specify `/bin/sh` it tries to do `%PATH%\sh.exe` which crashes.
@ospencer I know you put this in place, so do you believe this simplification will work?
> fix: replace shebang trick with flagged-respawn to support Windows

- compiler/src/utils/dune
Inline tests are currently broken on Windows until https://github.com/janestreet/ppx_inline_test/issues/23 is fixed (hopefully in 0.15 🤞)
I couldn't come up with a good way to enable them on other platforms, so let's just turn them off temporarily.
> fix: temporarily disable inline tests for Windows

- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/grainc/config/dune
- compiler/grainc/config/flags.re
- compiler/grainc/dune
This adds dune-configurator to provide linker flags to grainc on Windows that will allow it to statically include the MinGW libraries (libstdc++ and winthreads) into the binary so it doesn't need esy's MinGW location in the users' PATH.
I had to use configurator because it seems that on Mac, those flags cause Clang to fail for some reason.
Additionally, with this PR, the Grain compiler should build and run on Windows. The tests still fail, which needs to be looked into before we can add it to CI though.
If you want to try it out in Powershell, you need to add the results of running `yarn global bin` to the path using the `$env:PATH` variable (otherwise it's pretty similar to linux)
> feat: statically include MinGW libraries on Windows

- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/esy.lock/opam/ocaml-migrate-parsetree.2.1.0/opam
- compiler/esy.lock/opam/ppx_deriving.5.2/opam
- compiler/esy.lock/opam/ppx_expect.v0.14.1/opam
- compiler/esy.lock/opam/ppx_optcomp.v0.14.1/opam
- compiler/esy.lock/opam/ppx_sexp_conv.v0.14.2/opam
- compiler/esy.lock/opam/ppxlib.0.20.0/opam
- compiler/esy.lock/opam/reason.3.6.2/opam
Reason v3.6.2 was finally published to opam, so we no longer need a resolution! This was the release that had ocaml 4.11.0 support.
> chore: update Reason to use published 3.6.2

- .vscode/setup-ocaml-lsp.js
This updates our "setup vscode" script to assign the `.dyp` extension to ocamllex syntax highlighting within our workspace. I got sick of manually setting this each time I needed to work on the file, lol.
> chore: add ocamllex highlight to our dyp file in our workspace

- cli/bin/grain.js
- runtime/src/runtime.js
This allows setting the initial amount of memory page via a command line option. It actually required a handful of workarounds due to the static initialization (and dependents upon it), which we should consider when taking a deeper look at the runtime in the future.
Using this CLI option, I am able to compile my Advent of Code solutions.
> feat: allow setting the initial memory via CLI option

- stdlib/package.json
During debugging, I noticed some other files hanging around that weren't being cleaned, so I adjusted the script to clean those up.
> chore: cleanup more generated files in stdlib

- compiler/test/stdlib/array.test.gr
- stdlib/array.gr
In #159, it seemed that most people were on-board with fallible stdlib methods to return Option.  During AoC, I actually found a use case for Array.find to return an Option (when I wrote my naive parseInt function), so I thought I'd get that started with this PR.
Just wanted to get the 👍 before I go through and convert the rest.
> feat!: change return type of Array.find/findIndex to Option

- compiler/test/dune
I was poking around oUnit2 and I found it does parallel tests by default, so I added the `-help` flag to our test binary and it output this:
```
-shards i                       Number of shards to use as worker (threads or processes). (default: 2)
```
I believe this means that oUnit is running our tests in parallel in 2 processes and that **might** be causing an issue where 1 process is trying to create a stdlib wasm file, like `pervasives.gr.wasm`, at the same time another process is trying to open that file, which would result in the input channel being closed immediately and `End_of_file` being surfaced which fails the test with `Cmi_format.Error`. It also _kind of_ explains why only 1 tests fails with that error because no other test going forward would be recreating that file, so …
> fix: set test sharding to 1 in attempt to avoid test race condition

- compiler/src/typed/cmi_format.re
I combined the `try` wrapping a `switch` and the additional `raise` into a single `switch` statement that matches on Option or exceptions.
Also, changed an OCaml reference.
> refactor: little cleanup around try/switch

- stdlib/stdlib-external/sys/env.ts
- stdlib/stdlib-external/sys/random.ts
Per the research I did for #472, we can't use `memory.data` in AS. This updates our code to not use it anymore.
Could maybe optimize the env one to not need to call malloc an extra time, but this is much cleaner.
> Remove use of memory.data

- compiler/test/stdlib/set.test.gr
- compiler/test/test_end_to_end.re
- stdlib/set.gr
Add initial implementation of Set module using ~~List as the~~ the same underlying data structure as Map.
It reuses many modified helper functions from the Map module.
Maybe we could unify those functions?
@ospencer, what is the convention for `init` and `make` family of functions?
> feat: add Set stdlib module

- compiler/src/parsing/lexer.mll
I realized that because 
```
'
'
```
is a valid character (newline), we also need to account for it.
> fix: Multiline char locs

- compiler/test/stdlib/stack.test.gr
- compiler/test/test_end_to_end.re
- stdlib/stack.gr
I realized we don't have a Stack module in the standard library.
Even though it's just a wrapper around List, it mirrors the Queue module.
> feat(stdlib): add Stack module

- compiler/test/test_end_to_end.re
- stdlib/stdlib-external/runtime/string.ts
This makes it so `print("Hello, world!")` creates the program output `Hello, world!` instead of `"Hello, world!"`. As an added bonus, now `str == toString(str)` now holds (as it did not before).
Compound structures, i.e. `("Hello", 5)` still print with quotes.
> chore(runtime)!: Print strings without quotes

- compiler/test/stdlib/map.test.gr
Just a regression test now that the decRef bug is fixed.
Closes #350
> chore: add regression test for #350

- compiler/test/stdlib/map.test.gr
- compiler/test/stdlib/set.test.gr
- stdlib/set.gr
This adds regression tests for Map & Set related to #497 - I needed to add a `getInternalStats` to Set and I copied the Map tests.
Closes #497
> Regression tests for 497

- compiler/grainc/grainc.re
- compiler/src/diagnostics/lenses.re
- compiler/src/diagnostics/output.re
Updated LSP mode to return the full set of statements, patterns and expressions in a JSON format to the LSP server.
This is much better than the previous version as I use the built-in typedtreeiterator to get what I need (so all the hard work was done for me thanks!)
Values are returned in a new field in the results (values) and the old field (lenses) is returned as empty so older LSP clients just report empty values and don't potentially crash.
One question - I build my own type description for the record type and just return "Variant" for the hover for variants.  What would you like to see here?  Having the hover show the whole record or variant is a little strange as that's just a repeat of the code, but it's what Reason does.  Let me know and I'll update the PR
> Better lenses and hover for LSP

- compiler/src/codegen/compcore.re
- compiler/src/codegen/mashtree.re
- compiler/src/codegen/transl_anf.re
Closes #131.
Before exportable mutable globals were a thing, the only way to simulate the behavior was to have a "getter" function that could return the value from your module. This reduces overall code size and is more efficient for module startup.
> chore: Use mutable globals instead of wrapper functions for function exports

- compiler/src/codegen/compcore.re
- compiler/src/codegen/mashtree.re
- compiler/src/codegen/transl_anf.re
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/middle_end/linearize.re
- compiler/test/input/unsafeWasmGlobals.gr
- compiler/test/runner.re
- compiler/test/test-libs/unsafeWasmGlobalsExports.gr
- compiler/test/test_end_to_end.re
This PR adds the global use functionality described in #517.
> feat: Allow unsafe wasm values in globals

- compiler/src/middle_end/linearize.re
- compiler/src/middle_end/optimize.re
- compiler/src/middle_end/optimize_dead_statements.re
- compiler/src/middle_end/optimize_dead_statements.rei
- compiler/src/parsing/ast_helper.re
- compiler/src/parsing/ast_helper.rei
- compiler/src/parsing/ast_iterator.re
- compiler/src/parsing/ast_mapper.re
- compiler/src/parsing/parser.dyp
- compiler/src/parsing/parser_header.re
- compiler/src/parsing/parsetree.re
- compiler/src/parsing/well_formedness.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/src/typed/typedtreeIter.re
- compiler/src/typed/typedtreeMap.re
- compiler/test/test_end_to_end.re
This PR refactors `let` bindings in the AST to not have bodies, i.e. work the same way that toplevel bindings do. This makes things a little cleaner (as can be seen by the chunk of code deleted from `parser_header`). As an added bonus, compilation errors are now reported in top-down order, which can be seen in the test changes.
> chore: Refactor bindings in the AST

- compiler/src/codegen/compcore.re
- compiler/src/codegen/mashtree.re
- compiler/src/codegen/transl_anf.re
- compiler/src/middle_end/analyze_closure_scoped_vars.re
- compiler/src/middle_end/analyze_closure_scoped_vars.rei
- compiler/src/middle_end/analyze_purity.re
- compiler/src/middle_end/analyze_tail_calls.re
- compiler/src/middle_end/anf_helper.re
- compiler/src/middle_end/anf_helper.rei
- compiler/src/middle_end/anf_iterator.re
- compiler/src/middle_end/anf_mapper.re
- compiler/src/middle_end/anf_utils.re
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/middle_end/linearize.re
- compiler/src/middle_end/optimize.re
- compiler/src/middle_end/optimize_constants.re
- compiler/src/middle_end/optimize_dead_assignments.re
- compiler/src/middle_end/optimize_dead_branches.re
- compiler/src/middle_end/optimize_local_mutations.re
- compiler/src/middle_end/optimize_local_mutations.rei
- compiler/src/parsing/parsetree.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/test/input/letMutForLoop.gr
- compiler/test/test-libs/letMutExport.gr
- compiler/test/test_end_to_end.re
This PR optimizes `let mut` to use function locals instead of boxes, where possible. (It's not possible to do this when the mutable variable is closed over, which is why `let mut` uses boxes under the hood.)
In addition to some performance gains, this also makes it possible to use `let mut` with unsafe wasm values, and there's a test that showcases this.
> feat: Optimize local mutations

- compiler/src/codegen/compcore.re
- compiler/src/codegen/compcore.rei
We were putting way more than we needed to in our function tables, so this PR cleans that up. It also makes processing of function names a bit cleaner.
> chore: Clean up function tables

- compiler/src/codegen/compcore.re
- compiler/src/codegen/mashtree.re
- compiler/src/codegen/transl_anf.re
- compiler/src/middle_end/analyze_purity.re
- compiler/src/middle_end/analyze_tail_calls.re
- compiler/src/middle_end/anf_helper.re
- compiler/src/middle_end/anf_helper.rei
- compiler/src/middle_end/anf_iterator.re
- compiler/src/middle_end/anf_mapper.re
- compiler/src/middle_end/anf_utils.re
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/middle_end/linearize.re
This PR makes  (exported) Grain compiled functions have wasm function exports, i.e. if you compile the program `export let foo = x => 6` you'll see this in the compiled output:
This does two important things: 1) other languages (or the Grain compiler) can call Grain functions directly, as opposed to via loading the function pointer from the closure and using `call_indirect`, and 2) debugging compiled wasm output is much easier because the functions have their original source names.
There's not really a great way to write a test for this, but this functionality will be exercised heavily in the coming PRs.
> feat: Export compiled functions from modules

- compiler/src/typed/typecore.re
- compiler/test/test_end_to_end.re
Obviously not something that's very common, but something that I came across.
> fix: One-sided if results in any type

- compiler/src/middle_end/matchcomp.re
- compiler/test/input/patternMatchUnsafeWasm.gr
- compiler/test/test_end_to_end.re
It's not necessarily _hard_ to get i64/f32/f64s working, but it's not a feature we desperately need right now.
> feat: Allow pattern matching on unsafe wasm i32s

- compiler/test/test_end_to_end.re
- stdlib/stdlib-external/ascutils/numberUtils.ts
Closes #475. Figured this made sense to do before the rewrite.
I have to say—mad respect to the AssemblyScript team. This change was fairly straightforward to do because the offsets were kept as the number of digits instead of the number of bytes. 
To that, I'm fairly confident this is change is correct. Our tests pass, and my smoke testing looks good. We don't really have any tests _specifically_ for number `toString` functionality, but I added a couple for `Infinity/NaN` since I knew we didn't have any for those. Let me know if you think we should have more.
Also, for simplicity's sake, I left the same number of store functions for `DIGITS`/`HEX_DIGITS`/`ANY_DIGITS`, just because it's easier to read. It would be more efficient to store 4 pairs at once with a single `store<u64>` (by 4x), …
> feat: Optimize number to string conversions by writing UTF8 directly

- compiler/src/codegen/compcore.re
This uses the new constant introduced in binaryen.ml 0.9.0 (which internally is `-1`, the value that binaryen uses for unlimited size).
> chore: utilize `Function_table.unlimited` to set the max table size

- compiler/src/utils/wasm_utils.re
This removes the `MalformedLEB` exception and bit check and replaces it with an assert that checks to see a read byte is under 256.
This fix is needed in order for the compiler to run successfully when compiled to JS.
@ospencer is there a better way to phrase this commit message?
> fix: word-size independent LEB input byte checking

- compiler/src/parsing/parser.dyp
Fixes #558.
There's not really a great way to write tests for this without #560, since any inline assignment is a type error. Happy to add some tests after that's merged.
> fix: Parsing of conditional assignment with binary operators

- compiler/src/codegen/compcore.re
- compiler/src/codegen/mashtree.re
- compiler/src/codegen/transl_anf.re
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/middle_end/linearize.re
- compiler/src/typed/types.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
- compiler/test/test_end_to_end.re
- docs/contributor/printing.md
- runtime/src/core/runner.js
- stdlib/runtime/string.gr
This PR reimplements some support for printing from JS into Grain. As an added bonus, there is no longer a requirement that types be exported to be able to print them. 🎉 
Included in this PR is a new compiler flag, `--elide-type-information`, which allows you to save a bit of space by not including the information for `print`.
@phated I'm not sure if we want to label this as a breaking change—if anyone depended on the semantics of `toString` for non-exported types this would be a breaking change for them.
> feat: Implement printing support in Grain

- compiler/src/codegen/compcore.re
- compiler/src/typed/env.re
- compiler/src/typed/env.rei
- compiler/src/typed/typemod.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
- docs/contributor/runtime.md
- stdlib/runtime/malloc.gr
- stdlib/runtime/string.gr
This PR refactors the runtime setup to be simpler and better handle the upcoming changes to exceptions and static linking.
This PR goes from 4 compilation modes down to just two, `Normal` and `Runtime`. `--compilation-mode=malloc` is now the same as `--compilation-mode=runtime`, since a static pointer has been allocated for the runtime heap pointer. `--compilation-mode=managed-runtime` has been superseded by `--no-pervasives` 🎉 
I also added some documentation about how the runtime works!
> chore: Refactor runtime setup

- compiler/src/codegen/compcore.re
- compiler/test/runner.re
- compiler/test/test_end_to_end.re
- stdlib/exception.gr
- stdlib/pervasives.gr
- stdlib/runtime/exception.gr
chore!: Rename `registerBasePrinter` to `dangerouslyRegisterBasePrinter` in runtime/exception
fix: Throwing an exception now traps immediately in all cases
I added a test for the last fix, but there isn't a great way to test that the incRefs weren't happening. However, it gets exercised pretty well by changes in the linker PR.
> fix: Properly incRef exception printers

- compiler/dune-project
- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/esy.lock/opam/csexp.1.5.1/opam
- compiler/esy.lock/opam/dune-build-info.2.8.5/opam
- compiler/esy.lock/opam/dune-configurator.2.8.5/opam
- compiler/esy.lock/opam/dune.2.8.5/opam
This version includes a patch for our Int64 const generations in JS.
Looks like we got some dune upgrades and stuff as well since esy did a new resolve on packages.
> chore: upgrade binaryen.ml to 0.9.1

- cli/bin/grain.js
- cli/package.json
- yarn.lock
I ripped out v8flags and flagged-respawn in favor of `v8.setFlagsFromString` because flagged-respawn doesn't work with pkg.
> chore(cli): Remove flagged-respawn for built-in v8 method

- runtime/package.json
- runtime/src/runtime.js
- yarn.lock
This PR moves our runtime deps to devDeps because the `pkg` tool tries to pull in everything in `dependencies`, which causes a bunch of issues. However, we just bundle and ship the bundles anyway, so I changed the `main` and `browser` fields to point at the produced `dist` files.
I also removed treeify because it didn't seem to be used. And I fixed an issue with the re-used identifier `GrainRunner`... no idea why babel casually allows that but real JS runtimes throw.
> Runtime cleanup in preparation of pkg

- compiler/src/codegen/compcore.re
This ensures we always get an int64 in little endian from bytes instead of relying on native-endian.
> fix(compiler): Always get little endian i64 from bytes

- stdlib/index.js
- stdlib/package.json
This replaces the `main` file in the stdlib's `package.json` to point to a valid JS file, which just exports the `__dirname` of the location of the stdlib.
This is necessary because the `pkg` tool parses the `main` entrypoint and it needs to be valid JS, otherwise the packaging fails. Having the `index.js` export the `__dirname` is just a neat trick so you can do `const stdlibLocation = require('@grain/stdlib')`
> chore(stdlib)!: Replace JS entrypoint with locator file

- compiler/grainc/grainc.re
There's really no need to see these backtraces when you aren't in grainc debug mode.
> fix(grainc): Only print compiler backtraces in debug mode

- .gitignore
- cli/.prettierignore
- cli/bin/compile.js
- cli/bin/exec.js
- cli/bin/grain.js
- cli/bin/grainc.js
- cli/bin/lsp.js
- cli/bin/pkg.js
- cli/bin/run.js
- cli/package.json
- compiler/dune-project
- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/grainc/dune
- compiler/grainc/jsoo_hacks.js
- compiler/grainc/runtime.js
- compiler/src/utils/files.re
- package.json
- stdlib/package.json
- yarn.lock
All my current work to get GrainJS working.
I believe I have some other ideas to actually just compile `grainc` to JS, so I've marked this as draft.
> feat: Compile grainc to JS & create binaries with pkg

- yarn.lock
Let's make that security indicator go away.
> chore: Regenerate yarn.lock for updated dependencies

- .github/workflows/release.yml
This adds a Release workflow that currently just runs release-please. I'll expand upon this to generate the Packaged Grain binaries and attach them to the release.
> ci: Add most simple release workflow

- .github/workflows/docker-publish.yml
- .github/workflows/release.yml
Doesn't seem like that `$default-branch` thing works outside of templates. I also fixed the docker workflow branch name.
> chore: Use main branch name in workflows

- cli/bin/lsp.js
I'm not sure why the debug flag was added to the lsp command, but it causes .modsig and .wast files to be generated all over the place. I think we should remove it unless @ng-marcus or @ospencer has a reason it needs to be there.
> chore(cli): Remove debug flag from lsp exec call

- .github/workflows/release.yml
I tested this workflow in my personal fork: https://github.com/phated/grain/releases/tag/grain-v0.4.0
I think we should just manually do the npm publishes on stdlib and runtime for the 0.3.0 release (since they don't exist yet). I'll open an issue to automate that.
> ci: Add Binary creation & upload to release workflow

- cli/bin/compile.js
- cli/bin/exec.js
- cli/bin/grain.js
- cli/bin/lsp.js
- cli/package.json
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
- yarn.lock
chore(cli)!: Remove `-f` CLI option
chore(compiler)!: Remove --principal-types and --recursive-types compiler flags
chore(compiler)!: Rename --cdebug to --verbose
> feat(cli)!: Pass compiler flags from the CLI to grainc directly

- compiler/src/typed/module_resolution.re
This seems to be the underlying issue of why large portions of the dependency graph would be recompiled unnecessarily. With my checks, it looks like only changed files are recompiled.
> fix(compiler): Resolve names when doing CRC checks

- Dockerfile
As was mentioned in #569, the compiler (specifically Binaryen) doesn't build on debian, so we need to make our docker image an ubuntu image. I copied the nodejs setup stuff from their image and embedded it in ours.
When building on Mac, you need to crank up the RAM given to the docker service because JSOO needs more than 2gb of RAM otherwise it is SIGKILLed.
> fix(docker): Build our own image of ubuntu+node14

- cli/bin/lsp.js
Whoops, typo. Too late to get in this release, but it just causes a crash to crash so 🤷
> fix(cli): Correct typo in lsp catch block

- compiler/test/stdlib/queue.test.gr
- compiler/test/stdlib/stack.test.gr
- stdlib/queue.gr
- stdlib/stack.gr
Reverts grain-lang/grain#625
Pulling out this breaking change so we can release some bug fixes before 0.4.0.
> revert: "chore!: rename Queue/Stack lib methods (#625)"

- compiler/grainc/jsoo_hacks.js
I believe this fixes #621 
I did a ton of logging and it seems that js_of_ocaml only makes a `jsoo_mount_point` for the drive letter of the `process.cwd()`; however, our `pkg` tool's virtual snapshot adds `C:` to all of the paths included in it. This checks to see if the caml_root is not `C:` and adds it as a `jsoo_mount_point` if not (only on Windows).
This is definitely not the best place for this to go, but it is really just a temporary solution.
> fix: Workaround for Windows drive letters with jsoo & pkg

- release-please-config.json
This is needed because we had a breaking change merged and then reverted it but the bot doesn't know how to undo that...
From the ReleasePlease docs:
> manually set next version to be "x.x.x" ignoring conventional commits.
> absence defaults to conventional commits derived next version.
> Note: once the release PR is merged you should either remove this or
> update it to a higher version. Otherwise subsequent `manifest-pr` runs
> will continue to use this version even though it was already set in the
> last release.
Basically: we need to be super careful with this, and then remove it once we cut the release.
> chore: Remove bootstrap-sha & set release-as for 0.3.1

- release-please-config.json
I removed the release-as for 0.3.1 - closes #637 
Since we want to be more conscious with breaking changes and only want to batch them into the next minor, I think we should allow new non-breaking features in patches. This will allow us to merge changes like #635 that add new things while deprecating old for the next breaking release.
Additionally, I tried adding the `node-workspace` plugin now that it works with monorepos to keep our `@grain/cli` in sync with version bumps happening in stdlib & runtime.
And finally, I removed the package names for the node releasers because they aren't actually used.
H/T @joeldodge79 for all the tips.
> chore(releaser): Remove release-as & allow features in patch

- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/src/codegen/comp_utils.re
- compiler/src/codegen/comp_wasm_prim.re
- compiler/src/codegen/compcore.re
- compiler/src/linking/link.re
This should fix `Binaryen`-related type errors, after [this PR](https://github.com/grain-lang/binaryen.ml/pull/102) gets merged, and we update the `@grain/binaryen.ml` dependency
> Update Binaryen usage to match latest bindings

- compiler/src/middle_end/linearize.re
> fix: Always use correct wasm type for `throw`

- compiler/src/parsing/lexer.mll
- compiler/test/test_end_to_end.re
Ref https://github.com/grain-lang/grain-language-server/issues/46
We don't really have a great way to test locations right now, so I just added some tests that the locations are correct when using comments.
I also dropped support for the single `CR` and `LFCR` line endings since a single `CR` hasn't been used since Mac OS 9 and I don't think `LFCR` was ever a thing (I did find one guy on Stack Overflow who memed about it, but that's it). I didn't count this as a breaking change because I'm _fairly_ sure Grain doesn't work on Mac OS 9. If anyone feels like we should mark it as breaking though, we can mark it as such.
> fix(compiler): Correct reporting of locations for CRLF files

- .gitignore
- cli/bin/grain.js
- compiler/src/codegen/emitmod.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
- compiler/src/utils/files.re
This PR splits the `-g` `grainc` flag into `--debug` and `--wat`. The WebAssembly Text files produced are now named with a `.gr.wat` extension instead of `.gr.wasm.wast` to no longer use the deprecated `wast` name, and to match `.gr.wasm` <-> `.gr.wat`.
> feat(cli)!: Split -g into --debug and --wat

- compiler/test/input/mallocTight.gr
- compiler/test/test_end_to_end.re
- stdlib/runtime/malloc.gr
This PR fixes a pesky bug that only appears under absolutely perfect™️ conditions.
Currently, if the free list only contains one block and it's exactly the same size as the amount of requested memory, it will not be released from the free list. As such, further requests for that same size will result in the same pointer being allocated over and over again.
We hadn't noticed this because the stars really have to align to hit this case! In the case of [this run](https://github.com/grain-lang/grain/pull/698/checks?check_run_id=2750176540), it was the addition of a closure that happened to be just the right size that later calls to malloc would be perfectly sized to trigger the bug.
I reviewed the reference implementation and realized this was because we weren't setting up the free list …
> fix: Properly initialize malloc free list

- stdlib/sys/time.gr
The getClockTime function was overwriting the number tag and thus returning invalid instances of Int64.
> fix(stdlib): return proper values from getClockTime for Sys/Time

- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/esy.lock/opam/ocaml-lsp-server.1.4.1/opam
- compiler/package.json
- yarn.lock
I tried to jump back into the project and the ocaml-lsp was really angry. I made these changes and it is working again.
Note: we are on a "really" old version of ocaml-lsp because 1.5.0 dropped support for ocaml <4.12 but they backported some merlin fixes to 1.4.1
> chore(deps): Update esy & ocaml-lsp

- compiler/test/dune
- compiler/test/suites/arrays.re
- compiler/test/suites/basic_functionality.re
- compiler/test/suites/boxes.re
- compiler/test/suites/chars.re
- compiler/test/suites/comments.re
- compiler/test/suites/dune
- compiler/test/suites/enums.re
- compiler/test/suites/exceptions.re
- compiler/test/suites/exports.re
- compiler/test/suites/functions.re
- compiler/test/suites/gc.re
- compiler/test/suites/imports.re
- compiler/test/suites/let_mut.re
- compiler/test/suites/linking.re
- compiler/test/suites/lists.re
- compiler/test/suites/loops.re
- compiler/test/suites/numbers.re
- compiler/test/suites/optimizations.re
- compiler/test/suites/pattern_matching.re
- compiler/test/suites/print.re
- compiler/test/suites/records.re
- compiler/test/suites/stdlib.re
- compiler/test/suites/strings.re
- compiler/test/suites/tuples.re
- compiler/test/utils/concatlist.re
- compiler/test/utils/dune
- compiler/test/utils/wasm_utils.re
My understanding is that `(include_subdirs unqualified)` is a bad stanza and we shouldn't be using it, so I dove into setting up the tests repository more correctly. This required adding dune files for the suites and utils and setting up the framework/runner library differently, but things seem to be working.
> chore(tests): Add dune files to configure tests properly

- cli/bin/grain.js
- cli/bin/run.js
- compiler/src/linking/link.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
- compiler/test/runner.re
- runtime/package.json
- runtime/src/core/closures.js
- runtime/src/core/memory.js
- runtime/src/core/runner.js
- runtime/src/core/tags.js
- runtime/src/runtime.js
- runtime/src/utils/utils.js
- yarn.lock
feat(compiler): Add --initial-memory-pages and --maximum-memory-pages to set module memory limits
feat(runtime)!: Removed --limitMemory, GRAIN_INIT_MEMORY_PAGES, and GRAIN_MAX_MEMORY_PAGES in favor of --initial-memory-pages and --maximum-memory-pages
feat(runtime)!: Removed `managedMemory`, `memory`, and `table` exports. These can be accessed via `runner.managedMemory`, `runner.managedMemory._memory`, and `runner.table` respectively.
feat(runtime)!: Removed `encoder` and `decoder` exports.
The important takeaway from this PR is that it adds two new flags, `--initial-memory-pages` and `--maximum-memory-pages`, which work in both linked and non-linked mode (versus the fragmented way it was done before).
> feat(compiler)!: Universal WebAssembly initial and maximum pages flags

- compiler/test/suites/print.re
- stdlib/runtime/string.gr
This splits out the record printing fix. However, I also needed to add a test for it.
> fix(stdlib): Correctly indent nested record braces when printing

- stdlib/bytes.gr
- stdlib/number.gr
- stdlib/runtime/numbers.gr
This PR adds a simple function for Number to WasmI32 conversion that just wraps an existing one. The new function adds a bit of type safety instead of just exposing coerceInt32. It also replaces the duplicate function in Bytes module, which is replicated in the Buffer module currently proposed in PR #710 as well.
@ospencer briefly mentioned on Discord the possibility of just exporting coerceInt32 directly instead of a wrapper function, so if that is preferable I don't mind changing it.
> feat (stdlib): coerceNumberToWasmI32

- stdlib/array.gr
I started with `Array.zip` in order to land #699
I attributed the commit to @peblair but I also made a change to explicitly guard on the array lengths since a longer `b` wouldn't error. I'm not sure how much I like this API being a "fail" API but I think it is fine for now.
I didn't add tests since they are added in #699
> feat(stdlib): Add Array.zip function

- compiler/test/__snapshots__/comments.573e549e.0.snapshot
- compiler/test/suites/comments.re
The `//` in the name of this test caused a directory called `comment_lone_` to be created in the `test/output` directory and then it wrote files named **just** `.gr.wasm`, `.gr.wat`, and `.gr.modsig` into it.
This just renames the test and updates the snapshot so that doesn't happen.
> chore(tests): Fix test name that created directory

- stdlib/package.json
When the CLI changes landed, it looks like this didn't get updated. I'm unsure if I should have kept the mashtree glob.
> chore(stdlib): Update clean command to delete new files

- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/src/typed/typemod.re
In preparation of "graindoc", I need to submit a few cleanup PRs.
This attaches the comments from the `parsed_program` to the `typed_program` because the documentation generator runs the compiler until typechecking is complete and then combines the type signatures with the comments.
I'm not sure this needs to be tested because it is typechecked and doesn't actually modify the comments at all. We already test the comments are parsed correctly in the Parsetree.
> chore(compiler): Attach comments to the typed_program

- compiler/src/typed/printtyp.re
In preparation of "graindoc", I need to submit a few cleanup PRs.
This doesn't technically need to land for the documentation generator, but it was something I ran into while writing the code so we might as well clean it up.
> chore(compiler): Remove some shadowed & commented printtyp code

- compiler/test/stdlib/array.test.gr
- stdlib/array.gr
This adds `slice` to the Array stdlib. I actually rewrote the function because I believe our guiding principals on the stdlib is to be graceful where possible. This change is likely to be a bit controversial for the team so I'd like feedback if anyone doesn't think we should handle indexes too large or negative indexing from the end.
> feat(stdlib): Add Array.slice function

- compiler/src/parsing/parser_header.re
- compiler/src/utils/string_utils.re
- compiler/test/suites/comments.re
In preparation of "graindoc", I need to submit a few cleanup PRs.
This improves our comment string trimming to trim each line of a Doc or Block comment which allows for a more precise regexp in the documentation attribute parser (so each attribute line will start with an `@`-symbol).
> chore(compiler): Trim each line of a block or doc comment

- compiler/src/typed/oprint.re
In preparation of "graindoc", I need to submit a few cleanup PRs.
This cleans up some codepaths I encountered when trying to print Grain types inside the documentation generator. Some stuff is just little nits, while others were completely wrong and still printing OCaml-like types.
I think that "graindoc" will just be the "tests" for this.
> chore(compiler): Cleanup in oprint to print Grain code correctly

- stdlib/range.gr
This adds doc comments to the `range.gr` file in our standard library. It was my test file for all my Graindoc work and I wanted to submit this PR before Graindoc to find out if anyone has qualms with the doc comment syntax/attributes/structure/whatever.
> chore(stdlib): Add doc comments to Range

- README.md
I noticed the fury.io stuff was broken again, so I went to update the badges. I switched to shields.io to read the latest version and I squared them up.
> chore: Simplify the badges, square them & fix version

- compiler/src/parsing/parser_header.re
- compiler/src/utils/string_utils.re
- compiler/test/suites/comments.re
- stdlib/range.gr
This was the intended behavior of how `cmt_content` would work (and why we have both `cmt_source` and `cmt_content` in the first place 🤦). Added bonus: this makes writing `* @param` work with Graindoc 😄
> fix(compiler): Strip leading line asterisks in block and doc comments

- compiler/test/suites/numbers.re
- stdlib/runtime/equal.gr
- stdlib/runtime/numbers.gr
(I'm pretty sure this commit name will need to be changed)
I split out the change for Number equality and labeled it as a breaking fix. However, when writing tests for this, I noticed that `5 == 5.0` is false but `5.0 == 5` is true. Need someone's help to fix that, but it highlights the importance of writing tests for all our changes.
> fix!: Adjust Number equality, thus that 5 == 5.0

- compiler/src/typed/oprint.re
While writing docs, I noticed that the LSP was looking weird for functions that had no arguments. This was due to my oprint PR that skipped parens if arguments were <= 1 - this was incorrect and we should **only** skip the parens for single-argument functions.
This restores parens to argument-less functions.
> fix(compiler): Print parens for argument-less functions

- compiler/src/typed/oprint.re
While writing some docs, I noticed that our records were pretty-printing inaccurately. With these changes, this is how a few of the records from stdlib print:
```grain
record Bucket<k, v> {
key: k,
value: v,
next: Option<Bucket<k, v>>,
}
```
```grain
record Map<k, v> {
size: Number,
buckets: Array<Option<Bucket<k, v>>>,
}
```
```grain
record Stack<a> {
data: List<a>,
}
```
> fix(compiler): Correct pretty-printing of record types

- README.md
Whoops, I didn't catch that this link just links to the badge SVG. We should actually link to our runs.
> chore: Fix badge link to CI workflow

- compiler/grainc/grainc.re
- compiler/src/compile.re
- compiler/src/typed/typed_well_formedness.re
- compiler/src/typed/typed_well_formedness.rei
- compiler/src/utils/warnings.re
- compiler/src/utils/warnings.rei
Closes #738.
This pull request adds a QOL improvement for low-level standard WASM development by emitting a warning when `Pervasives.(==)` is used to compare any of the following types: `WasmI32`, `WasmI64`, `WasmF32`, and `WasmF64`. This is accomplished by a new well-formedness pass on the Typed AST, which we can add things to in the future. To illustrate, consider the following `tst.gr` file:
```grain
import WasmI32 from "runtime/unsafe/wasmi32"
assert 9n == WasmI32.fromGrain(4)
assert WasmI32.toGrain(9n) == 4
let (==) = WasmI32.eq
// safe, since we have shadowed (==) with the WasmI32 variant
assert 9n == WasmI32.fromGrain(4)
```
The compiler now emits the following:
```
λ grain git:(warn-wasm-unsafe-equal) > grain tst.gr                             
File "tst.gr", line 2, characters …
```
> feat(compiler): Emit a warning when using Pervasives.(==) with unsafe Wasm types

- compiler/graindoc/docblock.re
- compiler/src/diagnostics/comments.re
- compiler/src/utils/markdown.re
- stdlib/stack.gr
This adds support in GrainDoc for the `@deprecated` attribute. I decided to generate this markdown when the attribute is encountered:
```md
> **Deprecated:** Message for deprecation
```
(This currently doesn't style well on the website, but we can fix that.)
The deprecation markdown is inserted after the function name but before the type signature or any other documentation.
I also added my Stack documentation to this PR so y'all can test the generation to see if you like it. If you'd like me to split that documentation out before merge, let me know.
> feat(graindoc): Add support for deprecated attribute

- cli/bin/grain.js
When @ospencer removed the env var hack to apply memory settings, we missed removing this workaround. Let's get rid of it now.
cc @marcusroberts because you'll need to update the import in your formatter code.
> chore(cli): Remove workaround now that env vars are gone

- compiler/test/TestFramework.re
- compiler/test/runner.re
This refactors some of our test pathing and makes sure we cleanup the test-libs directory, since having old code there caused some test failures when changing compiler internals.
> chore(compiler): Refactor test paths & clean up more output

- compiler/src/parsing/parser.dyp
- compiler/test/__snapshots__/basic_functionality.1f787365.0.snapshot
- compiler/test/__snapshots__/basic_functionality.9b9c7047.0.snapshot
- compiler/test/__snapshots__/basic_functionality.d6ca4146.0.snapshot
- compiler/test/__snapshots__/loops.0a25def1.0.snapshot
- compiler/test/suites/basic_functionality.re
- stdlib/runtime/gc.gr
Up until this PR, ending a statement with a semicolon had the same effect as calling `ignore` on that statement. We found this feature to be too subtle, often causing more confusion than the feature was worth. This PR removes that behavior.
> feat(compiler)!: Remove semantic meaning of semicolons

- compiler/src/typed/typed_well_formedness.re
- compiler/src/utils/warnings.re
- compiler/src/utils/warnings.rei
Fixes issue found by @phated .
> feat(compiler): Emit a warning when using Pervasives.(!=) with unsafe Wasm types

- compiler/test/stdlib/wasmi32.test.gr
- stdlib/runtime/equal.gr
- stdlib/string.gr
Closes #746
The new warnings helped catch some more references to `Pervasives.(==)` and `Pervasives.(!=)` in the stdlib and tests. This fixes those issues and then removes the `isNumber(y)` workaround.
Probably should land after #758
> fix(stdlib): Correct usages of `==` and `!=` on WasmI32 values

- compiler/grainc/grainc.re
The LSP stopped working after #742 because the pattern match wasn't updated. This fixes it and adds a failure so we catch that in the future.
> fix(lsp): Pattern-match the phase to match the stop hook

- compiler/src/typed/oprint.re
While working on some docs, I noticed an extra space in tuples when being printed. This updates oprint to remove where I believe it was coming from.
> chore(compiler): Remove extra space when printing tuples

- stdlib/runtime/malloc.gr
This PR should speed up all grain programs at least a little bit by avoiding redundant memory accesses in Malloc.free.
I hope someone can carefully triple check this change so we can feel a little bit greener 💚
Synthetic test:
just allocate and free 1000000 strings  of 10 bytes each in a loop (with @disableGC).
207ms-216ms unoptimized
198ms-207ms optimized
Slightly less synthetic test:
Emit 15KiB json.
127ms-132ms unoptimized
74ms-81ms optimized
Emit 150KiB json.
5969ms-6364ms unoptimized
2955ms-3188ms optimized
Side note: Emit json time seems to grow exponentially with input size, but its not the case. It's because of a memory leak in GC (#745) so my benchmark results are heavily skewed with each iteration of the same being slower. 1.5MiB json takes 14 minutes (compare that to 5ms for …
> Reduce reduntant memory loads in Malloc.free.

- compiler/test/stdlib/string.test.gr
- stdlib/string.gr
This PR adds two optimized functions to iterate over Unicode code point that make up a given String. It's equivalent to calling String.explode and then converting single chars to code points, but a lot more efficient since no heap allocations are made.
> feat(stdlib): forEachCodePoint and forEachCodePointi

- stdlib/runtime/string.gr
This PR fixes a memory leak in the print function.
The intermediate string created was not freed. I'm not entirely sure I'm using the "right" free. Or maybe I should call decRef instead?
ps: I was using print to debug memory leaks, which lead me to the memory leak in print. So then I used print to debug the memory leak in print. 🤟
> fix(stdlib): Fixed memory leak in the print function.

- compiler/graindoc/docblock.re
While previewing some GrainDoc output, I noticed that words coming after `Array<a>` got turned into a link (because that's an html element!), so I think we should always wrap types in an inline code block.
> chore(graindoc): Print param/return types as inline-code

- stdlib/map.gr
This implements Map.toArray without converting it to an intermediate list. This avoids blowing the stack on huge Maps when you don't have experimental tail calls, and it increases performance by 25%.
Closes #187 (which this implementation inspired, and proves that we can allocate an array without items in it).
> chore(stdlib): Implement Map.toArray without intermediate list

- stdlib/runtime/numbers.gr
Avoid unnecessary and slow conversion to WasmI64 and back in case of simple and boxed int32 numbers.
> feat(stdlib): Optimized coerceNumberToWasmI32.

- stdlib/number.gr
- stdlib/number.md
This updates the number docs to the newest graindoc "spec" (I know that I still need to write that) and adds the `@since` attribute where needed.
I'm not sure how we wanted to phrase the `@returns` description so please review those carefully.
Additionally, this is the first PR where I'm checking in generated markdown files so everyone can review the output and we can notice any problems in diffs going forward.
> chore(docs): Update doc comments for Number module

- compiler/src/parsing/parser.dyp
This PR fixes toplevel statement srclocs in order to support @marcusroberts's `format-ignore` work.
> fix(compiler): Fix location information for parsed toplevel statements

- compiler/test/stdlib/result.test.gr
- stdlib/result.gr
This adds `Result.expect` and `Result.unwrap` functions to the stdlib. I realized that my test changes in #792 wouldn't actually work, so I'll need these methods to write those tests in a (relatively) nice fashion.
> feat(stdlib): Add Result.expect & Result.unwrap functions

- compiler/graindoc/graindoc.re
When I started writing the docs for our `stdlib/sys/file.gr` module, I noticed that I needed this extra content under the module definition:
> Many of the functions in this module are not intended to be used directly, but rather for other libraries to be built on top of them.
This is too long to inline into the `@module` attribute line, so instead I am now inserting any non-attribute content between the attr_desc and the example.
> feat(graindoc): Add support for extra information in module docblock

- compiler/src/typed/oprint.re
While working on the `stdlib/sys/file.gr` documentation, I found that variants without arguments don't actually print with a trailing comma. This fixes it.
> fix(graindoc): Ensure argument-less variants print with trailing comma

- compiler/test/dune
- compiler/test/runner.re
- compiler/test/test_utils.re
This PR introduces a timeout for tests in the test suite. This is useful when developing changes to the runtime, as memory corruption can often result in hangs. When this happens, the runner tells you the test suite but not the individual test which is hanging. With this change, hanging tests will fail, and they will then be displayed on the console.
I went ahead and set the timeout to 15 seconds, but this was an arbitrary choice.
> chore(compiler): Introduce timeout for compiler tests

- stdlib/array.gr
- stdlib/array.md
This updates the Array module doc blocks with `@since` and `@history` attributes. I also noticed that I missed 1 `@returns` in my initial PR.
I also checked in the generated `array.md` file.
> chore(docs): Add `@since` and `@history` annotations for Array

- compiler/package.json
- yarn.lock
Updating esy to 0.6.11 which has the "extra-sources" and `{post}` support for opam files. We'll need both of these in the future.
> chore: Upgrade esy

- js-runner/src/core/memory.js
While trying to update the Grain web example, I found out that our js-runner crashes if you don't provide an options object to `buildGrainRunner` due to trying to destructure from undefined in `ManagedMemory`.
This just adds a default object to the constructor of `ManagedMemory` so it doesn't crash like that.
> fix(js-runner): Add default object for destructuring

- compiler/src/parsing/well_formedness.re
- compiler/test/__snapshots__/chars.27fb7f30.0.snapshot
- compiler/test/suites/chars.re
@jozanza noticed that 3-byte utf-8 characters trigger a well-formedness error for char literals. I think there's a bug in the utf8 library we're using (or that I just didn't understand what a few functions did), so here's an easy workaround. Issue to see what's up with the function we were using: https://github.com/reasonml/reason-native/issues/266
> fix(compiler): Fix incorrect char well-formedness error

- compiler/src/linking/link.re
- stdlib/runtime/gc.gr
- stdlib/runtime/string.gr
Between #800 being submitted and merged, we also landed some changes to the stdlib that changed the calling convention in non-GC contexts. This required adding some `fd_sync` imports for debugging and they didn't get removed, which caused the linker to fail on our wasi polyfill tests.
Here, I've added a better error message for this case and then removed the 2 references to fd_sync in our stdlib, so the tests should pass again.
> fix(stdlib): Remove fd_sync calls that are not used

- compiler/test/stdlib/string.test.gr
- stdlib/string.gr
The two bit prefix was applied incorrectly on the second byte. Also, changed the format of bit masking and prefixing constants to binary for easier reasoning about the encoding.
> fix(stdlib): Fixed String.writeUtf8CodePoint for two byte sequences.

- compiler/test/stdlib/sys.file.test.gr
- compiler/test/stdlib/sys.process.test.gr
- compiler/test/stdlib/sys.random.test.gr
- compiler/test/stdlib/sys.time.test.gr
- compiler/test/suites/stdlib.re
- stdlib/sys/file.gr
- stdlib/sys/file.md
- stdlib/sys/process.gr
- stdlib/sys/process.md
- stdlib/sys/random.gr
- stdlib/sys/random.md
- stdlib/sys/time.gr
- stdlib/sys/time.md
Fixes #688
I changed all the methods in `stdlib/sys` that throw errors into Result-returning functions. This solves the issue where you want to see if a file exists and handle that case.
I also changed `sys/process.gr`, `sys/time.gr` and `sys/random.gr` but I'm unsure how bad it'll feel to use those methods. What are y'alls opinions?
I wanted to get feedback here before I update the docs, but those will go in this same PR.
> feat(stdlib)!: Convert sys functions to return Results instead of throwing errors

- js-runner/src/core/grain-module.js
While trying to update the Grain web example, I found out that using fd_write on `/dev/stdout` doesn't actually log in the browser.
This monkeypatches the memfs library used by wasmerjs to `console.log` or `console.error` when fd 0 or 1 is written to.
The downside to this patching is that the newline at the end of our `print` is stored in a different iov (?) so it logs separately (here's a screenshot):
> fix(js-runner): Monkeypatch fs_write in browser environment

- cli/bin/grain.js
- compiler/src/linking/link.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
- compiler/test/suites/linking.re
This adds a config (and corresponding flag) to the linker that allows people to disable the WASI convention of exporting a `_start` function and instead set a start section in the linked output. This is needed for NEAR because they don't call the `_start` function and rely on the start section during instantiation.
I want to make 1 more improvement to the added tests after @ospencer takes a stab at parsing the exports in our Wasm_utils.
> feat(linker): Add --use-start-section flag to use start section in output

- cli/bin/exec.js
When my NodeJS was in C:\Program Files\... the exec would try and run C:\Program
Fix: Wrap the node executable in quotes
> fix(cli): Support NodeJS installed into a path with spaces

- compiler/grainformat/reformat.re
- compiler/grainformat/walktree.re
- compiler/grainformat/walktree.rei
- compiler/test/formatter_inputs/comments.gr
- compiler/test/formatter_outputs/comments.gr
Improvements to comment handling - handle trailing comments on the same line as the expression only, and then look for any remaining comments at the end of blocks.
Fixes #856
> fix(grainfmt): Handle trailing block comments better

- compiler/grainformat/reformat.re
- compiler/test/formatter_inputs/matches.gr
- compiler/test/formatter_outputs/matches.gr
The formatter was removing the space between arguments, which I ran into this issue when writing some enum pattern matches. This fixes that so there is always a space after a comma.
> fix(grainfmt): Correctly add space between arguments in enum pattern

- compiler/src/parsing/parsetree.re
Noticed when comparing ASTs for the formatter that comments still had their locations shown when location reporting was disabled.
> fix(compiler): Don't report comment locations when disabled

- compiler/src/parsing/lexer.mll
I believe a line comment should only ever be a single line.
The lexer was including any following newlines
// this is a comment\n
\n
\n
Change to add only the newline at the end of the comment to the comment source
> fix(compiler): Stop line comment lex absorbing the newlines after

- compiler/grainformat/reformat.re
The compiler currently needs parens around the trailing type annotation:
`let ret = WasmI32.toGrain(array): (Array<a>)`
so the formatter adds these now.  Also used Doc.space near colons as better form.
> fix(grainfmt): Use Doc.space and surround trailing type annotations with parens

- compiler/grainformat/reformat.re
- compiler/test/formatter_inputs/imports.gr
- compiler/test/formatter_outputs/imports.gr
Fixes #862 by properly re-printing comments found in import statements
> fix:(grainfmt): Handle comments in import statements

- compiler/test/suites/print.re
- stdlib/runtime/string.gr
As an optimization in the runtime string module, we don't follow the regular calling convention to avoid some unnecessary incRefs/decRefs. Before the calling convention changed, an enum constructor would always incRef its arguments. With the new convention, it still does, however it also decRefs the arguments, expecting that they were incRef'd before being passed.
The tl;dr is that `SLEmpty` needs an extra incRef. We should maybe consider reworking the lists in this module to follow the convention, but I think this is a fine fix for now.
> fix(stdlib): Premature free in toString

- cli/package.json
Due to the rename of runtime to js-runner, this didn't get automatically bumped. This manually bumps it for this time, but it should be automatically bumped going forward.
> fix(cli): Manually bump CLI dependencies

- stdlib/buffer.gr
I generated the Buffer docs and found out that these 2 functions have their parameters inferred as generic types, so we need to annotate them.
> fix(stdlib): Annotate generic types in Buffer

- stdlib/sys/file.gr
When regenerating these docs, I noticed that fdPwrite had the wrong return value.
> fix(stdlib): Correct fdPwrite return value

- stdlib/array.gr
- stdlib/array.md
While reviewing the website docs, I found some issues with the type signatures of Array functions.
> fix(stdlib): Correct type signatures on some Array functions

- stdlib/sys/file.gr
- stdlib/sys/file.md
Found this while reviewing the docs on the website.
> chore(stdlib): Fix missing backtick in sys/file docs

- compiler/grainformat/reformat.re
- compiler/test/formatter_inputs/function_params.gr
- compiler/test/formatter_outputs/function_params.gr
Fixes #870 
Don't add spaces before/after types in function signature
> fix(grainfmt): Remove extra spacing from type signatures

- stdlib/buffer.gr
- stdlib/buffer.md
I wasn't happy with the way the docs for Buffer are organized on the website, so I reorganized the file and added a new section.
> chore(stdlib): Reorganize buffer library for better docs

- compiler/test/suites/print.re
- stdlib/runtime/string.gr
Fixes #892. The problem appeared to be with `reverse()`, but commenting that function out appeared not to make the problem entirely go away. Since `slConsDisableGC` had confusing semantics anyway, @ospencer and I decided it would be best to make it _more_ align with the standard calling convention; it now incRefs its first argument (the head of the list). This required adding some extra decRefs, but we are less likely to prematurely free something now.
> fix(stdlib): Fix issue with list printing

- compiler/grainformat/debug.re
- compiler/grainformat/reformat.re
- compiler/grainformat/walktree.re
- compiler/test/formatter_inputs/brace_comments.gr
- compiler/test/formatter_inputs/enums.gr
- compiler/test/formatter_inputs/function_params.gr
- compiler/test/formatter_inputs/records.gr
- compiler/test/formatter_outputs/brace_comments.gr
- compiler/test/formatter_outputs/enums.gr
- compiler/test/formatter_outputs/function_params.gr
- compiler/test/formatter_outputs/records.gr
- compiler/test/suites/formatter.re
Fixes #884 and other similar code cases where comments follow an opening brace.
Improved record and record pattern printing
> fix(grainfmt): Resolve issues with comments within braces

- compiler/src/codegen/compcore.re
- compiler/test/__snapshots__/pattern_matching.16cd197e.0.snapshot
- compiler/test/__snapshots__/pattern_matching.5b158103.0.snapshot
- compiler/test/__snapshots__/pattern_matching.64686134.0.snapshot
- compiler/test/__snapshots__/pattern_matching.eb4334e1.0.snapshot
- compiler/test/suites/gc.re
Fixes #893.
@cician You are a lifesaver! Your repro was absolutely perfect and made finding this a breeze.
> fix(compiler): Follow proper calling convention when callling stdlib equals in match

- compiler/src/parsing/location.re
- compiler/src/utils/warnings.re
This PR will allow us to land Regex without exposing users to those compiler warnings. This PR buys us more time to properly investigate #681.
> chore(compiler): Disable by default principal type and type name scope compiler warnings

- README.md
Two changes:
- Replace build instructions in README to point to official Grain docs (to avoid maintaining two sets of build instructions)
- Update copyright year
Preview [here](https://github.com/grain-lang/grain/blob/philip/update-readme/README.md)
> chore: Update README to point to official build documentation

- compiler/grainformat/reformat.re
- compiler/test/formatter_inputs/imports.gr
- compiler/test/formatter_outputs/imports.gr
Fixes 
export foreign wasm promise_results_count: () -> WasmI64 as promiseResultsCount from "env"
to not break on the empty param types
> fix(grainfmt): handle empty type for foreign exports

- .github/workflows/ci.yml
- cli/bin/grain.js
This adds an conditional around the `--experimental-wasm-bigint` flag so we don't get a warning in node 16+. I also added node 16 to the test matrix in CI.
Closes #883 (but we should leave #114 open until we don't support node < 16 anymore).
> fix(cli): Avoid --experimental-wasm-bigint flag on node 16

- compiler/grainformat/reformat.re
- compiler/test/formatter_inputs/application.gr
- compiler/test/formatter_outputs/application.gr
Make sure we keep the parens for single param functions like this:
export let batchActionCreateAccount = ({index}) => {
Native.promiseBatchActionCreateAccount(Conv.fromInt64(index))
}
> fix(grainfmt): Fix the parens around single arg function params

- cli/bin/compile.js
- cli/bin/doc.js
- cli/bin/exec.js
- cli/bin/format.js
- cli/bin/grain.js
- cli/bin/lsp.js
This PR refactors `GraincOption` into `ForwardOption`. The major change is that cli subcommands will receive the options for their subcommand rather than the top-level `grain` command (except for `compile` and `run`).
Now, for example, for a subcommand you can add `.addOption(new ForwardOption("--write", "my description"))` and the `--write` flag will be forwarded to the underlying command.
The `--graceful` flag was really only meant to be used with `grain run`, but it's sort of made its way to being a catch-all. To keep backward compatibility I added a `wrapAction` function which will preserve the graceful behavior for all of the subcommands, though we should consider removing that behavior in a breaking version.
> feat(cli): Refactor forwardable options

- compiler/grainformat/reformat.re
- compiler/grainformat/walktree.re
- compiler/test/formatter_inputs/brace_comments.gr
- compiler/test/formatter_outputs/brace_comments.gr
Fixes issues with comments 
@peblair spotted this didn't reformat
export let setCounter = val => {
// Write the value to memory.
Storage.setInt32(key, val)
}
which uncovered some issues with comments in patterns, and comments after the lbrace in other expressions
> fix(grainfmt) Fixes comments after lbraces and in patterns

- compiler/src/parsing/location.re
- compiler/src/typed/parmatch.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
- compiler/test/WarningExtensions.re
- compiler/test/dune
- compiler/test/runner.re
- compiler/test/suites/pattern_matching.re
Most of the code here is really new testing support around warnings. Added custom matchers so we can do `expect.ext.warning.toHaveTriggered` and `expect.ext.warning.toHaveTriggeredNoWarnings`, and added some tests around the warning generation for boolean matches.
> fix(compiler): Don't warn on exhaustive boolean matches

- compiler/src/codegen/comp_utils.re
- compiler/test/input/wasiPolyfill.gr
This never was an issue with the linker since it generates a fresh module (which has no defined exports). It's an issue for the polyfill since it writes exports on an already-exiting module.
Somewhat related: #918
> fix(compiler): Remove existing exports when writing universal exports

- compiler/src/parsing/lexer.mll
- compiler/test/suites/chars.re
Fixes #930. Same story as the fencepost error we had with string literals.
> fix: Correctly preserve start position for character literals

- compiler/test/suites/linking.re
I changed the type of `compile` that's exposed to the tests, and missed that there were tests already using it directly.
> chore(compiler): Clear compiler warnings in linking tests

- compiler/grainformat/reformat.re
- compiler/test/formatter_inputs/arrays.gr
- compiler/test/formatter_inputs/list_sugar.gr
- compiler/test/formatter_inputs/strings.gr
- compiler/test/formatter_outputs/arrays.gr
- compiler/test/formatter_outputs/list_sugar.gr
- compiler/test/formatter_outputs/operators.gr
- compiler/test/formatter_outputs/spreads.gr
- compiler/test/formatter_outputs/strings.gr
Adding a comma after a spread in a list was a syntax error
[a,...b,]
Keep array set assignments on the same line as the =
Use constants direct from source to avoid losing any programmer intention regarding structure/format e.g. keep chars specified in the same format, numbers in the same base, etc.
> fix(grainfmt): Removed a trailing comma after a spread in a list, and fixed escaped single quote

- .github/workflows/release.yml
This adds 2 new jobs to our Release workflow. They initiate a `workflow_dispatch` event to the `Grain Release` workflows added in https://github.com/grain-lang/grain-lang.org/pull/258 and https://github.com/grain-lang/homebrew-tap/pull/5
Running a release now generates this workflow graph:
You can see a trial run from my personal repos:
* Grain release run: https://github.com/phated/grain/actions/runs/1281316653
* Triggered website run: https://github.com/phated/grain-lang.org/actions/runs/1281341528
* Generated website commit: https://github.com/phated/grain-lang.org/commit/675d3339c362bacc72d23304c0f1a44aa4f69d2f
* Triggered homebrew run: https://github.com/phated/homebrew-tap/actions/runs/1281341560
* Generated homebrew commit: …
> chore(ci): Configure release to trigger workflow_dispatch on other repos 

- compiler/src/middle_end/linearize.re
- compiler/test/__snapshots__/basic_functionality.4d6f9417.0.snapshot
- compiler/test/__snapshots__/basic_functionality.970a2a2b.0.snapshot
- compiler/test/__snapshots__/functions.d9466880.0.snapshot
- compiler/test/__snapshots__/functions.f647681b.0.snapshot
- stdlib/char.gr
- stdlib/runtime/string.gr
- stdlib/string.gr
Those snapshot diffs 💀 
This also fixes all memory issues related to this operator being a function.
> feat(compiler): Inline not `(!)` operator

- README.md
We'll probably remove this whole section, but for now we can at least get rid of the outdated command.
> chore: Update yarn commands in README

- compiler/src/typed/module_resolution.re
- compiler/src/utils/files.re
- compiler/test/TestFramework.re
Closes #943
The fix here was using the `Grain_utils.Files.get_cwd()` function which does the separator normalization. I made it in a separate commit than the cleanup for y'all to verify.
I also refactored some of the utils into `Grain_utils.Files` because all Fp utilities should live there (Grain_typed doesn't actually depend on `Fp` so we were relying on transitive deps).
> fix(compiler): Ensure cwd directory is normalized on Windows

- .github/workflows/release.yml
This adds additional jobs to our release workflow to publish `@grain/stdlib` and `@grain/js-runner` to npm if they were bumped as part of a release.
I actually needed to split the logic into 2 parts:
1. While we are building the compiler, we will also now run `npm pack` and uploaded the packed artifacts to the appropriate GitHub release. For example, the `js-runner.tgz` file will be uploaded to the `js-runner-vX.X.X` release on GitHub.
2. After **all** the artifacts are built and uploaded, those artifacts are used to publish to npm in their own steps.
This process is similar to what we do with our binaryen.ml package, but that is packed different due to esy.
Everything added for these npm releases need to be guarded on the "release_created" output for that library, so you'll notice that …
> feat: Add npm releases to workflow

- compiler/grainformat/reformat.re
- compiler/grainformat/walktree.re
- compiler/grainformat/walktree.rei
- compiler/test/formatter_inputs/brace_comments.gr
- compiler/test/formatter_outputs/brace_comments.gr
One trick was simple, use cons instead of appending to an array.  I reverse it in the hope that helps the sort be faster.
Instead of folding over the entire list each time (and skipping) by using recursion I can stop early which speeds up partitions of the AST in the earlier phases when there are lots of non-relevant items in the node list still
> fix(grainfmt): Improve formatter performance

- compiler/grainformat/grainformat.re
The reading in of files with CRLF  line endings that left a stray \r character which caused a syntax error
This fixes that issue.   The file is left as a LF file so we need to fix to output in CRLF (see #940)
> fix(grainfmt): Format CRLF files without error

- stdlib/bytes.gr
- stdlib/bytes.md
I noticed in #947 that the Bytes module was using the outdated syntax, and upon further investigation, it had the same ordering issues that I removed from the Buffer module.
This PR updates the docblock, parameter names, and re-organizes the file. I also formatted the module with grainformat and generated the markdown docs.
Diff is terrible because I reorganized the file 😭
> chore(stdlib): Update docs for Bytes module

- .vscode/setup-ocaml-lsp.js
In vscode-ocaml-platform v1.0.0, they added a configuration option to specify a "custom" template for finding the ocamllsp in your sandbox. Before this, we needed to have a special script that found the absolute path to `grain/compiler` and labeled that as the esy sandbox. However, with this "custom" template, we can actually defer the lookup to `yarn` and our local `esy` command.
I've removed the "vscode" script and the file it executed and then committed a workspace `settings.json` file that implements the custom command that I got working. We need to test this on windows still 😭
cc @cician - Can you try this out in your environments (without a global esy installed)?
> chore(compiler): Update vscode script to use a custom template on non-Windows

- compiler/src/typed/env.re
- compiler/test/suites/records.re
- compiler/test/test-libs/data.gr
Fixes #665
It seems that when we didn't have a filename for a module, we were using it's identifier as a filepath. However, if we raise `Not_found`, the compiler can generally sort out the type you want.
> fix(compiler): Allow modules to re-export imported types containing generics

- .dockerignore
- .github/workflows/docker-publish.yml
- .github/workflows/release.yml
- Dockerfile
- Dockerfile-slim
Closes #1007
Closes #1010 
This PR updates the `docker/build-push-action` GitHub action to v2 (which allows us to publish to DockerHub again) and adds a new `Dockerfile-slim` which provides a minimal environment that can compile Grain programs. The slim version is about 10x smaller!
You can see a [successful run of the GitHub workflow](https://github.com/grain-lang/grain/runs/4243823185?check_suite_focus=true), [images published on DockerHub](https://hub.docker.com/repository/docker/grainlang/grain/tags?page=1&ordering=last_updated&name=oscar-docker), and [on the GitHub Container Registry](https://github.com/grain-lang/grain/pkgs/container/grain). Note that we previously were (accidentally) publishing on GHCR as `grain-lang/grain/grain` rather than `grain-lang/grain`.
In addition to the …
> chore: Add -slim Dockerfile and update Docker workflows

- compiler/src/middle_end/matchcomp.re
- compiler/test/__snapshots__/pattern_matching.eb4334e1.0.snapshot
- compiler/test/suites/pattern_matching.re
Closes #1023 
We were over-optimizing an Explode case—the continuation for when a guard fails needs the bindings that `Explode` introduces.
> fix(compiler): Properly apply bindings when executing match guard

- compiler/test/stdlib/array.test.gr
- stdlib/array.gr
- stdlib/array.md
This PR changes slightly the `Array.rotate` function to accept arrays with any types of elements. This theoretically changes the signature of the function, but I'm assuming the intention form the start was to make it generic.
Additionally calling rotate on an empty array becomes a no-op instead of failing with a runtime error.
> fix(stdlib): Array rotate with generic elements and for empty arrays

- compiler/grainformat/reformat.re
- compiler/src/codegen/compcore.re
- compiler/src/codegen/mashtree.re
- compiler/src/codegen/transl_anf.re
- compiler/src/middle_end/anf_helper.re
- compiler/src/middle_end/anf_helper.rei
- compiler/src/middle_end/anf_utils.re
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/middle_end/linearize.re
- compiler/src/parsing/ast_iterator.re
- compiler/src/parsing/ast_mapper.re
- compiler/src/parsing/asttypes.re
- compiler/src/parsing/parser.dyp
- compiler/src/parsing/well_formedness.re
- compiler/src/typed/translprim.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typed_well_formedness.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/src/typed/typemod.re
- compiler/src/typed/typetexp.re
- compiler/src/typed/typetexp.rei
- compiler/test/suites/foreigns.re
- compiler/test/suites/optimizations.re
This PR adds the ability to specify any UTF-8 string (not just valid Grain identifiers) to use as an external identifier when importing a foreign value or exporting one:
```
@externalName("env.foo")
import foreign wasm foo: Number -> Number from "env"
@externalName("__bar%%!")
export let bar = () => foo(1)
```
This is to allow importing/exporting any foreign value WebAssembly supports.
> feat(compiler): Allow @externalName attribute for foreign names

- compiler/graindoc/docblock.re
- stdlib/array.md
- stdlib/result.md
- stdlib/set.md
Remember when I posted #1069 and said that I thought it was going to be hard to fix? Well, I fixed it.
Closes #1069
@ospencer do you think this is a good semantic title? I also wonder if everything should be resolved to outcome types when they are plucked out of `signature_items` 🤔
> fix(graindoc): Ensure value_description is resolved to outcome before printing

- compiler/test/stdlib/buffer.test.gr
- stdlib/buffer.gr
Fixes #1046 
- `Buffer.addStringSlice` appends bytes from the `slice` var returned from an internal call to `String.slice` instead of the original `string`. This prevents unwanted memory access. I was originally going to guard against negative start indexes in `String.slice`, but then I realized we seem to support this behavior because I saw tests for it.
- `Buffer.addBytesSlice` prevents the usage of out-of-bounds `start` and `length` parameters entirely.
> fix(stdlib): Add bounds checking to Buffer addStringSlice & addBytesSlice

- compiler/test/stdlib/number.test.gr
- stdlib/number.gr
- stdlib/number.md
This adds the `Number.sign(x)` function, similar to the [`Math.sign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign) function in JavaScript. It even accounts for the `-0` case by multiplying the `0` result by the input number (you can see it working in the tests).
Opening as a draft, just to make sure we are good with the implementation.
Ref #1017
> feat(stdlib): Add sign function to Number module

- compiler/src/middle_end/analyze_inline_wasm.re
- compiler/src/middle_end/analyze_inline_wasm.rei
- compiler/src/middle_end/linearize.re
- compiler/src/middle_end/optimize_inline_wasm.re
- compiler/test/__snapshots__/basic_functionality.1d2ec323.0.snapshot
- compiler/test/__snapshots__/basic_functionality.9379df0d.0.snapshot
- compiler/test/__snapshots__/basic_functionality.f58be537.0.snapshot
- compiler/test/__snapshots__/boxes.08fca3f7.0.snapshot
- compiler/test/__snapshots__/boxes.0c59fc4e.0.snapshot
- compiler/test/__snapshots__/boxes.17668725.0.snapshot
- compiler/test/__snapshots__/boxes.2b56febf.0.snapshot
- compiler/test/__snapshots__/boxes.7d564476.0.snapshot
- compiler/test/__snapshots__/boxes.9035923e.0.snapshot
- compiler/test/__snapshots__/boxes.adbe1660.0.snapshot
- compiler/test/__snapshots__/boxes.bc258c1b.0.snapshot
- compiler/test/__snapshots__/boxes.eb81e542.0.snapshot
- compiler/test/__snapshots__/let_mut.3307d5a7.0.snapshot
- compiler/test/__snapshots__/loops.0a25def1.0.snapshot
- compiler/test/__snapshots__/optimizations.ff6d5bfb.0.snapshot
- compiler/test/__snapshots__/stdlib.323e410a.0.snapshot
Right now we only inline some primitives. This PR inlines them all. This also allows us to mostly remove the `inline_wasm` optimization, but we can't completely get rid of it because of `--no-bulk-memory`—we could, but that means we'd need to write the polyfill implementations of `memory_fill` and `memory_copy` in pure wasm in the compiler (which I didn't want to do right now 😅).
> feat(compiler): Inline all primitives

- README.md
- js-runner/LICENSE
- stdlib/LICENSE
Updates 2021 to 2022 in the license and copyright.
> chore: Update copyright & license year

- compiler/grainformat/format.re
- compiler/test/formatter_inputs/application_indenting.gr
- compiler/test/formatter_outputs/application_indenting.gr
- compiler/test/suites/formatter.re
- stdlib/runtime/numberUtils.gr
- stdlib/string.gr
- stdlib/sys/file.gr
Fixes #1087 
Add indenting when adding parens around function application arguments for better layout.
Added tests and reformatted the stdlib with the change
> fix(grainfmt): Indent function application args when adding parens

- compiler/grainc/grainc.re
- compiler/grainformat/grainformat.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
- compiler/test/runner.re
- compiler/test/suites/optimizations.re
Closes #1094
This removes the `--lsp` flag from `Grain_utils.Config` and adds it to grainc directly. This avoids using it as a flag that triggers a full recompile of every dependency.
You can see the drastic difference if you compile the JS version and use `time grain test.gr` while adjusting code with the LSP enabled.
> fix(compiler): Move lsp flag into grainc to remove it as a recompilation flag

- docs/contributor/memory_management.md
This will probably need some revisions based on reviewer feedback, but I wanted to have a go at documenting the Grain memory system, since a lot of details are not recorded anywhere and contributors such as @cician and @jozanza are interacting with low-level runtime code on a regular basis.
> chore: Document memory management in Grain

- compiler/src/typed/oprint.re
Do any of these actually need parens when printed via `oprint`? I'm pretty sure this was just a holdover from ocaml.
> fix(graindoc): Remove special idents from receiving parens

- compiler/grainc/grainc.re
- compiler/graindoc/graindoc.re
- compiler/grainformat/grainformat.re
The process should exit successfully with code 0 upon a successful cmdliner run. Having an explicit `exit(0)` here caused weirdness in some browser hacking I was working on.
> chore: Remove explicit exit 0 in native executables

- stdlib/bytes.gr
Bytes.length was always tagging the size as a Simple Number, so it was failing for sizes over 2GiB.
See also #1072.
> fix(stdlb): Fixed Bytes.length for size over 2GiB.

- compiler/src/parsing/parser_header.re
- compiler/src/utils/string_utils.re
- compiler/test/suites/comments.re
- stdlib/regex.md
Closes #1096
This adds an "indent calculation" during the trimming of Doc comments and it will only trim the start of any line in a Doc comment by the smallest common indentation—this is usually 1 space when writing comments like:
```grain
/**
* Returns the character length of the input string.
*
* @param string: The string to inspect
* @returns The number of characters in the string
*
* @example String.length("Hello world") == 11
*
* @since v0.1.0
*/
```
However, as noted by @cician, and evident in our own Regex docs (regenerated with this PR), sometimes authors want to have additional indentation inside their descriptions, etc. This will ensure we are preserving the indentation that is not shared by the whole Doc comment.
> fix(graindoc): Preserve indentation in Doc comments during trim

- stdlib/buffer.gr
In some cases Buffer.autogrow was making unnecessary intermediate resizes of the buffer. In particular when adding a big chunk of data at once.
> fix(stdlib): Buffer.autogrow was making unnecessary intermediate resizes of the buffer.

- stdlib/string.gr
> fix(stdlib): Fixed length and byteLength for strings over 2GiB.

- compiler/test/stdlib/buffer.test.gr
- stdlib/buffer.gr
This PR changes the semantics of `Buffer#addStringSlice` to align with those of `String#slice`.
Closes #1071.
> fix(stdlib)!: Change Buffer#addStringSlice API

- compiler/src/middle_end/anf_helper.re
We can potentially be a little smarter here and only do this for numbers that get allocated on the heap; it'd save a few incref/decrefs.
> fix(compiler): Apply correct allocation type to numbers

- stdlib/runtime/dataStructures.gr
- stdlib/runtime/gc.gr
- stdlib/runtime/numberUtils.gr
- stdlib/runtime/string.gr
The major thing to notice in this PR is that `runtime/numberUtils.gr` is no longer `--compilation-mode=runtime`. This means that it uses regular allocated Grain memory, which means that string literals, etc. are allowed to be used. Ideally, `malloc.gr`/`gc.gr`/`memory.gr` will be the only files in runtime mode.
> feat(stdlib): Convert runtime printing utils to @unsafe

- compiler/test/stdlib/buffer.test.gr
Buffers can't promise that they're structurally equal given that they don't reveal their underlying `Bytes` instance.
> chore(stdlib): Update tests around Buffer equality

- stdlib/string.gr
I'm opening this draft PR so we can get a sense of the diff when migrating from `@disableGC` to `@unsafe` once the new pointer stack lands along with the `@unsafe` attribute.
> chore(stdlib): migrate string module @disableGC to @unsafe

- stdlib/buffer.gr
This PR simply changes `Buffer.toBytes` to actually always make a copy like stated in its graindoc comment. Returning the underlying instance of Bytes could lead to nasty unexpected bugs.
I'm not sure if we want a way to access the underlying raw Bytes instance or not. It may be handy in some performance critical scenarios. If so, I think it should be a separate function and warn the consumer of the API of risks.
> fix(stdlib): Buffer.toBytes should not expose the raw instance of Bytes used by the buffer.

- stdlib/buffer.gr
- stdlib/bytes.gr
- stdlib/bytes.md
This PR adds a simple function `clear` to the Bytes module and uses it in `Buffer.clear` instead if `Bytes.fill`. This avoids allocating an instance of Int32 on the heap for each call to `Buffer.clear`.
> feat(stdlib): Added Bytes.clear function. Avoid allocation in Buffer.clear

- compiler/src/codegen/transl_anf.re
- compiler/test/__snapshots__/functions.6eacded0.0.snapshot
- compiler/test/suites/functions.re
Closes #1148 (though not in the way that the ticket describes). This PR changes the compilation of functions such that self-references are looked up at runtime via argument #0 (`$self`), rather than a closure variable. In addition to making the closures smaller, this should increase the scope of functions which are garbage-collectible (see #989).
I've implemented this patch in two commits, since the change did not modify any snapshots. The first commit introduces a test case, and the second commit shows the diff on that test case's snapshot to illustrate the change (and show that it actually works).
> feat(compiler): Reduce closure sizes by utilizing `$self` argument when possible

- compiler/grainc/grainc.re
- compiler/graindoc/graindoc.re
- compiler/grainformat/grainformat.re
- compiler/src/parsing/ast_helper.re
- compiler/src/parsing/ast_helper.rei
- compiler/src/parsing/parser.mly
- compiler/src/typed/env.re
- compiler/src/typed/env.rei
- compiler/src/utils/config.re
Following #1151, the build emits a number of warnings related to Cmdliner's [deprecation of the `Term` evaluation interface](https://github.com/dbuenzli/cmdliner/blob/master/CHANGES.md#new-cmd-module-and-deprecation-of-the-term-evaluation-interface) and OCaml 4.12's [widening of warning 16](https://github.com/ocaml/ocaml/pull/9783). This PR makes the necessary changes to fix those warnings.
> chore(compiler): Fix OCaml 4.12.0 and cmdliner warnings

- cli/package.json
- compiler/package.json
- package.json
In this PR, I'm cleaning all the compiler-generated code before we run the compiler build.
This should solve the codesign sigkill that @ospencer was experiencing on the latest MacOS on M1.
I believe what is happening is that we were overwriting the exe but for some reason MacOS didn't see it as a new file but instead a modification to the old file (inode?). If we delete these exe files before we generate them again, it seems to work fine.
I'm also deleting the `.bc.js` files, too, because I can.
> chore(cli): Clean exe and jsoo code before we build compiler

- compiler/test/suites/numbers.re
- stdlib/runtime/numberUtils.gr
Problem was that there was an unused argument in `genDigits`, and Grain "any" types are GC'd. We should consider adding a warning to `@unsafe` when arguments are unused/any types.
> fix(stdlib): Fix float printing in dtoa

- compiler/src/parsing/parser.messages
- compiler/src/parsing/parser.mly
- compiler/test/formatter_inputs/lambda.gr
- compiler/test/formatter_outputs/lambda.gr
- compiler/test/suites/functions.re
- compiler/test/suites/pattern_matching.re
This removes support for newlines before `=>`. This came up while I was trying to work on #1113 with @ospencer. We don't allow newlines before `->`, so menhir got really mad when I switched them to `=>` and Oscar said it would be really hard to resolve.
I started typing out examples of eol before arrow and they looked really terrible:
```grain
let a =
() => 1
```
```grain
match (a) {
x
=> 2
}
```
It seems easiest to just remove support for eol before an arrow. I hope y'all agree.
(Is it a chore? Who knows 🤷 )
> chore(compiler)!: Disallow end-of-line before `=>`

- compiler/src/codegen/comp_utils.re
- compiler/src/codegen/compcore.re
- compiler/src/codegen/transl_anf.re
- compiler/src/linking/link.re
- compiler/src/middle_end/linearize.re
- compiler/src/typed/env.re
- compiler/src/typed/type_utils.re
- compiler/src/typed/types.re
- compiler/test/__snapshots__/basic_functionality.1bf5759c.0.snapshot
- compiler/test/__snapshots__/basic_functionality.1d2ec323.0.snapshot
- compiler/test/__snapshots__/basic_functionality.2f53324c.0.snapshot
- compiler/test/__snapshots__/basic_functionality.3c2ba165.0.snapshot
- compiler/test/__snapshots__/basic_functionality.dbf5d3ff.0.snapshot
- compiler/test/__snapshots__/exports.a2013f43.0.snapshot
- compiler/test/__snapshots__/exports.d0b9a66c.0.snapshot
- compiler/test/__snapshots__/exports.de3bf2b8.0.snapshot
- compiler/test/__snapshots__/functions.6eacded0.0.snapshot
- compiler/test/__snapshots__/imports.2f957040.0.snapshot
- compiler/test/__snapshots__/imports.4ac5b2fd.0.snapshot
- compiler/test/__snapshots__/imports.54ae58d4.0.snapshot
- compiler/test/__snapshots__/imports.59fd966e.0.snapshot
- compiler/test/__snapshots__/imports.644a1413.0.snapshot
- compiler/test/__snapshots__/imports.91b07561.0.snapshot
- compiler/test/__snapshots__/imports.b31f1d0e.0.snapshot
- compiler/test/__snapshots__/imports.cc67676f.0.snapshot
- compiler/test/__snapshots__/imports.daf4add5.0.snapshot
- compiler/test/__snapshots__/imports.dd1aa173.0.snapshot
- compiler/test/__snapshots__/imports.f4cfe044.0.snapshot
- stdlib/sys/file.gr
This PR uses regular `call`s where possible between modules. This should be fairly significant for performance, as direct `call`s are much faster than `call_indirect`s. Additionally, Binaryen can now provide better optimizations after linking.
> feat(compiler): Call known functions across module boundaries

- Dockerfile-slim
Closes #1194 
Tested this locally—works great (more similar to the regular Dockerfile) and is the same size as before.
> chore: Simplify slim docker image with multistage build

- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/esy.lock/opam/re.1.10.4/opam
- compiler/grainc/grainc.re
- compiler/graindoc/graindoc.re
- compiler/grainformat/grainformat.re
- compiler/src/utils/files.re
This is a WIP draft of upgrading our reason-native dependencies to drop the Windows path separator hacks.
There's more work to do and a ton more testing (haven't tried it on Windows yet).
> chore(compiler): Upgrade reason-native dependencies

- compiler/graindoc/docblock.re
- compiler/graindoc/graindoc.re
- compiler/src/diagnostics/comments.re
While working on #972, I found that the singleton used for ordering the comments of a file doesn't work when you try to handle multiple files. It would inject more comments in the map, which could cause bugs or throw errors on multiple module definitions, etc.
This switches the implementation to using a first-class module `OrderedComments` which is then passed to the functions that operate on comments.
> fix(graindoc): Avoid singletons when building ordered comments

- stdlib/runtime/malloc.gr
- stdlib/runtime/wasi.gr
This updates some docs that don't match the currently supported graindoc format.
> chore(stdlib): Correct some docs for latest graindoc format

- compiler/graindoc/graindoc.re
- compiler/src/utils/filepath.re
This is a refactor that I wanted to implement to share input/output arguments between our different CLI executables. This is important because I'll be implementing directory support that will be shared between graindoc and grainformat.
What do y'all think of this approach?
> chore(graindoc): Implement input & output args with a Filepath module

- compiler/src/codegen/compcore.re
- compiler/src/codegen/optimize_mod.re
- compiler/src/codegen/optimize_mod.rei
- compiler/src/linking/link.re
This is a translation of Binaryen's default optimization passes. By not relying on the defaults, we can adjust this to speed up compilation times. The primary reason for doing a 1-to-1 translation was to ensure that everything was behaving correctly and can be seen by the snapshots not changing at all.
> chore(compiler): Translate default optimization passes from binaryen

- compiler/grainformat/format.re
- compiler/grainformat/grainformat.re
- compiler/grainformat/res_doc.re
- compiler/grainformat/res_doc.rei
- compiler/grainformat/res_minibuffer.re
- compiler/grainformat/res_minibuffer.rei
- compiler/src/utils/fs_access.re
@marcusroberts These are some refactors that I think we should make to the formatter code. It really cuts down on the different code paths and mutable values. `Grain_utils.Fs_access` isn't the *perfect* place for the EOL utils, but I think it's fine for now.
> Refactor suggestions

- compiler/src/typed/env.re
- compiler/src/typed/env.rei
- compiler/src/typed/typetexp.re
- compiler/test/suites/records.re
> fix(compiler): Supply correct error for unbound record labels

- compiler/test/stdlib/sys.process.test.gr
It's not very cross-platform (crashes on Windows) and we probably shouldn't raise random signals.
> chore: Don't raise signals in tests

- stdlib/map.gr
In #1088, I noticed that `Map.forEach` allowed any return value in the iterator function. This explicitly annotates the return type as `Void` to ensure the signature is correct.
> fix(stdlib)!: Add explicit void return type on Map.forEach

- .gitattributes
- .github/workflows/ci.yml
- compiler/src/utils/hacks.js
This implements some missing JS externals for Windows related to `Unix.readdir`. I didn't realize they had separate externals when I first implemented them. I also needed to get one fix to the Unix external.
This also enables the JS tests on Windows so we catch things like this before they land. One change that needed to happen to make them work was to ensure our snapshots always have `LF` line endings (because JSOO doesn't actually handle `\r\n` translations for `open_in` on Windows.
> chore(compiler): Implement JS externals for Windows readdir

- compiler/dune-project
These don't actually do anything since we exclusively use esy, and (for that reason) we are very bad at updating them. We should just delete them. The only thing dune needs for the dune-project stanzas is the name, but a description is nice too.
> chore(compiler): Remove depends from dune-project stanzas

- compiler/graindoc/docblock.re
- compiler/src/typed/printtyp.re
- compiler/src/typed/printtyp.rei
This moves the type-to-string utilities that I wrote for graindoc into Printtyp (where they really should be). I noticed that #1131 copy-pasted my utilities. Instead of duplicating this logic, we should be putting them in the correct location.
I also experimented with `string_of_type_sch` and `string_of_type_scheme` and I **think** `string_of_type_sch` does the same thing as my weird `string_of_type_expr` function. I'll have a more thorough testing of that once directory support for graindoc is finished.
> chore(compiler): Move type string printing into Printtyp module

- compiler/grainc/grainc.re
- compiler/graindoc/graindoc.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
While doing some Windows debugging, I noticed that we don't actually use `Grain_utils.Config.base_path` anywhere anymore. I believe there was a change where we made things relative to the file being compiled, and this was probably just leftover.
> chore(compiler): Remove Config.base_path entirely

- compiler/src/diagnostics/modules.re
- compiler/src/language_server/completion.re
- compiler/src/language_server/hover.re
While working on a fix for type printing, I ran into an issue where the LSP wasn't printing types, records, etc as nicely as it could. This applies some fixes to make it nicer.
One thing that I still didn't solve is that `enum` declarations are being printed as `type`. I'm wondering if they are being marked as abstract somehow (cc @ospencer ?)
> Handle more data types and fix printing

- compiler/src/typed/oprint.re
Fixes #1236
This actually implements the prefix when printing abstract types or really any type definition.
Is the `Otyp_constr` correct?
> fix(graindoc): Fix type printing for types and abstract types

- compiler/src/utils/wasm_utils.re
Previously we relied on OCaml's `input` to read the custom section from a module. If all the bytes were not read, we skipped the section entirely. This swaps to `really_input` to ensure we read the entire section.
> fix(compiler): Read custom sections in full

- compiler/graindoc/docblock.re
- stdlib/map.gr
- stdlib/map.md
We previously did a lookup on the types in the module's signature, but that type is the original type rather than what the module is trying to expose. This change uses what's defined in the signature.
> fix(graindoc): Use value_descriptions and type_declarations defined by the module signature

- compiler/src/language_server/completion.re
- compiler/src/utils/string_utils.re
I found that the LSP was crashing a lot because it was trying to do operations on strings that were outside of the string boundaries. @marcusroberts we have the `String_utils.slice` utility so you should never be using `String.sub`. And I added a `char_at` utility that returns an option.
> Remove fallible string operations in LSP

- compiler/src/language_server/hover.re
In talking with @ospencer about what the purpose of "grain-type" syntax in our vscode extension, he helped me notice that the syntax highlighting on our hover tooltips was wrong. We need to use `grain-type` syntax for any type signatures (which all hover items should be).
> Fix hover highlighting by using the correct language

- compiler/src/language_server/message.re
- compiler/src/language_server/protocol.re
- compiler/src/language_server/protocol.rei
I noticed that the restart was crashing because it couldn't parse params on the request.
> Fix shutdown/exit by making request params optional

- package.json
By ending our passthrough scripts with `--`, we should only need a single `--` to pass arguments through, such as `npm test -- -u`.
> chore: Avoid need for double `--` for argument passthrough

- compiler/src/language_server/completion.re
- compiler/src/language_server/protocol.re
It turns out that derivers don't know about each other, so we have to override the yojson serde functions if we want to convert to/from integer values.
Good catch @marcusroberts
> Fix enum serde by providing custom yojson functions

- cli/package.json
- stdlib/package.json
I'm not exactly sure why single-ticks don't work on Windows when inside an npm "script", but they don't. They work when you run the command manually, which is doubly weird.
Anyway, this uses escaped double-tick quotes so deleting files works on Windows.
> chore: Use Windows-safe glob strings

- compiler/src/linking/link.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
We previously tried to resolve the location of the wasi polyfill relative to the Grain program being compiled, which is incorrect—it's relative to the directory where `grainc` is invoked.
Closes #1257
> fix(compiler): Refactor WASI polyfill resolution

- compiler/src/codegen/compcore.re
- compiler/src/codegen/emitmod.re
- compiler/src/compile.re
- compiler/src/linking/link.re
- compiler/src/typed/env.re
- compiler/src/typed/module_resolution.re
- compiler/src/typed/module_resolution.rei
- compiler/src/utils/filepath.re
- compiler/src/utils/hacks.js
- compiler/test/TestFramework.re
The JS version of the compiler kept crashing because it was unable to locate the stdlib. This was due to JSOO reporting itself as "Cygwin" instead of "Win32". We've pushed for a lot of upstream changes in `Fp` so we use the correct separators on Windows, but that doesn't happen if it thinks it is running in Cygwin.
This hack (placed in `Grain_utils` so pretty much everything will get it applied) will swap us back to reporting `Win32` and make the all our tools work.
> fix(compiler): Report Win32 instead of Cygwin in JS compiler

- .github/workflows/ci.yml
- .github/workflows/release.yml
The esy cache import seems to fail on Windows more than I'd like. Let's just make this step fallible in our workflows so it doesn't crash the run (it'll just take longer).
> chore(ci): Allow esy cache import to fail without killing run

- stdlib/sys/file.gr
- stdlib/sys/process.gr
- stdlib/sys/random.gr
- stdlib/sys/time.gr
Closes #1146 as this removes the sys functions' self-references, which allows them to be dropped from the module if unused.
> feat(compiler): Convert Sys libraries to @unsafe

- compiler/src/parsing/ast_helper.re
This problem is supposed to be solved by Menhir's `$sloc`, but that only works in the current rule. We'd essentially need to inline all of the right side of binops to get the location reporting right, but this is much simpler.
Closes #1129
> fix(compiler): Report binop locations properly

- stdlib/queue.gr
- stdlib/queue.md
Now that we show the abstract type, we should show the data type in the docs.
> chore(stdlib): Show data type on Queue module docs

- cli/bin/exec.js
- cli/bin/grain.js
- compiler/graindoc/graindoc.re
- compiler/grainformat/dune
- compiler/grainformat/grainformat.re
- stdlib/regex.gr
Closes #973
This adds directory input & output support for grain format. The implementation is very close to the graindoc implementation and they can probably be consolidated in the future.
The big breaking changes to support this are:
1. We no longer have an `--in-place` flag. Instead, you need to specify the same file as the "output", e.g. `grain format test.gr -o test.gr`
2. We no longer support input on stdin. The stdin support was primarily to support the old way our vscode plugin operated, so this shouldn't be an issue. (Side note: we should theoretically be able to support stdin, but ppx_deriving_cmdliner crashes when we try to make a positional argument optional 🤷 https://github.com/hammerlab/ppx_deriving_cmdliner/issues/51 )
I ran the directory formatting against the stdlib and …
> feat(grainfmt): Allow directory input & output

- compiler/src/typed/typedtreeIter.re
- compiler/src/typed/typedtreeMap.re
Found that we were missing these while smoke testing the new LSP version.
> fix(compiler): Iterate over guard clauses in typedTreeIter/typedTreeMap

- compiler/grainformat/format.re
- compiler/test/formatter_inputs/enum_long.gr
- compiler/test/formatter_outputs/enum_long.gr
Fixes the problems with comments when we had multiple data declarations in a top level statement
> fix(compiler): fix formatter multiple data bug

- cli/bin/grain.js
- cli/bin/run.js
- compiler/test/runner.re
This removes the `--graceful`/`-g` flag and removes the "graceful" exit behavior. I don't actually think this is necessary/useful and it just makes boilerplate more cluttered.
> chore(cli)!: Remove graceful flag & behavior

- compiler/graindoc/docblock.re
- compiler/graindoc/graindoc.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/src/typed/typemod.re
The exports refactor & bug fixes caused some of my bad code to break in graindoc. Since no new bindings are created in scope for re-exports, I can't use `Env.find_value` to find the locations anymore. @ospencer walked me through the better way to do this, but I need help to finish the value lookup (see TODO in diff).
> fix(graindoc): Improve location lookup so re-exports do not crash it

- compiler/src/language_server/hover.re
- compiler/src/language_server/lenses.re
- compiler/src/language_server/sourcetree.re
This reports the original type of an identifier rather than the instanced type. For example, before this change, the LSP would report the type of `print` as `_weak -> Void`, and if hovering `print` in `print(5)`, `Number -> Void`, when it should show `a -> Void` as the instanced is a bit misleading.
The instanced type is correct for other expressions.
A good example of this is `Map.make`. Creating one without setting any values should show the instanced type as being weak as you haven't set any values to define some concrete types:
But hovering over just `make` should show the original type, since hey, you're probably going to make another map some day and you'd be pretty confused if the tool told you it only makes weak maps.
And the same deal for non-weak maps:
> fix(lsp): Report non-instanced type for identifiers

- stdlib/bytes.gr
We don't need these cuz `@unsafe` 🤙
> chore(stdlib): Remove unused mut in bytes module

- compiler/test/suites/numbers.re
Closes #1081
I believe this was fixed with the thiccnum implementation, but this adds a direct regression test from the issue.
> chore(compiler): Add boxed number overflow regression test

- cli/bin/grain.js
This builds upon #1285 and needs #1290 
Since #1290 ensures all versions are the same across the monorepo, we no longer need to output different versions for the CLI & compiler.
Simplifying the output so it only prints the version allows us to run `grain doc stdlib -o stdlib --current-version=$(grain -v)` in CI. See https://github.com/grain-lang/grain-lang.org/pull/289
> chore(cli)!: Simplify version output

- release-please-config.json
I was writing docs for the List stdlib module, and I found a really old issue number linked into our release notes. I believe the new version of release-please isn't finding the correct release PR, so we should try to force it with this.
> fix(ci): Add a last-release-sha to release-please

- stdlib/list.gr
- stdlib/list.md
While prepping for release, I noticed that the List module didn't have any graindoc added to it. With the automated docs updates on the website, this would wipe out our List documentation.
I took most of this from the Array module and updated it for the differences. I also noticed some inconsistencies in Array that I'll PR after this.
Please thoroughly review the docs for clarity and consistency (especially with our other docs).
> chore(stdlib): Add docs to List module

- compiler/src/typed/oprint.re
- stdlib/pervasives.md
- stdlib/runtime/numbers.md
While working on the Pervasives docs, I noticed that we printed infix operators like `( + )` but all our website docs were written as `(+)`. So this removes the extra spaces around it.
> fix(graindoc): Remove spaces between parens and infix idents

- compiler/src/typed/printtyp.re
- stdlib/pervasives.md
- stdlib/runtime/numbers.md
While working on the Pervasives docs, I noticed that infix operator idents weren't being printed with parens. This adds similar logic to `Oprint.value_ident` for handling these idents.
> fix(graindoc): Add parens around infix operators in titles

- cli/package.json
This makes it so our NEAR smoketest always runs in release mode. We need to do this because the smoketest is testing that binaryen optimizations don't produce wasm that is unsupported by NEAR.
> chore(cli): Always run NEAR smoketest in release mode

- stdlib/list.gr
- stdlib/list.md
While reviewing the docs against the website, I noticed that a couple functions in List didn't have return docs.
> chore(stdlib): Add returns docs to some List functions

- stdlib/map.gr
- stdlib/map.md
This fixes some Map docs that were broken by an extra newline inserted by grainformat.
> chore(stdlib): Correct Map docs broken by grainformat

- stdlib/list.gr
- stdlib/list.md
Found this while reviewing doc changes against the website. `List.forEach` and `List.forEachi` signatures were wrong.
> fix(stdlib)!: Ensure Void return for forEach functions in List module

- compiler/test/__snapshots__/stdlib.24cb9bbf.0.snapshot
- compiler/test/__snapshots__/stdlib.5fe88631.0.snapshot
- compiler/test/__snapshots__/stdlib.648f406e.0.snapshot
- compiler/test/__snapshots__/stdlib.6bf88430.0.snapshot
- compiler/test/__snapshots__/stdlib.6de47be2.0.snapshot
- compiler/test/__snapshots__/stdlib.8300ad7c.0.snapshot
- compiler/test/__snapshots__/stdlib.91a94037.0.snapshot
- compiler/test/__snapshots__/stdlib.a70e79ca.0.snapshot
- compiler/test/__snapshots__/stdlib.d28dee65.0.snapshot
- compiler/test/__snapshots__/stdlib.d4faa5bf.0.snapshot
- compiler/test/__snapshots__/stdlib.e306600a.0.snapshot
- compiler/test/__snapshots__/stdlib.e6349872.0.snapshot
- compiler/test/stdlib/list.test.gr
- stdlib/list.gr
- stdlib/list.md
In #1298, @ospencer said we should remove `List.sum`. This removes the function before 0.5 since it is a breaking change.
> chore(stdlib)!: Remove `sum` function from the List module

- release-please-config.json
This was used to get us through the upgrade of release-please, but it should be removed now that 0.5.0 is released.
> chore(ci): Remove the last-release-sha from release-please

- compiler/src/typed/cmi_format.re
I was able to reproduce with a hex editor, and with this change the file is recompiled as expected.
> fix(compiler): Properly handle corrupted CMIs

- compiler/src/parsing/wrapped_lexer.re
- compiler/test/__snapshots__/pattern_matching.e17bcd61.0.snapshot
- compiler/test/suites/pattern_matching.re
This PR allows
```
match (true) {
true
| false => print("ok")
}
```
in addition to
```
match (true) {
true |
false => print("ok")
}
```
> feat(compiler): Allow newline in or-patterns

- compiler/src/language_server/hover.re
When we don't have a successful compilation to check, this will tell vscode "I heard you but I don't have an answer for you" so it doesn't think it's waiting on us and display a "Loading..." message.
> fix(lsp): Always respond to hover request

- compiler/src/typed/typetexp.re
- compiler/test/suites/types.re
> fix(compiler): Correct error message for unbound type variables

- compiler/src/typed/oprint.re
This was crashing the LSP when I wrote `type Tup = (String, String)`. Also noticed it didn't print singleton tuples correctly.
> fix(compiler): Support printing tuple types in oprint

- compiler/src/formatting/format.re
- compiler/test/formatter_inputs/patterns.gr
- compiler/test/formatter_outputs/patterns.gr
- compiler/test/suites/formatter.re
The formatter now correctly formats Or and Alias patterns.
@ospencer and @phated  notice the second example from the blog has the OR formatted onto a single line as it fits.  
This follows the formatter rules, but may not be best style.   We could look to force a new line for an Or operator applied to lists?
> fix(grainfmt): Support PPatOr and PPatAlias

- compiler/src/parsing/parser.mly
- compiler/test/__snapshots__/basic_functionality.d124f931.0.snapshot
- compiler/test/suites/basic_functionality.re
Closes #1335 
When compiled in release mode, the resulting module is 51 bytes 😄
> feat(compiler): Allow compilation of empty programs

- .github/workflows/ci.yml
- stdlib/bigint.md
- stdlib/buffer.gr
- stdlib/buffer.md
- stdlib/bytes.md
- stdlib/int32.md
- stdlib/int64.md
- stdlib/map.md
- stdlib/random.md
- stdlib/set.md
- stdlib/sys/random.md
This adds a step to the CI workflow that runs graindoc and grainformat against the stdlib. This is really just another linting step but it needs to happen after we know we have a working grain binary.
As you can see in the following commits, we are very bad at updating things 😛 
I have been planning to add this, but #1337 reminded me we needed it when @ospencer accepted my change but didn't regen the docs.
> chore(ci): Add phase for checking stdlib docs & formatting

- compiler/src/codegen/compcore.re
- compiler/test/__snapshots__/exports.40fa3869.0.snapshot
- compiler/test/runner.re
- compiler/test/suites/exports.re
This PR allows you to manually define a function called `_start` when using the `--use-start-section` flag.
> fix(compiler): Allow defining _start when using --use-start-section

- compiler/src/utils/wasm_utils.re
- compiler/src/utils/wasm_utils.rei
- compiler/test/runner.re
Streams in OCaml have been deprecated. This also cleans up a long-time comment about an issue with streams, so that's a plus.
> chore(compiler): Remove deprecated use of Streams

- compiler/src/codegen/transl_anf.re
- compiler/src/middle_end/anf_utils.re
- compiler/src/middle_end/anf_utils.rei
- Adds a new record type, stack_size to anf_utils.re && rei
- Gets unpacked + ported to a Mashtree.stack_size in codegen
- decided to not have Mashtree.stack_size use Anf_utils.stack_size due to not wanting to use `[@derive sexp]` in the middle end
I don't know if there is a better convention for testing small things/unit testing here, but `npm run compiler test` gave me the good ol' thumbs up.
Closes #1155
> chore(compiler): Port Anf_utils.anf_count_vars to use record

- compiler/test/suites/numbers.re
- stdlib/runtime/numbers.gr
> fix(stdlib): Correctly promote numbers to bigints when left-shifting

- compiler/src/typed/oprint.re
Fixes #1366 
Also fixes the LSP problem (and this shows the output of the printer):
@phated we don't have any graindoc tests right?
> fix(graindoc): Enable printing of arrow types

- compiler/dune-workspace
- compiler/src/formatting/comment_utils.re
- compiler/src/formatting/format.re
- compiler/src/language_server/hover.re
- compiler/src/linking/link.re
- compiler/src/typed/dependency_graph.re
- compiler/src/typed/env.re
Newer versions of OCaml have a warning for this, so this just applies labels to unlabeled arguments.
> chore(compiler): Always use labels when calling functions

- compiler/src/parsing/ast_helper.re
This will help the formatter understand where lists are in the source program.
> fix(compiler): Apply list location to outer node

- compiler/test/stdlib/buffer.test.gr
- stdlib/buffer.gr
Fixes #1382, prevents `Buffer.addBuffer` from throwing an exception when adding an empty buffer.
> fix(stdlib): Prevent addBytesSlice throwing error on empty buffer

- compiler/src/formatting/format.re
- compiler/test/formatter_inputs/constraints.gr
- compiler/test/formatter_outputs/constraints.gr
- compiler/test/suites/formatter.re
Use only the comments applicable for the constraint not the whole expression
Fixes #1378
> fix(grainfmt): Use only the correct comments for constraints

- .github/workflows/docker-publish.yml
- Dockerfile
- Dockerfile-slim
This PR adds support for the linux/arm64 arch in our published Docker images. Since GitHub actions doesn't yet support ARM, this is done by booting up an AWS Graviton instance and using it as a remote builder to handle the arm64 part of the image build. The Graviton instance is set to automatically stop when it detects that builds are complete.
Additionally, `esy` does not yet have linux/arm64 binaries, so we use a workaround in the Dockerfiles to use one that I built. When `esy` ships a release with linux/arm64 binaries, we can remove the workaround.
If you have an arm64 linux machine (or a Mac with an M1 processor) you can try out the image with
```sh
docker run -it ghcr.io/grain-lang/grain:oscar-docker-arm64
```
or
```sh
docker run -it ghcr.io/grain-lang/grain:oscar-docker-arm64-slim …
```
> feat: Arm64 docker builds

- compiler/test/stdlib/marshal.test.gr
- compiler/test/suites/stdlib.re
- stdlib/marshal.gr
- stdlib/marshal.md
This PR implements serialization and deserialization of Grain values, useful for a variety of purposes like transmission across a network or storing values on disk to use later.
> feat(stdlib): Marshal

- compiler/test/stdlib/immutablepriorityqueue.test.gr
- compiler/test/stdlib/priorityqueue.test.gr
- compiler/test/suites/stdlib.re
- stdlib/immutablepriorityqueue.gr
- stdlib/immutablepriorityqueue.md
- stdlib/priorityqueue.gr
- stdlib/priorityqueue.md
As the name suggests, this PR is for implementation of both mutable and immutable priority queues. The mutable priority queue is implemented as a binary heap, and the immutable priority queue is implemented as a skew binomial queue as described in the paper "Optimal Purely Functional Priority Queues" by Chris Okasaki. (O(1) insertions and peeking, O(log(n)) deletions)
This closes #1383 . The API for an immutable priority queue was not really discussed in this issue, but I made one that seemed reasonable to me; let me know if something should be changed:
- `make(comp: (a, a) -> Number) -> ImmutablePriorityQueue<a>`: creates a new PQ with a comparator for determining priority
- `size(pq) -> Number`
- `isEmpty(pq) -> Bool`
- `push(val: a, pq) -> ImmutablePriorityQueue<a>`: creates a new …
> feat(stdlib): Implement mutable/immutable priority queues

- compiler/src/formatting/format.re
- compiler/test/formatter_inputs/only_comments.gr
- compiler/test/formatter_outputs/only_comments.gr
- compiler/test/suites/formatter.re
Still format the comments correctly.
> fix(grainfmt): Handle source files with no code, only comments

- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/esy.lock/opam/dune.2.9.3/opam
- compiler/esy.lock/opam/sexplib.v0.15.1/opam
I was discussing with @ospencer about Binaryen versions and he reminded me that Binaryen 108 allowed us to disable the building of their "tools". This update should reduce build times a fair bit.
> chore(compiler): Upgrade to Binaryen 108

- compiler/src/utils/config.re
When trying to use --help for grainc, this makes the docs printer for enum look for a None value on the enum list, which yields an Invalid_argument exception, crashing the grainc executable.
> fix(utils): Use option converter instead of Some

- compiler/src/formatting/comment_utils.re
- compiler/src/formatting/format.re
- compiler/test/formatter_inputs/comments.gr
- compiler/test/formatter_outputs/comments.gr
> fix(grainfmt): Stop adding an extra line after block comments

- compiler/src/formatting/format.re
- compiler/test/formatter_inputs/data_docs.gr
- compiler/test/formatter_outputs/data_docs.gr
- compiler/test/suites/formatter.re
Fixes #1317 
Formatter was ignoring comments between top level data declarations
Fixed and tests added
> fix(grainfmt): Write comments found between top level data statements

- stdlib/array.gr
- stdlib/array.md
Updated the grains docs for array.gr to add examples for length,get,set,append,concat methods for array
> chore(stdlib): Add examples to the Array module

- compiler/test/stdlib/regex.test.gr
- stdlib/regex.gr
> fix(stdlib): Fix anchoring behavior in Regex.replaceAll

- compiler/src/typed/type_utils.re
- compiler/test/suites/types.re
- compiler/test/test-libs/funcAliasExport.gr
Fixes #1424 
Thanks @alex-snezhko for the report!
> fix(compiler): Fully expand types when finding concrete representation

- compiler/src/codegen/compcore.re
- compiler/src/codegen/mashtree.re
- compiler/src/middle_end/analyze_purity.re
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/parsing/parsetree.re
- compiler/src/typed/translprim.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/test/__snapshots__/arrays.0f9e7d37.0.snapshot
- compiler/test/__snapshots__/arrays.28fcc534.0.snapshot
- compiler/test/__snapshots__/arrays.4c8c9f91.0.snapshot
- compiler/test/__snapshots__/arrays.6eac4e1f.0.snapshot
- compiler/test/__snapshots__/arrays.74d79181.0.snapshot
- compiler/test/__snapshots__/basic_functionality.2bcc447b.0.snapshot
- compiler/test/__snapshots__/basic_functionality.704872bc.0.snapshot
- stdlib/runtime/exception.gr
- stdlib/runtime/exception.md
- stdlib/runtime/malloc.gr
This is a bit of a fun bug I discovered while working on refactoring constructors. When an `OutOfMemory` is thrown, if any memory is allocated during the chain of exception printer calls, we wind up in an infinite loop: we're out of memory, so trying to allocate something to report that we're out of memory ends up entering the out of memory flow again.
This PR adds `Exception.panic` in the runtime to print a string and immediately hit `unreachable`, and changes the implementation of `morecore` to immediately panic when out of memory instead of following the normal exception handling logic which could potentially try to allocate memory.
This seemed like a reasonable approach to me, since (in the future) users shouldn't be allowed to catch an `OutOfMemory` error.
I didn't consider this a …
> fix(compiler): Panic immediately when out of memory

- compiler/src/formatting/format.re
- compiler/test/formatter_inputs/arrays.gr
- compiler/test/formatter_outputs/arrays.gr
Fixes #1461
Handle expressions inside array accessors as groups so they break properly
> fix(grainfmt): Group expressions inside array accessors

- compiler/test/stdlib/immutablemap.test.gr
- compiler/test/stdlib/immutableset.test.gr
- compiler/test/suites/stdlib.re
- stdlib/immutablemap.gr
- stdlib/immutablemap.md
- stdlib/immutableset.gr
- stdlib/immutableset.md
- stdlib/set.gr
I figured I'd include both maps and sets in one PR since their implementation is almost identical. They are both implemented as size-balanced BSTs, following "Implementing Sets Efficiently in a Functional Language" by Stephen Adams. API for these is as was discussed in #1403
> feat(stdlib): Implement immutable map and immutable set

- compiler/src/formatting/format.re
- compiler/test/formatter_inputs/chained.gr
- compiler/test/formatter_inputs/lets.gr
- compiler/test/formatter_outputs/chained.gr
- compiler/test/formatter_outputs/lets.gr
- compiler/test/suites/formatter.re
- stdlib/regex.gr
- stdlib/runtime/compare.gr
- stdlib/runtime/equal.gr
- stdlib/runtime/gc.gr
- stdlib/runtime/string.gr
Fixed #1454 
This formats chained value bindings properly so that they now break over lines if over the width or end in line comments.
It does change how we display chained functions, I think it's more consistent now but let me know what you think
> fix(grainfmt): Handle chained value bindings properly

- compiler/test/stdlib/immutablepriorityqueue.test.gr
- stdlib/immutablepriorityqueue.gr
- stdlib/immutablepriorityqueue.md
- stdlib/queue.gr
- stdlib/queue.md
- stdlib/stack.gr
- stdlib/stack.md
As suggested in https://github.com/grain-lang/grain/pull/1414#discussion_r1001171918, immutable data structures should have an `empty` constant instead of a `make()` function where possible. This PR extends this idea to the remaining immutable data structures (Stack, Queue, Immutable Priority Queue).
> feat(stdlib): Added `empty` constant to immutable data structures

- .github/workflows/ci.yml
- .github/workflows/docker-publish.yml
- .github/workflows/release.yml
This pins ubuntu to 20.04 instead of latest. It seems that GitHub is slowly rolling out 22.04 as "latest" and that caused CI to fail in #1457 
We would need a newer OCaml to support this new version of Ubuntu (similar to our problem with newer GCC on Fedora) but we can't upgrade due to breaking Windows static linking.
> chore(ci): Lock ubuntu to 20.04

- stdlib/array.gr
- stdlib/array.md
- stdlib/list.gr
Improves `Array.flatMap` performance addressing #458. Also small performance upgrade for `every` and `some` for `Array` and `List`, as I noticed that in their current state they would always traverse the entire collection even after a suitable match/counterexample was found.
> feat(stdlib): Improve perf for array flatMap, array & list some & every

- compiler/src/typed/typecore.re
- compiler/test/suites/pattern_matching.re
Fixes #1453.
New warnings with the fix:
> fix(compiler): Perform partial match checking on let-binds

- compiler/src/language_server/code_file.re
- compiler/src/language_server/protocol.re
- compiler/src/language_server/protocol.rei
While looking into #1485, I noticed that the reporting of a missing file was being shown on the line & col of the top-level file we were compiling. This lead me down a rabbit-hole where I found that all errors were being surfaced within the file you were editing (which is very wrong).
This PR changes the error surfacing logic of the LSP to check to see if the error matches the file being compiled. If it matches, the error is surfaced normally; however, if the filenames don't match, we set an error on 0,0 that says which file failed to compile and add its error message to the `related_information` list. This will show "problems" that link to the correct location in the source.
Here's an example for a missing module once #1485 lands:
> fix(grainlsp): Properly surface errors in other files

- compiler/src/parsing/driver.re
- compiler/src/parsing/driver.rei
- compiler/src/typed/module_resolution.re
- compiler/test/input/brokenImports/broken.gr
- compiler/test/input/brokenImports/main.gr
- compiler/test/runner.re
- compiler/test/suites/imports.re
Fixes #1480. Additionally, this PR modifies the missing module error message to contain the correct source locations. For example, given the following files:
`tst.gr`:
```grain
import Number from "./numberr"
print(Number.min(2, 3))
```
`numberr.gr`:
```grain
import Number from "number"
import Foo from "foo" // <- does not exist
export let min = Number.min
```
The following error is reported:
```
λ grain git:(philip/file-missing-import) > grain tst.gr
File "././numberr.gr", line 2, characters 16-21:
Error: Missing file for module foo
```
> fix(compiler): Raise appropriate exception when modules are missing during dependency graph construction

- stdlib/array.gr
These didn't get cleaned up when #793 was completed. I noticed them in #1494
> chore(stdlib): Re-enable type annotations in Array module

- compiler/src/parsing/parser.messages
- compiler/src/parsing/parser.mly
- compiler/test/suites/parsing.re
Fixes #1473.
The precedence of `>>` was being parsed as having the precedence of `>`. `>>` is lexed as two `>` characters so that they don't interfere with type arguments.
> fix(compiler): Fix precedence of >>

- compiler/src/formatting/format.re
- compiler/test/formatter_inputs/comments.gr
- compiler/test/formatter_outputs/comments.gr
Fixes #1445
As we can't tell from the AST if a trailing comment is inside or outside the parens, we always render it inside
> fix(grainfmt): Handle comment in or near if conditionals better

- compiler/graindoc/docblock.re
- compiler/src/diagnostics/comments.re
- compiler/src/utils/markdown.re
- stdlib/array.gr
- stdlib/array.md
- stdlib/buffer.gr
- stdlib/buffer.md
- stdlib/bytes.gr
- stdlib/bytes.md
- stdlib/char.gr
- stdlib/char.md
- stdlib/immutablepriorityqueue.gr
- stdlib/int32.gr
- stdlib/int32.md
- stdlib/int64.gr
- stdlib/int64.md
- stdlib/list.gr
- stdlib/list.md
- stdlib/number.gr
- stdlib/number.md
- stdlib/option.gr
- stdlib/option.md
- stdlib/pervasives.gr
- stdlib/pervasives.md
- stdlib/result.gr
- stdlib/result.md
Closes #767 
This adds a `@throws` attribute to graindoc. This is a draft because we need to figure out some design...
Currently, the "exception name" is optional; however, the generated table looks really weird without an exception name. Should we make this required?
Things look good with the "exception name", but do we want to represent the entire pattern (like you'd match on)? Or just the name of the exception?
I also started adding the attributes to the stdlib and it felt better to document separate exceptional cases individually, even if they are throwing the same exception.
Please take a look at this and give me some feedback so I can wrap up this feature. 🙏
> feat(graindoc): Add attribute for exceptions that may be thrown

- compiler/src/formatting/format.re
- compiler/test/formatter_inputs/comments.gr
- compiler/test/formatter_outputs/comments.gr
Fixes #983 
Use the new iterator to format function arguments in function application
> fix(grainfmt): Maintain comments in function arguments

- cli/bin/grain.js
There appears to be a problem we've exposed in the latest release in regards to stack overflows when compiling some programs. This is a temporary fix until we can roll out a full refactor. See https://github.com/grain-lang/grain/issues/1530 for details.
> fix(compiler): Increase JS stack size

- compiler/src/codegen/optimize_mod.re
- compiler/src/middle_end/linearize.re
- compiler/src/parsing/well_formedness.re
- compiler/src/typed/env.re
- compiler/src/typed/parmatch.re
- compiler/src/typed/subst.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typedecl.re
- compiler/src/typed/typedtreeIter.re
- compiler/src/typed/typetexp.re
- compiler/src/utils/warnings.re
- js-runner/src/core/grain-module.js
- stdlib/array.gr
- stdlib/runtime/unsafe/printWasm.gr
Closes #1499.
This pr converts all `FIXME` comments in the code base to the standardized `TODO format. 
I had to open some new issues for these if anyone wants to add some more context to any of the issues it would probably be helpful for anyone looking to take them on in the future.
#1511 - Is this what this is refering to https://docs.mirage.io/ocaml/Untypeast/index.html?
#1510 
#1509 
#1508 
#1507 
#1506 
#1505 
#1504 
#1503 
#1502 
#1501 - I do not know if I understood this issue properly
#1500
> chore: Convert FIXME comments to TODOs

- compiler/test/stdlib/immutablearray.test.gr
- compiler/test/suites/stdlib.re
- stdlib/immutablearray.gr
- stdlib/immutablearray.md
An efficient immutable array implementation based off of Elm's Array. For the most part the API is the same as Array with a few exceptions to fit in with immutability.
> feat(stdlib): Immutable array

- compiler/src/utils/literals.re
- compiler/test/__snapshots__/basic_functionality.27a7e2f7.0.snapshot
- compiler/test/__snapshots__/basic_functionality.2cb30a54.0.snapshot
- compiler/test/suites/basic_functionality.re
This makes `0xffff_ffff_ffff_ffff` parse (correctly) as 18446744073709551615 and `-0xffff_ffff_ffff_ffff` as -18446744073709551615. Shoutout to @alex-snezhko for discovering this one.
> fix(compiler): Properly parse large hex numbers

- .github/CODEOWNERS
- .vscode/settings.json
- docs/contributor/commits_pull_requests_and_merging.md
Closes #976
This introduces a breaking change to our approval process (and thus requires approval from the entire core team). We want to switch to using a CODEOWNERS file and only require one approval from a code owner for non-breaking changes. We'll still require **all** code owner approvals for breaking changes.
Please comment inline on the CODEOWNERS file if you think owners of specific things should be changed—@ospencer and I did the best we could.
From my understanding of CODEOWNERS, this might be clumsy for us to use. GitHub doesn't create a full set of all owners for all touched files, but instead assigns the last match in the file, so order matters. If this doesn't end up working for us, we can look into something else, but this is integrated into the platform. 🤷
> feat(docs)!: Update approvals process using CODEOWNERS

- compiler/src/codegen/compcore.re
- compiler/src/codegen/runtime_errors.re
- compiler/src/codegen/runtime_errors.rei
- compiler/test/__snapshots__/arrays.0f9e7d37.0.snapshot
- compiler/test/__snapshots__/arrays.28fcc534.0.snapshot
- compiler/test/__snapshots__/arrays.4c8c9f91.0.snapshot
- compiler/test/__snapshots__/arrays.6eac4e1f.0.snapshot
- compiler/test/__snapshots__/arrays.74d79181.0.snapshot
- compiler/test/suites/arrays.re
- stdlib/runtime/exception.gr
This PR fixes an issue where a potential non-integer or heap-allocated index for an array get/set may not result in an error. It also provides a better error for non-integer indexes.
> fix(compiler): Provide appropriate error during invalid array access

- .github/workflows/ci.yml
- compiler/src/compile.re
Since `~is_root_file` was not set for the polyfill, dependencies were not compiled. Tests didn't catch this because the dependencies were already compiled when the test was run.
Added a clean step to the near smoketest that would catch this in the future.
> fix(compiler): Fix dependency compilation of wasi polyfill

- compiler/src/formatting/comment_utils.re
- compiler/test/formatter_inputs/records.gr
- compiler/test/formatter_outputs/records.gr
Fixes #1575 
Handle comments properly when they are on the same line as the brace
> fix(grainfmt): Handle comments after braces properly when on one line

- compiler/src/typed/env.re
This reports the errors inline instead of at the top of the file, like so:
> fix(compiler): Fix error location reporting of unbound modules and labels

- compiler/src/codegen/mashtree.re
- compiler/src/codegen/transl_anf.re
- compiler/src/formatting/debug.re
- compiler/src/formatting/format.re
- compiler/src/middle_end/anf_helper.rei
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/middle_end/linearize.re
- compiler/src/parsing/ast_helper.re
- compiler/src/parsing/ast_helper.rei
- compiler/src/parsing/ast_iterator.re
- compiler/src/parsing/ast_mapper.re
- compiler/src/parsing/parser.messages
- compiler/src/parsing/parser.mly
- compiler/src/parsing/parsetree.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/src/typed/typedtreeIter.re
- compiler/src/typed/typedtreeMap.re
- compiler/src/utils/warnings.re
- compiler/src/utils/warnings.rei
- compiler/test/__snapshots__/records.012b017b.0.snapshot
- compiler/test/formatter_inputs/records.gr
- compiler/test/formatter_outputs/records.gr
- compiler/test/suites/records.re
Syntax for creating a copy of a record while changing some field values. Currently the "naive" approach of copying fields one at a time is used, but bulk copying was discussed as a possible future improvement.
Closes #778
> feat(compiler): Record spread syntax

- compiler/test/stdlib/array.test.gr
- stdlib/array.gr
- stdlib/array.md
- stdlib/immutablearray.gr
- stdlib/immutablearray.md
- stdlib/list.gr
- stdlib/list.md
Closes #1470 , making `Array.rotate` rotate to the left to match `ImmutableArray` and `List` behavior
> feat(stdlib)!: Change array rotation direction

- compiler/test/stdlib/list.test.gr
- stdlib/list.gr
- stdlib/list.md
Closes #1522 
Also allows rotation if positive `count` exceeds list length per the spirit of this issue and to match rotation behavior of other data structures (wrapping with the list length).
> feat(stdlib)!: `List.rotate` wraparound for count > length

- compiler/src/codegen/comp_utils.re
- compiler/src/codegen/comp_utils.rei
- compiler/src/codegen/compcore.re
- compiler/src/codegen/compcore.rei
- compiler/src/linking/link.re
This is a refactor that needs to happen prior to binaryen 110 because we want to make a constant for the memory and we'd end up with a dependency cycle with compcore and comp_utils.
> chore(compiler): Move constants from compcore into comp_utils

- compiler/src/parsing/parser.mly
- compiler/test/suites/parsing.re
Fixes #1609 
Since subtraction is left-associative and return statements are not required to have an expression, parsing `return -1` was causing the `return` itself to be treated as an expression, in the same way that typing `foo(5) - 4` would cause the parser to reduce `foo(5)` to a function call before attempting to parse subtraction.
Thanks @alex-snezhko for the report 🙂
> fix(compiler): Properly handle parsing return of negative number

- stdlib/runtime/bigint.gr
- stdlib/runtime/compare.gr
- stdlib/string.gr
While rebasing #1493 and poking around in the stdlib, I've found there are more places where we should be using early return.
There are even more but I wanted to chunk my current work to keep the diff easy enough.
> chore(stdlib): Utilize early return in more of the stdlib

- stdlib/list.gr
- stdlib/regex.gr
- stdlib/runtime/atof/parse.gr
This cleans up a few `when` expressions we had on pattern matches in the stdlib that were just comparing to constant values. I assume these are from before we supported constant values in pattern matches.
> chore(stdlib): Light cleanup on constant pattern matches

- compiler/test/stdlib/number.test.gr
- compiler/test/suites/basic_functionality.re
- stdlib/number.gr
- stdlib/number.md
This removes the `Number.nan` and `Number.infinity` constants and uses `Infinity` and `NaN` keywords. Ideally, this sort of changes will happen with the feature so we aren't adding 2 different breaking changes for it in the changelog.
> chore(stdlib)!: Replace Number.nan & Number.infinity constants with keywords

- compiler/src/codegen/compcore.re
- compiler/test/__snapshots__/chars.200d9e1a.0.snapshot
- compiler/test/__snapshots__/chars.259e330c.0.snapshot
- compiler/test/__snapshots__/chars.27fb7f30.0.snapshot
- compiler/test/__snapshots__/chars.51010573.0.snapshot
- compiler/test/__snapshots__/chars.7e0f68db.0.snapshot
- compiler/test/__snapshots__/chars.af4b3613.0.snapshot
- compiler/test/__snapshots__/chars.e1cac8cd.0.snapshot
- docs/contributor/data_representations.md
- stdlib/char.gr
- stdlib/runtime/string.gr
Change char internal representation to contain data shifted 8 to the left from the end rather than 3 to allow for inclusion of small ints into the same tag as char.
> feat(compiler)!: Change Char internal representation

- compiler/test/stdlib/float32.test.gr
- compiler/test/stdlib/float64.test.gr
- compiler/test/stdlib/int32.test.gr
- compiler/test/stdlib/int64.test.gr
With the addition of the module system, the typechecker is now smarter and understands that the `fromNumber` that comes from the `Int32` library is the same as doing `Int32.fromNumber`, so warnings are now produced by those tests. This change rebinds `fromNumber` to suppress the warning while we test the functionality.
> feat(compiler): Suppress warnings about using fromNumber for Int32/64 and Float32/64 tests

- compiler/src/parsing/lexer.re
- compiler/test/suites/parsing.re
While working on the language reference, I realized that the category used for whitespace wasn't quite right, disallowing some common whitespace while allowing some uncommon ones.
This PR states explicitly that Grain follows https://unicode.org/reports/tr31/#Pattern_Syntax for Unicode allowed in the syntax of the language.
Whitespace in Grain now properly adheres to _Pattern_White_Space_, with additional Grain semantics described below.
Whitespace includes:
Spaces, namely
- Horizontal tab, `U+0009`
- Vertical tab, `U+000B`
- Space, `U+0020`
- Left-to-right mark, `U+200E`
- Right-to-left mark, `U+200F`
Line separators, namely
- Line feed, `U+000A`
- Form feed, `U+000C`
- Carriage return, `U+000D`
- Next line, `U+0085`
- Line separator, `U+2028`
- Paragraph separator, `U+2029`
Line …
> fix(compiler)!: Apply correct rules for parsing Unicode whitespace

- compiler/test/stdlib/sys.file.test.gr
- compiler/test/suites/stdlib.re
- stdlib/sys/file.gr
- stdlib/sys/file.md
These utilities previously operated on Strings, but this is not quite correct since files can contain any type of data, not just UTF8 encoded strings.
> fix(stdlib)!: Sys/File reading and writing operate on Bytes

- compiler/src/formatting/comment_utils.re
- compiler/src/formatting/format.re
- compiler/test/formatter_inputs/comments.gr
- compiler/test/formatter_outputs/comments.gr
I'm trying to break my cleanups into understandable chunks. This is part 1.
> chore(grainfmt): Consolidate comment logic by removing assumed breaks

- compiler/src/codegen/comp_utils.re
Grain calling convention requires all function arguments be incref'ed before calling the function. Previously, after calling a universal export, the closure would be deallocated, crashing the program if the export was called more than once.
Necessary for #1029
> fix(compiler): Fix memory bug in universal exports

- stdlib/runtime/string.gr
Test for this in `strings.re` continues to pass.
> chore(stdlib): Clean up extra case in string escape logic

- cli/bin/grain.js
- compiler/src/linking/link.re
- compiler/src/utils/config.re
- compiler/src/utils/config.rei
- compiler/test/suites/linking.re
Works towards #1029 
For compilers that support this functionality, they just support importing from `env.memory`. We could make this a bit more complicated and allow passing the module name and memory name, but for now I don't think this is necessary.
We don't currently have the ability to add a test for this because the memory import happens after linking.
> feat(compiler): Allow importing a memory

- compiler/src/parsing/ast_helper.rei
- compiler/src/parsing/lexer.re
- compiler/src/parsing/parser.mly
- compiler/test/suites/strings.re
Works towards #1029 
Currently, printing bytes uses a custom format: `<bytes: 4a 56 ef ...>`
Should bytes print as byte strings? If so, we should make an issue and that can be a follow-on PR.
> feat(compiler): Bytes literals

- compiler/graindoc/docblock.re
- compiler/graindoc/graindoc.re
- compiler/src/diagnostics/comment_attributes.re
- compiler/src/diagnostics/graindoc_parser.mly
- stdlib/regex.md
This updates graindoc to support submodules. Since modules need to be processed recursively, I needed to refactor most of the graindoc internals. This was a really good refactor because it makes a clear separation between the attribute parsing, the docblock data types, and the markdown generation phase. Both the docblock collection and markdown generation are recursive so we can start at the top of the program tree and call `Docblock.for_signature_items` and the `Docblock.to_markdown` on the results and everything gets printed.
Since we don't have any submodules in the stdlib at the moment, I've run this against #1479 and pushed the updated docs as https://github.com/grain-lang/grain/pull/1479/commits/4dfc7c56074cc929f3becad5db7a98e0d3e7174c
Closes #1621
> feat(graindoc)!: Support docblocks on submodules

- compiler/src/utils/markdown.re
- compiler/test/utils/markdown.re
This escapes any `*+` characters at the beginning of a string passed to `Markdown.bold`, any `**+` anywhere in the string, and any `*+` at the end of string. These all would cause the bold to be rendered improperly.
I've also started adding tests for the markdown utils, to ensure this was working before applying to #1538
Closes #1550 - I know this said to escape `_` but those don't actually effect the `**` added by bold so I'm not going to escape them right now.
> fix(graindoc): Escape * chars that would close markdown bold incorrectly

- compiler/graindoc/docblock.re
- compiler/graindoc/graindoc.re
- stdlib/bigint.gr
- stdlib/float32.gr
- stdlib/float64.gr
- stdlib/int32.gr
- stdlib/int64.gr
- stdlib/pervasives.gr
- stdlib/runtime/compare.gr
- stdlib/runtime/compare.md
- stdlib/runtime/equal.gr
- stdlib/runtime/equal.md
- stdlib/runtime/numbers.gr
- stdlib/runtime/numbers.md
- stdlib/runtime/string.gr
- stdlib/runtime/string.md
Graindoc will now pull docs from the original definition of a value/type/module. This was enabled by adding all of the location information to the CMI. Note that each file that provides a value needs to be recompiled through the parse phase so we can get the parsed comments.
This is a breaking change to graindoc since it will **only** pull from the original definition. You can see that I had to move definitions into the runtime to make this work. That results in the docs existing in the runtime and then in the stdlib places they are re-provided.
This should also solve the problem @alex-snezhko brought up in discord since each thing being documented will pull the exact definition.
Closes #1626
> feat(graindoc)!: Only use original doc blocks when re-providing

- compiler/graindoc/docblock.re
In #1685, I added the fix for escaping values; however, when @spotandjake generated his docs in #1690 the fix wasn't applied. I traced it down to this line not using the markdown helpers and trying to do bolding itself.
> fix(graindoc): Use Markdown bold helper for each case of bolding

- compiler/src/parsing/ast_helper.re
- compiler/src/parsing/ast_helper.rei
- compiler/src/parsing/parser.mly
- compiler/src/parsing/parsetree.re
- compiler/src/typed/typedecl.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
This removes the `pval_prim` and `tvd_prim` labels on `value_description`. I believe these were used before `primitive_description` existed, but we should be able to remove now because it was always an empty list.
> chore(compiler): Remove unused prim values on value_descriptions

- compiler/src/formatting/format.re
- compiler/src/parsing/ast_helper.rei
- compiler/src/parsing/ast_mapper.re
- compiler/src/parsing/parser.mly
- compiler/src/parsing/parsetree.re
- compiler/src/parsing/parsetree_iter.re
- compiler/src/parsing/well_formedness.re
- compiler/src/typed/typecore.re
- compiler/test/suites/basic_functionality.re
While working on the formatter stuff, I noticed that we represented the `else` branch as an empty block in the AST. This makes things like the formatter harder, so I think we should just change it to `option(expression)`.
> chore(compiler): Represent the else branch of PExpIf as an option instead of empty block

- stdlib/runtime/numbers.gr
This pr refactors `pow` to use early return. 
This also adds a small optimization to `Rational**Int` Cases.
> chore: Make `pow` use early return

- compiler/test/suites/strings.re
- stdlib/runtime/string.gr
This pr adds custom box printing.
Now single argument tuples will be wrinted as `Box(1)` intead of `(1,)` given the only safe way to create a single arugment tuple is by using the box primitive.
I am wondering where I would add a regression test for this if needed I couldn't see anywhere, that we were testing `print` or `toString`.
Closes: #1620
> feat(compiler)!: Custom box printing

- compiler/test/stdlib/string.test.gr
- stdlib/string.gr
This pr fixes #1700 , The issue had nothing todo with the recursive pattern given how ReplaceAll only replaces the strings after it finds them all the real issue was that in the inital implementation it was never accounted for a scenario of the distance betweeen two matching patterns being smaller then the matching length this new pr changes that so when we find a match we increment by the length of the pattern.
Essentially what was happening is in the example below we were matching three sets of `Meow` when the second two `Meow`s should be eaten by the first match and the last match.
```
String.replaceAll("MeowMeow", "Meow", "MeowMeowMeowMeow")
```
> fix: Fix String.ReplaceAll

- compiler/src/parsing/well_formedness.re
- compiler/test/suites/chars.re
This pr escapes `"` in the error for chars that are meant to be strings.
This is because in a case like `'{"test":1}'` when the compiler asks you if you mean `"{"test":1}"` it would be an invalid string so instead the new error looks like `"{\"test\":1}'`
> chore(compiler): Escape `"` in char well formness error

- compiler/test/stdlib/string.test.gr
- stdlib/bytes.gr
This change ensures we always provide a zeroed byte array from `Bytes.make`.
Closes #1723
> feat(stdlib)!: Provide empty byte array from Bytes.make

- compiler/src/parsing/well_formedness.re
- compiler/test/suites/chars.re
> fix(compiler): Provide appropriate error for empty char literals

- compiler/test/runner.re
- compiler/test/suites/basic_functionality.re
- stdlib/runtime/gc.gr
- stdlib/runtime/gc.md
- stdlib/runtime/numberUtils.gr
- stdlib/runtime/unsafe/memory.gr
- stdlib/runtime/unsafe/memory.md
This removes an unnecessary dependency for some Grain programs, allowing them to save some file size. This is particularly helpful for running in runtimes with limited memory, like wasm4.
This change makes the smallest Grain program `module Main` when compiled with `--elide-type-info` and `--release` 5056 bytes.
There is one other change necessary to make this program truly a no-op (< 100 bytes) but that hasn't been deemed necessary at this time.
> chore(stdlib): Remove debugging code

- compiler/src/formatting/format.re
- compiler/src/parsing/ast_helper.re
- compiler/src/parsing/ast_helper.rei
- compiler/src/parsing/ast_mapper.re
- compiler/src/parsing/parser.mly
- compiler/src/parsing/parsetree.re
- compiler/src/parsing/parsetree_iter.re
- compiler/src/parsing/well_formedness.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typepat.re
- compiler/test/suites/blocks.re
This adds Singleton constructors on `constructor_pattern` and `constructor_expression` types. While rewriting the formatter, I found that we used empty lists to indicate this but that seems weird when they are formatted differently than tuples.
> chore(compiler): Add singleton constructor to expressions and patterns

- stdlib/string.gr
- stdlib/string.md
This pr adds graindoc `@throws` attributes to the `string` stdlib.
closes: #1519
> chore(stdlib): Add throws documentation to String module

- compiler/src/formatting/debug.re
- compiler/src/formatting/format.re
- compiler/src/middle_end/linearize.re
- compiler/src/parsing/ast_helper.re
- compiler/src/parsing/ast_helper.rei
- compiler/src/parsing/ast_mapper.re
- compiler/src/parsing/parsetree.re
- compiler/src/parsing/parsetree_iter.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/src/typed/typedtreeIter.re
- compiler/src/typed/typedtreeMap.re
This pr removes `PEXPNULL` and `TEXPNULL` from the ast. given they are no longer used.
Closes: #1719
> chore(compiler): Remove `PExpNull` and `TExpNull`

- stdlib/runtime/atof/parse.gr
It looks as though a random `assert` was left in `atof` from debugging this is a tiny pr to clean that up.
> chore: remove assert from `atof`

- compiler/test/stdlib/uint16.test.gr
- compiler/test/stdlib/uint32.test.gr
- compiler/test/stdlib/uint64.test.gr
- compiler/test/stdlib/uint8.test.gr
- stdlib/random.gr
- stdlib/uint16.gr
- stdlib/uint16.md
- stdlib/uint32.gr
- stdlib/uint32.md
- stdlib/uint64.gr
- stdlib/uint64.md
- stdlib/uint8.gr
- stdlib/uint8.md
This changes `>>` to `>>>` in the `uint` libs to reflect that they are unsighned. this also changes `%` to rem in the unsighned libs to better reflect that it is just returning the remainder.
> chore(stdlib)!: Update Operator `uint` operator Names

- compiler/src/typed/builtin_types.re
- compiler/test/__snapshots__/arrays.0f9e7d37.0.snapshot
- compiler/test/__snapshots__/arrays.1deb7b51.0.snapshot
- compiler/test/__snapshots__/arrays.28fcc534.0.snapshot
- compiler/test/__snapshots__/arrays.4c8c9f91.0.snapshot
- compiler/test/__snapshots__/arrays.6eac4e1f.0.snapshot
- compiler/test/__snapshots__/arrays.74d79181.0.snapshot
- compiler/test/__snapshots__/basic_functionality.2bcc447b.0.snapshot
This type is not used by the `File` library and is not used anywhere in Grain.
> chore(compiler)!: Remove built-in FileDescriptor type

- compiler/test/stdlib/buffer.test.gr
- compiler/test/stdlib/string.test.gr
- stdlib/buffer.gr
- stdlib/path.gr
- stdlib/regex.gr
- stdlib/string.gr
- stdlib/string.md
Closes #1566
This uses defaulted arguments to make the API of `String.slice` nicer. The `end` argument is now required to be used as a label or it is defaulted to the length of the input string.
> feat(stdlib)!: Use String length as default end in `String.slice` function

- compiler/src/parsing/parser.mly
While working on the formatter, I discovered these locations were wrong.
> fix(compiler): Correct locations for data constructor idents

- compiler/src/codegen/transl_anf.re
- compiler/src/typed/typemod.re
- compiler/test/suites/modules.re
- compiler/test/test-libs/simpleModule.gr
This PR fixes an issue where a module on the include path that re-provided other included modules could not be compiled as a part of a project. 
Previously, a module re-export was just a pointer to the original module. Now, the intermediate module provides the full interface. This incurs no runtime cost, but compilation may be a tad slower due to the indirection.
> fix(compiler): Provide full module interface in intermediate wasm files

- compiler/src/compile.re
This pr just removes a variable that I think was left over from a past change that reference a `.wast` file extension as its no longer used anywhere its probably good to be removed.
> chore(compiler): Cleanup reference to `wast`

- compiler/test/stdlib/array.test.gr
- stdlib/array.gr
- stdlib/array.md
Following the lead of #1748 
This uses defaulted arguments to make the API of `Array.slice` nicer. The end argument is now required to be used as a label or it is defaulted to the length of the input array.
> feat(stdlib)!: Use Array length as default end in `Array.slice` function

- .github/workflows/build-js.yml
- .github/workflows/build-native.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/dependencies.yml
- .github/workflows/docker-publish.yml
- .github/workflows/release.yml
- .github/workflows/test-pkg.yml
- compiler/package.json
- package-lock.json
Closes #1409
This updates the CI to use reusable workflows, which will allow us to construct more complex workflows (such as a nightly build). Some of the splitting is unintuitive so I tried to document why specific workflows exist.
The best thing about these changes are that built artifacts are attached to the workflow run, such as the native build executables and the pkg binaries, so we can use them later (see the test-pkg workflow) or download them to debug, etc.
I also took the opportunity to refactor a bit so it's easier to figure out what failed without having to look at logs.
> chore(ci): Convert CI workflows to reusable & apply various QoL changes

- .github/workflows/build-js.yml
- .github/workflows/build-native.yml
- .github/workflows/ci.yml
- .github/workflows/generate-docs.yml
- .github/workflows/release.yml
- .github/workflows/test-pkg.yml
- .github/workflows/upload-binaries.yml
This updates the Release workflow to generate "preview" binaries whenever the Release Please updates the release PR. It also uses that binary to regenerate and push the docs on the release branch, which triggers a CI run necessary for us to merge the release in the queue.
I refactored the workflow a bit so we use the same logic to build and upload the binaries with the same workflow. This should allow us to be more confident the release flow will happen successfully since the previews are built often.
I didn't get around to adding workflow_dispatch so we could run these in isolation, which is mostly because we rely on the binary being an artifact of a run. We might need to combine some reusable workflows into a dispatch, but I'm not sure yet.
> feat(ci): Add builds for preview binaries

- compiler/src/codegen/compcore.re
- compiler/src/codegen/garbage_collection.re
- compiler/src/codegen/mashtree.re
- compiler/src/middle_end/analyze_purity.re
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
- compiler/src/middle_end/linearize.re
- compiler/src/parsing/parsetree.re
- compiler/src/typed/translprim.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/test/suites/basic_functionality.re
> feat(compiler): Add `magic` primitive

- compiler/src/utils/fs_access.re
This just handles a single `TODO` related to using `String.ends_with`
> chore(compiler): Use `String.ends_with` to check last character

- js-runner/LICENSE
- stdlib/LICENSE
This changes the license year from `2022` to `2023` in the stdlib and js-runner license's looks like we missed it when we changed the main copyright notice.
> chore: Update license year

- compiler/test/suites/strings.re
- stdlib/runtime/string.gr
Closes: #1799 
This pr removes the trailing space when printing bytes literals, it looked off with the trailing space before the space seemed to have come from when we caculate the string length we do `numBytes * 3` two chars for the hex and 1 char for the space and then we use memory.Fill to fill the string with spaces this by subtracting one from the `numBytes * 3` we get rid of the spot for the trailing space.
Breaking: This changes that behaviour of `toString` and `print` to a user.
Note: I did not see any test for the `...` behaviour or print should i add a test under the test for bytes_literals printing to test strings taht are too long?
> fix(stdlib)!: Remove extra space when converting Bytes to String

- compiler/src/parsing/parser.messages
- compiler/src/parsing/parser.mly
While working on the formatter, I noticed that the location for variants weren't what I thought. As I went to update them, I was confused why we would allow a variant like `Foo()` and @ospencer said it was a bug.
I've made the types non-optional and I've moved it into a new declaration so the locations are correct. I also renamed `data_labels` to `data_record_body` since it also represents the braces. Happy to change if @ospencer thinks of better naming.
> fix(compiler)!: Disallow enum variants with parens but no types

- compiler/test/stdlib/array.test.gr
- stdlib/array.gr
- stdlib/array.md
This pr makes `Array.fillRange` work correctly with negative indexs.
This pr also corrects the `failure`s used to be actual exceptions.
Closes: #1521
> fix(stdlib)!: Ensure `Array.fillRange` works with negative indexing & throws IndexOutOfBound

- compiler/test/stdlib/char.test.gr
- stdlib/char.gr
- stdlib/char.md
This pr adds comparison operators to the `char` stdlib.
This is blocked on #1734 beacuse currently the imports from the wasm library are using the names rather then the operators.
> fea(stdlib): Add comparison operators to char stdlib

- stdlib/sys/process.gr
This returns early from the `Process.argv()` function if the `argsLength` is zero. This avoids some differences between wasi implementations, and is also probably just a good idea to avoid extra sys calls.
Fixes an issue I was encountering in #1585
> fix(stdlib): Return early from `Process.argv()` if length is zero

- docs/contributor/runtime.md
- stdlib/runtime/malloc.gr
Since #1410 was landed, far less memory is used in programs run in runtime mode. I did an audit, and it seems that we now only use ~650 bytes, so I reduced the reserved runtime size from 16384 bytes down to 2048 bytes. This is helpful when running in some memory-constrained runtimes, like wasm4.
> feat(compiler)!: Reduce size of runtime heap

- .github/workflows/build-js.yml
- .github/workflows/build-native.yml
- .github/workflows/dependencies.yml
- .github/workflows/release.yml
It seems that my range was too broad and we started pulling down node 20, which pkg can't build.
> chore(ci): Always run actions on node v18

- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/esy.lock/opam/utop.2.12.1/opam
- compiler/src/codegen/comp_utils.re
- compiler/src/codegen/comp_utils.rei
- compiler/src/codegen/compcore.re
- compiler/src/linking/link.re
This updates to binaryen 110 using our binaryen.ml bindings v0.20.1 - the big change is that binaryen requires all APIs to use an internal memory name when interacting with memories. This is to support multi-memory, I believe. However, we found a bunch of problems and/or bugs with their implementation that we need to raise upstream.
This currently has workarounds for the issues but relies on us dropping the js-runner in #1585. It also is built upon my cleanup in #1598
> chore(compiler): Update binaryen.ml to v0.20.1

- compiler/test/stdlib/number.test.gr
- stdlib/number.gr
- stdlib/number.md
This pr adds `linearInterpolate`, `linearMap` and `clamp` to the `Number` stdlib.
This currrently is using the compilers in built `Range` record in the tests but should eventually be switched to the range syntax whenever it is added.
This is work on: #1017
> feat(stdlib): Add `linearInterpolate`, `linearMap` and `clamp`

- compiler/test/input/memoryBase/asserts.gr
This test would need to be updated every time we change a type in the runtime or Pervasives, which is cumbersome.
> chore(stdlib): Make memory base test less strict

- .github/workflows/release.yml
We're now using node 18 in CI so we can remove my sed workaround for an npm bug, which was fixed in 9.1.3 - I checked node 18.6 and it comes with npm 9.5.1
> chore(ci): Remove sed usage in stdlib release

- compiler/test/suites/cycles.re
- stdlib/runtime/string.gr
Closes #1841 
I used a style of reporting cycles similar to Node.js where references are labeled with numbers whenever there is a cycle. For example:
```
record A {
val: Number,
mut next: Option<A>
}
let a = { val: 1, next: None }
let aOpt = Some(a)
a.next = aOpt
print(a)
// output:
<1>: {
val: 1,
next: Some(<cycle to <1>>)
}
```
> feat(stdlib)!: Handle printing of reference cycles

- compiler/test/stdlib/list.test.gr
- stdlib/list.gr
- stdlib/list.md
This pr adds `List.isEmpty` bringing the api inline with the other data types. This is beneficial for `List` especially as the common way of checking if a `List` is empty is `List.length(i) == 0` which in the case of list would have to iterate the entire list to calculate the length.
closes: #1784
> feat(stdlib): Add `isEmpty` to `List` module

- compiler/test/stdlib/string.test.gr
- stdlib/string.gr
- stdlib/string.md
This pr adds `String.isEmpty` to the string library to bring it in line with other api's from different modules, off of oscars in discord stdlib notes.
Benefit of adding this is making the api the same as other data types and providing more clarity in code.
Note: empty means no characters are included in the module so `bytelength` is equivalent to 0.
> feat(stdlib): add `isEmpty` to `String` module

- compiler/test/stdlib/queue.test.gr
- stdlib/queue.gr
- stdlib/queue.md
This fixes a tiny bug where if you did:
```
let q = Queue.makeSized(0)
Queue.push(1, q)
```
you would get an index out of range error.
Breaking because you will no longer recieve an exception.
> fix(stdlib): Properly resize empty Queue on push

- stdlib/regex.gr
This pr converts some of the matches in the `Regex` lib to use or patterns.
Closes: #696 
One other bit of cleanup I wonder if it is worth it is to merge these to use a variable f, and then just pass that to the functions:
@peblair is there a reason you didnt use a variable here.
> chore(stdlib): Use `|` patterns to cleanup pattern matches

- stdlib/bytes.gr
- stdlib/bytes.md
This is a small pr changing the wording used in `Bytes.move`, it makes sense to stay away from the wording `Buffer` given grain has a specific `Buffer` type which is different than the `Bytes` type.
Closes: #1836
> chore(stdlib): Clarify `Byte.move` docs

- compiler/test/stdlib/stack.test.gr
- stdlib/stack.gr
- stdlib/stack.md
Applies the fix made on queue in #1865 to the `Stack` Module
> fix(stdlib): Properly resize empty Stack on push

- compiler/test/stdlib/list.test.gr
- stdlib/list.gr
- stdlib/list.md
> feat(stdlib)!: Reorder parameters to `List.insert`

- compiler/src/formatting/format.re
- compiler/src/parsing/parser.messages
- compiler/src/parsing/parser.mly
- compiler/test/grainfmt/includes.expected.gr
- compiler/test/grainfmt/includes.input.gr
- compiler/test/input/modules/provideIncludedModule.gr
- compiler/test/input/nestedModules.gr
- compiler/test/stdlib/array.test.gr
- compiler/test/stdlib/map.test.gr
- compiler/test/stdlib/priorityqueue.test.gr
- compiler/test/stdlib/queue.test.gr
- compiler/test/stdlib/range.test.gr
- compiler/test/stdlib/set.test.gr
- compiler/test/stdlib/stack.test.gr
- compiler/test/suites/includes.re
- compiler/test/suites/modules.re
- compiler/test/suites/provides.re
```
// provide
module Submodule {
// ...
}
provide { module Submodule }
// use
from Mod use { module Submodule }
```
> feat(compiler)!: Require `module` prefix on `use`/`provide` for modules

- cli/bin/exec.js
- cli/bin/grain.js
- cli/bin/grainrun.js
- compiler/test/runner.re
- compiler/test/stdlib/sys.process.test.gr
- compiler/test/suites/wasi_args.re
- stdlib/sys/process.gr
Closes #1822 
Closes #1823 
Examples:
```
grain a.gr --env=FOO=bar
grain a.gr --env FOO=bar FOO2=baz -- arg1 arg2
grain a.gr arg1 arg2   # will not pass args to WASI, -- required
```
> feat(cli)!: Allow specifying WASI environment variables and CLI args

- cli/bin/grain.js
This pr changes the cli to make it so `grain main.gr --use-start-section` no longer works and you have to use `grain compile main.gr --use-start-section` when using the `--use-start-section` flag.
This was done because in the move to the new wasi runner. the way the runner loads the wasm module changed meaning that if you tried to use the grain runner with `--use-start-section` you would get an error as wasi is not intialized when node calls the start function.
This is marked breaking because the flag can no longer be used with the runner.
This should be able to be reverted when grain switches to using wamr as a wasm runner.
closes: #1847
> fix(cli)!: Ensure `--use-start-section` can only be used with compile command

- compiler/src/typed/oprint.re
Fixes: #1894
Technically we may want to use another prefix compared to `exception` but given they are the only open type in grain. this should be good for now.
> feat: Add `exception` opentype implementation to `Oprint`

- compiler/src/typed/env.re
- compiler/src/typed/typemod.re
- compiler/test/suites/includes.re
- compiler/test/test-libs/provideContents.gr
- compiler/test/test-libs/reprovideContents.gr
> fix(compiler): Type aliasing in `use` statements

- compiler/esy.json
- compiler/esy.lock/index.json
- compiler/esy.lock/opam/chrome-trace.3.10.0/opam
- compiler/esy.lock/opam/dune-build-info.3.10.0/opam
- compiler/esy.lock/opam/dune-configurator.3.10.0/opam
- compiler/esy.lock/opam/dune-rpc.3.10.0/opam
- compiler/esy.lock/opam/dune.3.10.0/opam
- compiler/esy.lock/opam/dyn.3.10.0/opam
- compiler/esy.lock/opam/ocamlformat-rpc-lib.0.26.0/opam
- compiler/esy.lock/opam/ocamlgraph.2.1.0/opam
- compiler/esy.lock/opam/ordering.3.10.0/opam
- compiler/esy.lock/opam/re.1.11.0/opam
- compiler/esy.lock/opam/stdune.3.10.0/opam
- compiler/esy.lock/opam/xdg.3.10.0/opam
This realigns ocaml dependencies to upstream where possible: my fix landed into reason-native and we can remove some resolutions.
> chore(compiler): Realign ocaml dependencies

- cli/bin/grainrun.js
I was trying to run our tests with node 20 globally and they were failing.
We don't want to upgrade our version in CI yet (though soon!) but we also want them to run if people don't have the exact setup.
> chore(cli): Ensure our WASI runner works on node 20+

- compiler/esy.json
- compiler/esy.lock/index.json
This updates to binaryen.ml 0.22 which are our bindings for the binaryen 112 release
> chore(compiler): Upgrade to binaryen 112

- compiler/test/stdlib/int64.test.gr
- compiler/test/stdlib/sys.time.test.gr
- stdlib/int64.gr
- stdlib/int64.md
This pr brings the `Int64` library inline with the changes made in #1742 and #1734 
Marked as breaking beecause the external api changes.
> feat(stdlib)!: Replace `Int64` arithmatic functions with operators

- compiler/test/stdlib/int32.test.gr
- stdlib/int32.gr
- stdlib/int32.md
This pr brings the `Int32` library inline with the changes made in #1742 and #1734 
Marked as breaking beecause the external api changes.
> feat(stdlib)!: Replace `Int32` arithmatic functions with operators

- compiler/src/formatting/format.re
- compiler/src/parsing/ast_helper.re
- compiler/src/parsing/ast_helper.rei
- compiler/src/parsing/parser.mly
- compiler/src/typed/parmatch.re
- compiler/src/typed/translprim.re
- compiler/src/typed/typecore.re
- compiler/test/suites/arrays.re
- compiler/test/suites/basic_functionality.re
- compiler/test/suites/blocks.re
- compiler/test/suites/chars.re
- compiler/test/suites/parsing.re
- compiler/test/suites/strings.re
This pr makes locatons on ast nodes not optional.
Question should we also refactor the anf_helper nodes to have non optional locs in this pr or should we do that in a seperate pr.
Closes: #1106
> chore(compiler): Make Ast_helper locs non optional

- compiler/test/__snapshots__/basic_functionality.00bcbc39.0.snapshot
- compiler/test/__snapshots__/basic_functionality.06bd2a80.0.snapshot
- compiler/test/__snapshots__/basic_functionality.7599b5a6.0.snapshot
- compiler/test/__snapshots__/basic_functionality.79ea1ccc.0.snapshot
- compiler/test/__snapshots__/basic_functionality.bb137371.0.snapshot
- compiler/test/suites/basic_functionality.re
In #1928 it was noticed that we dont have basic tests for binop assignments, this adds some basic testing for that.
> chore(tests): Add basic testing for binop assignments

- compiler/src/codegen/transl_anf.re
- compiler/src/middle_end/analyze_inline_wasm.re
- compiler/src/middle_end/analyze_manual_memory_management.re
- compiler/src/middle_end/anf_helper.re
- compiler/src/middle_end/anf_helper.rei
- compiler/src/middle_end/anftree.re
- compiler/src/middle_end/anftree.rei
This pr removes the unused `js_func` from the anftree. It looks to just be unused legacy code.
> chore(compiler): Remove unused `JSFunction` and `js_func`

- stdlib/runtime/bigint.gr
Optimizes `absi32` and `absi64` in `runtime/bigint` to avoid branching.
Closes: #1188
> chore(runtime): Optimize `abs` in `runtime/bigint`

- compiler/test/stdlib/int32.test.gr
- stdlib/int32.gr
- stdlib/int32.md
This pr adds a power function to the `Int32` library. This pr will need to be updated after #1936 is merged.
> feat(stdlib): Add `**` operator to `Int32` module

- compiler/test/stdlib/queue.test.gr
- stdlib/queue.gr
- stdlib/queue.md
Adds `fromArray` to the `Queue` module, helping to bring it more inline with the other stdlib data structures.
> feat(stdlib): Add `fromArray` to `Queue` module

- compiler/test/stdlib/float32.test.gr
- compiler/test/suites/numbers.re
- compiler/test/suites/strings.re
- stdlib/float32.gr
- stdlib/float32.md
This pr switches `Float32` from using functions to operators
> feat(stdlib)!: Replace `Float32` arithmatic/comparison functions with operators

- stdlib/regex.gr
This pr just changes the `Regex` library from using `Float32.toNumber(Float32.infinity))` to `Infinity`, which means we can drop the uneccessary dependency
> chore(stdlib): Leverage `Infinity` keyword in `Regex` module

- stdlib/runtime/equal.gr
This replaces the logic for `String` equality and `Bytes` equality using the `Memory.compare` function. which should help reduce the size of the generated function and increase performance a tiny bit.
> feat(stdlib): Simplify `equal` using `Memory.compare`

- stdlib/float64.gr
Repurposed this pr to remove the `Float64.Infinity` and `Float64.nan` in favour of `Infinityd` and `NaNd`
> chore(stdlib): Simplify `Float64.infinity`, `Float64.nan` definitions

- stdlib/float32.gr
Repurposed this pr to remove `Float32.Infinity` and `Float32.NaN` in favour of the `Infinityf` and `NaNf` syntax
> chore(stdlib): Simplify `Float32.Infinity` and `Float32.NaN` definitions

- stdlib/int8.gr
- stdlib/int8.md
This pr adds examples to the docs for `Int8`
> chore(stdlib): Add examples to `Int8` module

- compiler/test/stdlib/float64.test.gr
- compiler/test/suites/numbers.re
- compiler/test/suites/strings.re
- stdlib/float64.gr
- stdlib/float64.md
This pr switches `Float64` from using functions to operators
> feat(stdlib)!: Replace `Float64` arithmatic/comparison functions with operators

- stdlib/array.gr
This pr optimizes `Array.join` using low level instructions.
Work for: #728
> chore(stdlib): Optimize `Array.join`

- stdlib/bytes.gr
- stdlib/bytes.md
This pr adds examples to the docs for `Bytes`
> chore(stdlib): Add examples to `Bytes` module

- compiler/src/typed/typecore.re
This adds a label to the `ArrayLength` primitive. 
Neccessairy for #1973.
Question, do we want to add labels to all the primitive functions?
> chore(compiler): Add arg label to `ArrayLength` primitive

- .github/workflows/docker-publish.yml
I believe the flakiness happening with the docker builds is that one job starts the machine and the other sees that it's already running and decides to move forward, even if the machine isn't truly ready yet. This makes the CI wait until the machine reports OK status rather than just running.
> chore(ci): Improve reliability of docker builds on AWS

- stdlib/buffer.gr
This optimizes `Buffer.addChar` which previously relied on `Char.toString`. This new method eliminates the need for a needless string allocation on the heap.
Closes: #1879
> chore(stdlib): Optimize `Buffer.addChar`

- stdlib/exception.gr
- stdlib/exception.md
This pr improves the docs for exceptions, by adding examples. Changes the since attribute to use the `v` pattern used by the rest of the stdlib. and fixes a small spelling mistake.
> chore(stdlib): Add examples to `Exception` module

- stdlib/string.gr
This optimizes `String.trim` by avoiding the double allocation of a new string after each separate string. Now we only allocate a new string once weve trimmed both sides.
I think this optimization can also close: #982 even though we still do two seperate iterations combing them would likely lead to unmaintainable code with a minimal performance increase.
> chore(stdlib): Optimize `String.trim`

- stdlib/char.gr
- stdlib/char.md
This pr improves the docs for `Char` by adding examples. It also switches the `semvar` format to use the `v` as the other stdlibs do.
> chore(stdlib): Add examples to `Char` module

- stdlib/array.gr
This is a really small pr that changes the implementation of `Array.length` to use the internal instruction.
> chore(stdlib): Export `@array.length` primitive directly

- compiler/src/parsing/parser.messages
- compiler/src/parsing/parser.mly
- compiler/test/suites/arrays.re
Closes #1915
Following the same semantics as record set, array accesses should allow to make use of shorthand binary operation assignments like `+=`.
`arr[0] += 1` currently throws a syntax error, this should fix it.
> feat(compiler): Allow arrays to do binary operation assignment

- compiler/src/parsing/well_formedness.re
- compiler/test/suites/chars.re
I noticed a few places where well-formedness checks weren't being applied properly to patterns.
> fix(compiler): Properly apply well-formedness checks on patterns

- compiler/src/formatting/format.re
- compiler/src/language_server/definition.re
- compiler/src/language_server/hover.re
- compiler/src/language_server/sourcetree.re
- compiler/src/middle_end/linearize.re
- compiler/src/parsing/ast_mapper.re
- compiler/src/parsing/parser.messages
- compiler/src/parsing/parser.mly
- compiler/src/parsing/parsetree.re
- compiler/src/parsing/parsetree_iter.re
- compiler/src/parsing/well_formedness.re
- compiler/src/typed/datarepr.re
- compiler/src/typed/env.re
- compiler/src/typed/env.rei
- compiler/src/typed/printtyp.re
- compiler/src/typed/printtyp.rei
- compiler/src/typed/typedecl.re
- compiler/src/typed/typemod.re
- compiler/src/typed/types.re
- compiler/src/typed/typetexp.re
- compiler/src/typed/typetexp.rei
- compiler/test/grainfmt/includes.expected.gr
- compiler/test/grainfmt/includes.input.gr
- compiler/test/suites/provides.re
- compiler/test/test-libs/provideException.gr
- compiler/test/test-libs/reprovideException.gr
Closes #1053
Syntax:
```
// provider.gr
provide exception MyException
// OR
exception MyException
provide { exception MyException }
// includer.gr
include "./provider"
from Provider use { exception MyException }
// can re-provide
provide { exception MyException }
```
> feat(compiler): Providing, including, reproviding exceptions

- stdlib/array.gr
- stdlib/array.md
This pull request adds examples to every function in the array module, along with standardizing the style of the examples.
I plan on going through and adding examples to all the modules in the stdlib starting with this so it makes sense to note some style decisions:
* All the examples are runnable
*  The only thing that needs to be added is the module header and the include
* for single line examples an assert needs to be added as well
* Single line examples are treated as if they were assertions
* Syntax for creating the data type is added as an example to the `module`, It seems like a good place to show a basic example of how to create the data type that were working with. I think this will be more helpful with the number libs later on.
* Examples are placed between `@throws` and …
> chore(stdlib): Improve examples in `Array` module

- compiler/test/__snapshots__/basic_functionality.122e74b0.0.snapshot
- compiler/test/__snapshots__/basic_functionality.1f787365.0.snapshot
- compiler/test/__snapshots__/basic_functionality.52ca8e0e.0.snapshot
- compiler/test/__snapshots__/basic_functionality.711a4824.0.snapshot
- compiler/test/__snapshots__/basic_functionality.7d0640b4.0.snapshot
- compiler/test/__snapshots__/basic_functionality.b07cc734.0.snapshot
- compiler/test/__snapshots__/basic_functionality.b836b89a.0.snapshot
- compiler/test/__snapshots__/basic_functionality.c4090bb1.0.snapshot
- compiler/test/__snapshots__/basic_functionality.d6ca4146.0.snapshot
- compiler/test/__snapshots__/basic_functionality.fe88cb04.0.snapshot
- compiler/test/__snapshots__/enums.ae26523b.0.snapshot
- compiler/test/__snapshots__/includes.c0c0d5ca.0.snapshot
- compiler/test/__snapshots__/pattern_matching.0fa61137.0.snapshot
- compiler/test/__snapshots__/pattern_matching.25930935.0.snapshot
- compiler/test/__snapshots__/pattern_matching.9ffaa7a7.0.snapshot
- compiler/test/__snapshots__/pattern_matching.be46eb0e.0.snapshot
- compiler/test/__snapshots__/provides.30cbc409.0.snapshot
- compiler/test/__snapshots__/provides.82c10ab4.0.snapshot
- compiler/test/suites/basic_functionality.re
- compiler/test/suites/optimizations.re
- stdlib/pervasives.md
- stdlib/runtime/string.gr
- stdlib/runtime/string.md
Adds `suffix` argument to `print` (default `"\n"`). Enables printing without newline for instance
```
print(123, suffix="")
```
> feat(stdlib)!: Add `print` suffix default argument

- compiler/src/codegen/garbage_collection.re
- compiler/src/codegen/mashtree.re
- compiler/test/suites/gc.re
In a tail call such as `let isNaN = x => x != x` where `x` is passed to `!=` twice, we would over-optimize by not `incRef`ing `x` since it would be `decRef`ed by `!=`; however as the argument is passed twice, it is `decRef`ed twice. This PR ensures we handle this case properly by only doing this optimization on the _last_ time the argument is passed to the tail call.
> fix(compiler): Ensure refcounts are maintained when tail calls use arguments multiple times

- compiler/test/TestFramework.re
- compiler/test/runner.re
- compiler/test/runtime/numbers.test.gr
- compiler/test/suites/runtime.re
- stdlib/runtime/numbers.gr
This pr adds floating point modulo support closing #1371
> feat(runtime): Allow modulo on floating point numbers

- cli/bin/exec.js
- cli/bin/grain.js
This pr hides the node stack trace when an error is thrown from the cli. 
This should help improve user experience as the stack trace was irrelevant to the error previously.
> chore(cli): Hide node's stack trace

- compiler/src/typed/typecore.re
- stdlib/pervasives.gr
- stdlib/pervasives.md
- stdlib/runtime/dataStructures.gr
- stdlib/runtime/dataStructures.md
- stdlib/runtime/unsafe/memory.md
- stdlib/runtime/unsafe/wasmf32.md
- stdlib/runtime/unsafe/wasmf64.md
- stdlib/runtime/unsafe/wasmi32.md
- stdlib/runtime/unsafe/wasmi64.md
This pr adds labels to the primitive compiler types which allows for better documentation.
Notes:
* I removed the `prim_type_labeled` and just made `prim_type` take the labels to prevent unlabeled functions in the future.
Closes: #1981
> chore(compiler): Add labels to primitive function types

- compiler/graindoc/docblock.re
- compiler/src/diagnostics/comments.re
- compiler/src/typed/oprint.re
- compiler/src/typed/printtyp.re
- compiler/src/typed/printtyp.rei
- compiler/src/utils/markdown.re
- compiler/test/graindoc/types.expected.md
- compiler/test/graindoc/types.input.gr
- compiler/test/suites/graindoc.re
- stdlib/regex.gr
- stdlib/regex.md
- stdlib/runtime/atof/decimal.gr
- stdlib/runtime/atof/decimal.md
- stdlib/sys/file.gr
- stdlib/sys/file.md
- stdlib/sys/process.gr
- stdlib/sys/process.md
Closes #992 
```
provide record R {
/**
* A very special number
*/
x: Number
}
provide enum E {
/**
* A thing
*/
Thing
}
```
> feat(graindoc): Allow doc comments on variants and record fields

- compiler/test/stdlib/number.test.gr
- stdlib/number.gr
- stdlib/number.md
This pr adds `Number.asin`, `Number.acos` and `Number.isClose` to the Number stdlib. I was just going to add `asin` and `acos` but given that the methods being used to calculate `asin` and `acos` are approximations I decided to also add `isClose` to make the testing more concise.
isClose is taken from https://peps.python.org/pep-0485/#proposed-implementation,
The license on it just says its in the public domain I think that means we can use it but I honestly dont know happy to find an alternative approach though if that isnt allowed.
The `asin` and `acos` functions are from:
https://git.musl-libc.org/cgit/musl/tree/src/math/asin.c
Just like `pow`.
This is a draft because `isClose` is blocked on optional Arguments for a nice api, once that gets merged I will go back and refactor the …
> feat(stdlib): Add `asin`, `acos`, `atan`, `isClose` to Number module

- stdlib/array.gr
- stdlib/buffer.gr
- stdlib/pervasives.gr
- stdlib/string.gr
This pr cleans up some use cases of `let mut` and `let rec` that were unnecessary.
> chore(stdlib): Cleanup unnecessary `mut` and `rec`

- stdlib/float32.gr
- stdlib/float32.md
This improves the docs in the `Float32` module, It adds examples for the float32 syntax to the top following the pattern ive been using in other libs, Adds example to all the functions. and updates the documentation for `Float32.infinity` and `Float32.nan` to mention the alternative syntax.
> chore(docs): Add examples to `Float32` module

- stdlib/float64.gr
- stdlib/float64.md
This improves the docs in the `Float64` module, It adds examples for the float64 syntax to the top following the pattern ive been using in other libs, Adds example to all the functions. and updates the documentation for `Float64.infinity` and `Float64.nan` to mention the alternative syntax.
> chore(docs): Add examples to the `Float64` module

- compiler/src/parsing/parser.messages
- compiler/src/parsing/parser.mly
- compiler/test/grainfmt/comments.expected.gr
- compiler/test/grainfmt/comments.input.gr
Closes #2042 
I split the parsing of numbers into two distinct sets of rules: one for positive and one for negative numbers. This avoids a limitation with Menhir where `$sloc` locations aren't carried beyond a single rule. I don't think I'd go so far as to say this is a bug with Menhir, though. I kind of wish this could be solved with an `%inline` declaration, but they make an effort to have marking something inline not affect how the locations work. I may open an issue to ask/suggest a solution for this.
> fix(compiler): Ensure constant number locations are propagated correctly when parsing

- compiler/src/language_server/hover.re
- compiler/src/language_server/sourcetree.re
This PR adds hover lenses onto submodules, which makes it easier to see a submodule's signature at a glance without having to look through the entire submodule. This isn't as useful for modules where everything is provided. but in a module with a bunch of unprovided helpers, a summary can make understanding the code base a lot easier.
Demo Below:
> feat(lsp): Add hover for submodules

- compiler/src/typed/cmi_format.re
- compiler/src/utils/wasm_utils.re
- compiler/src/utils/wasm_utils.rei
This pulls @hhugo's change that we included in #1909 into a separate commit so we can land the improvement without the JSOO upgrade while we figure out the performance degradation.
> chore(compiler): Avoid round trip between string & bytes when reading cmi

- stdlib/marshal.gr
This refactors `Marshal` to use early return which makes it a bit easier to follow. 
Closes: #2020
> chore(stdlib): Refactor `Marshal` to use early return

- compiler/test/stdlib/number.test.gr
- stdlib/number.gr
- stdlib/number.md
This pr adds `Number.atan2` which is useful in game development and when working with angles as it is a quick way to compute the angle of a ray from its coordinates.
The implementation is taken from the [here](https://en.wikipedia.org/wiki/Atan2#Definition_and_computation) with a slight modification to follow `c`, `python` and `js` where `x==0` and `y==0` results in an output of `0` instead of `NaN`.
Work for: #1017 
Other Documentation:
MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2
Wiki Reference: https://en.wikipedia.org/wiki/Atan2
> feat(stdlib): Add `atan2` to the `Number` module

- compiler/test/stdlib/marshal.test.gr
- stdlib/marshal.gr
This makes sure that the marshaled representation is always consistent.
> fix(stdlib): Ensure consistent marshal representation

- compiler/src/typed/typemod.re
- compiler/test/input/reprovideTypeUnifyA.gr
- compiler/test/input/reprovideTypeUnifyB.gr
- compiler/test/input/reprovideTypeUnifyC.gr
- compiler/test/suites/provides.re
Closes #1886 
Shoutout to @peblair for the type manifest idea.
> fix(compiler): Ensure reprovided types unify

- cli/bin/grainrun.js
If an assertion fails, we show `Unable to instantiate WebAssembly module` which is incorrect. This ensures that message only shows when the module failed to instantiate.
> fix(cli): Show correct error when module traps

- compiler/test/stdlib/uri.test.gr
- stdlib/uri.gr
- stdlib/uri.md
URI parsing and utility module, mostly conforming to RFC 3986.
```
module Main
include "uri"
let uri = Result.unwrap(Uri.parse("https://grain-lang.org"))
print(Uri.scheme(uri)) // https
print(Uri.host(uri)) // grain-lang.org
Uri.encode("a:b") // a%3Ab
```
> feat(stdlib): Add `Uri` module

- stdlib/hash.gr
- stdlib/hash.md
This adds examples to the `Hash` module.
> chore(docs): Add examples to `Hash` module

- compiler/test/stdlib/path.test.gr
- stdlib/path.gr
Properly handles case where first argument is absolute and second argument is relative to the `Path.relativeTo` function
> fix(stdlib): Error when `relativeTo` used on relative source and absolute dest

- compiler/src/typed/typed_well_formedness.re
- compiler/src/utils/warnings.re
- compiler/src/utils/warnings.rei
- compiler/test/suites/numbers.re
This pr makes the `fromNumber(<literal>)` warning work on all types.
On a side note I think we broke the implementation of this check when we added default args and this pr also fixes that issue.
I merged the `FromNumberLiteralXXX` warnings into a single warning. I don't know if we want to make this a breaking change as the warning numbers have changed (I feel like we should consider it as one). 
closes: #2019
> chore(compiler): Add `fromNumber(<literal>)` warning for `short` types

- stdlib/number.gr
- stdlib/number.md
This pr improves the documentation on the `Number` module, by adding examples to most functions. It also adds a missing `since` property to `Number.sign`.
Notes:
* I omitted examples on the functions that take a `Range` until we have proper syntax.
* Our trig functions are currently not precise enough for good examples, I think we might need to look into rewriting them #1478 had been an issue to make `Number.sin` unbounded, but I noticed during this pr that was not the actual problem, the problem is how we map the input range and also with our implementation.
> chore(docs): Add examples to `Number` module

- compiler/test/stdlib/json.test.gr
- compiler/test/suites/stdlib.re
- stdlib/json.gr
- stdlib/json.md
- stdlib/runtime/string.gr
- stdlib/runtime/string.md
This PR aims to include my JSON parser/printer (https://github.com/cician/grain-json) into stdlib. Hopefully for 0.5 release.
I'm opening this PR as a draft for now since I expect to still make some important changes once stack allocated chars and thick numbers are in. Strictly speaking no changes are really required after stack chars PR is merged, but code can be improved for clarity by using chars instead of code points as raw numbers. Thick numbers on the other hand are going to affect the behavior of number parsing.
> feat(stdlib): Add `Json` module

- compiler/src/typed/oprint.re
- compiler/test/stdlib/number.test.gr
- stdlib/number.gr
- stdlib/number.md
- stdlib/runtime/atoi/parse.gr
- stdlib/runtime/atoi/parse.md
This makes `parseInt` use an exception in the `err` case.
On a note though until #1053 is fixed I dont know if it makes sense to make this change as you lose the ability to pattern match on the individual cases without importing the exceptions directly from the runtime which we dont want users doing.
That could still make it in before 0.6 so this pr is up for that and also just in case we want to move forward on this anyways.
This has been blocked by: #1758   or #1759  either one would work to get this moving.
Closes: #1057
> chore(stdlib)!: Replace `parseInt` error strings with structured error enum

- compiler/src/language_server/hover.re
- compiler/src/language_server/sourcetree.re
When #1963 was added we added support for hovering over the `include` tag to see the module signature. It looks like the function used for getting the signature can sometimes throw an exception this prevents the lsp from completely crashing in that case.
This has changed the env to be the program env as `include` is always going to be on the top level and a module is always going to imported into the programs env this makes it more reliable. In the case of failure we just provide the `module Header` so its still nice.
> fix(lsp): Prevent lsp crash when module cannot be found

- compiler/test/stdlib/rational.test.gr
- compiler/test/suites/numbers.re
I ran the suite locally with @spotandjake's changes and got a bunch of warnings. This uses the same trick as everywhere else to avoid them.
> chore: Supress warnings when testing fromNumber

- compiler/src/typed/module_resolution.re
In working on #2059, I noticed that the error message was wrong when I wrote `"runtime/atof/common.gr"` so I fixed it.
> fix(compiler): Ensure the extension is chopped in the case of module name error

- stdlib/runtime/atof/common.gr
- stdlib/runtime/atof/decimal.gr
- stdlib/runtime/atof/lemire.gr
- stdlib/runtime/atof/parse.gr
- stdlib/runtime/atof/slow.gr
Not sure if we care about this. I thought it might matter for some of our optimizations but nothing changed in the snapshots.
> chore(stdlib): Convert all relative filepath includes to module includes

- compiler/src/linking/link.re
- compiler/test/suites/basic_functionality.re
This pr makes the linker set the maximum wasm table size when generating code. 
[This issue was raised in discord](https://discord.com/channels/676306448594108416/778671397266128897/1214694527005229057)
> fix(compiler): Set maximum wasm table size

- stdlib/runtime/string.gr
Reimplement `print` using a single element IO vec in preparation for WASI prev 2 and to accommodate for the `fd_write` implementation of certain runtimes
> fix(stdlib): Implement `print` using a single element io vec

- compiler/src/typed/typepat.re
- compiler/test/suites/types.re
When multiple variants with the same name are in scope and one is used in a pattern match, the compiler would warn that the user should disambiguate, but when doing so for variants you'd get a type error. This resolves that issue.
> fix(compiler): Allow proper disambiguation of enum variants

- .github/workflows/generate-docs.yml
Docgen is failing because it's trying to commit no changes (because we did a release and all the changes got merged!). This only does the commit if there are changes.
> chore(ci): Conditionally commit regenerated documentation

- compiler/src/parsing/parser.messages
- compiler/src/parsing/parser.mly
- compiler/test/grainfmt/comments.expected.gr
- compiler/test/grainfmt/comments.input.gr
- compiler/test/grainfmt/for_loops.expected.gr
- compiler/test/grainfmt/for_loops.input.gr
- compiler/test/grainfmt/while_loops.expected.gr
- compiler/test/grainfmt/while_loops.input.gr
Allows `for` and `while` loops to be used without block bodies
```grain
for (let mut i = 0; i < 5; i += 1)
print("Hello")
```
> feat(compiler): Allow non-block bodies with loops

- compiler/src/parsing/well_formedness.re
- compiler/src/utils/warnings.re
- compiler/src/utils/warnings.rei
- compiler/test/suites/arrays.re
This pr adds a basic warning for `arr[1.5]` and `arr[1.5] = 1` along with `rational` use cases. The purpose of this is to better catch instances where a user is indexing with floats ahead of time and prevent more runtime bugs. You can still achieve the runtime `Index not an integer` error by doing something like `let i = 1.5; arr[i]` though. The biggest place thing this helps to prevent is `arr[1.0]` where a user might assume we cast that to an `int like` number.
> feat(compiler): Add warning for non-integer array indices

- compiler/src/utils/warnings.re
- compiler/test/suites/records.re
When you omit record fields in a record pattern we currently just tell you, that you need them. The warning has been improved to let you know that if you meant to omit the fields you can use `, _` syntax, This helps the compiler better document and inform users about our language features.
> feat(compiler): Improve warning when omitting fields in record pattern

- compiler/src/formatting/fmt.re
- compiler/test/grainfmt/function_params.expected.gr
- compiler/test/grainfmt/function_params.input.gr
I noticed that the formatter was formatting `(?suffix: String) => void` into `(suffix: String) => void` this pr fix's this and adds a regression test.
> fix(grainfmt): Fix formatting of `default` argument types

- stdlib/json.gr
- stdlib/json.md
- stdlib/runtime/numberUtils.gr
- stdlib/runtime/numberUtils.md
This is a small pr that cleans up a little bit of the code in the json libary.
This also adds graindoc to the `json` data structure which closes: #2057
> chore(stdlib): Cleanup json libary

- compiler/src/codegen/emitmod.re
This helps address the issue raised in #2082.
Non-release builds of Grain will now include debug information which can at least provide the names of functions in stack traces. For example, with the program
```
module Playground
from "string" include String
String.charAt(7, "foo")
```
You get the following stack trace from the CLI:
```
Failure: Invalid offset: 7
RuntimeError: unreachable
at panic_1163.linked.653 (wasm://wasm/00114abe:wasm-function[122]:0x2897)
at throw_4472.linked.17966 (wasm://wasm/00114abe:wasm-function[558]:0x2e2c0)
at fail_4474.linked.17967 (wasm://wasm/00114abe:wasm-function[559]:0x2e31b)
at charAtHelp_1518.linked.18542 (wasm://wasm/00114abe:wasm-function[605]:0x3095d)
at charAt_1532.linked.18544 (wasm://wasm/00114abe:wasm-function[607]:0x30cb2)
at _start.linked.23251 …
```
> feat(compiler): Enable debug info in binary output

- stdlib/LICENSE
I noticed we forgot to update the `stdlib` license year to 2024.
> chore(stdlib): Update license year

- stdlib/set.gr
Fixes #2110. I didn't compile nor test this change.
> chore(stdlib): Removed redundant for-loop in `Set.intersect`

- docs/contributor/compiler_walkthrough.md
> chore: Update lexer link in the compiler walkthrough

- stdlib/int8.gr
- stdlib/int8.md
Small pr fixing a tiny typo in one of the examples in the `Int8` docs.
> chore(stdlib): Correct typo in `Int8` doc example

- stdlib/int32.gr
- stdlib/int32.md
This pr adds examples to the `Int32` docs
> chore(stdlib): Add examples to `Int32` docs

- stdlib/array.gr
- stdlib/bytes.gr
- stdlib/hash.gr
- stdlib/map.gr
- stdlib/runtime/numbers.gr
- stdlib/string.gr
- stdlib/wasi/file.gr
I did an audit of the stdlib and found these cases where it would be _possible_ to encounter use-after-free bugs.
> fix(stdlib): Ensure references are retained in unsafe stdlib functions

- stdlib/int64.gr
- stdlib/int64.md
This pr adds examples to the docs for the `Int64` module.
> chore(stdlib): Add examples to `Int64` docs

- compiler/src/language_server/definition.re
The previous behaviour of the lsp with goto definition failed when you selected a variable from `left to right`, we now try and account for this by trying to find again, but one char over if we fail the first check.
> fix(lsp): Improve lsp behaviour on goto definition

- compiler/test/stdlib/string.test.gr
- stdlib/string.gr
- stdlib/string.md
This pr adds `forEachChar`, `forEachCharI`, `map` and `mapi` to the String library.
> feat(stdlib): Add `forEachChar`, `forEachCharI`, `map` and `mapi` to String module

- compiler/src/middle_end/anf_helper.re
- compiler/src/middle_end/anf_helper.rei
- compiler/src/middle_end/linearize.re
- compiler/src/middle_end/matchcomp.re
- compiler/test/suites/optimizations.re
This pr makes locations non optional on `anf_helper`.
I think after this is merged we might want to open an issue to go through and evaluate the use of `Location.dummy_loc` throughout the compiler.
> chore(compiler): Make `locs` on `anf_helper` non optional

- compiler/test/suites/optimizations.re
Depending on the order the test suites are run, calling `Ident.create` in the tests will change what stamps idents in further tests get, which can cause snapshot tests to fail. This prevents stamp changes.
> chore(compiler): Stabilize snapshots

- stdlib/pervasives.md
- stdlib/runtime/string.gr
- stdlib/runtime/string.md
I noticed we never added a `history` attribute to `print` when we added the `suffix` argument in `v0.6.0`
> chore(stdlib): Add history item to `print` for `suffix` change

- stdlib/list.gr
This pr optimizes `List.join` similarly to how `Array.join` was optimized in #1948, this change makes `List.join` use only a single allocation, and should reduce the number of times we need to copy while reallocating. 
Closes: #728
> chore(stdlib): Optimize `List.join`

- compiler/test/runtime/numbers.test.gr
- stdlib/runtime/numbers.gr
This optimizes `numberMod` closing: #375
I noticed that `17 % -4` changed in the tests, but it now follows the same behaviour as `Int64` and `int32`.
> fix(stdlib): Optimize number modulo

- stdlib/runtime/wasi.gr
- stdlib/runtime/wasi.md
- stdlib/string.gr
- stdlib/wasi/file.gr
This pr cleans up some of the random usage of number tagging throughout the stdlib. This pr does not cleanup every case there are a few instances I found in `string.gr` where we do checks on the number before untagging it same as `array.gr` that I have left the same for now.
This is work towards finishing: #1072 
Seperate Note:
I also noticed in `file.gr` there are number of `TODO`s, `// TODO(#775): This has specific ordering requirements because of ambiguous type inference` I think these can be removed as that issue has been closed though I am unsure.
> chore(stdlib): Cleanup usage of number tagging throughout the stdlib

- compiler/src/language_server/goto.re
Holding control highlights the correct origin
Before:
After:
> fix(lsp): Use correct origin selection range

- stdlib/runtime/unsafe/memory.gr
- stdlib/runtime/unsafe/memory.md
This pr simplifies the `Memory.copy` and `Memory.fill` polyfills in `Memory.gr`, I implemented them using a `for` loop as it means less mutable variables compared to the while loop approach and makes the code a lot easier to follow.
Additionally this removes a few operations per cycle on the functions as we are not modifying as many values every iteration.
> feat(runtime): Simplify `copy` and `fill` polyfills in `Memory` module

- compiler/src/typed/typecore.re
- compiler/test/suites/functions.re
This pr fixes #2151, we seem to have made an invalid assumption when creating the type here which was causing the crashes. 
For anyone interested the root cause of the issue was in `type_approx` which is used when we are guessing types for recursive functions, we were producing the a `TTyvar` instead of an `option(TTyvar)` on default arguments.
> fix(compiler): Correct type approximation on recursive functions

- compiler/test/stdlib/float64.test.gr
- stdlib/runtime/bigint.gr
We were handling the conversion on `Bigints` to `Float64`s wrong in the runtime. This pr corrects that behaviour and fixes the issue.
I still need to add a regression test. 
Closes: #2159
> fix(runtime): Correct `Bi.toFloat64` rounding

- compiler/test/stdlib/float32.test.gr
- compiler/test/stdlib/float64.test.gr
- stdlib/float32.gr
- stdlib/float32.md
- stdlib/float64.gr
- stdlib/float64.md
- stdlib/runtime/numbers.gr
- stdlib/runtime/numbers.md
This pr adds the `power` function `2.0d ** 2.0d` to the `Float32` and `Float64` libraries, this uses the same algorithm we use for `Number.pow` without the extra overhead for the different number types, a future improvement we could make is having a separate algorithm for `float32` for better performance.
> feat(stdlib): Add `**` to `Float64` and `Float32`

- compiler/test/stdlib/float32.test.gr
- stdlib/float32.gr
- stdlib/float32.md
This pr adds some utilities to `Float32` which map easily to `wasmF32` such as `copySign`, `sqrt`, `min`, `max`, `round`, `trunc`, `floor`, `ceil`
Work Towards #2156
> feat(stdlib): Add `copySign`, `sqrt`, `min`, `max`, `round`, `trunc`, `floor`, `ceil` to `Float32`

- compiler/test/stdlib/float64.test.gr
- stdlib/float64.gr
- stdlib/float64.md
This pr adds some utilities to `Float64` which map easily to `wasmF64` such as `copySign`, `sqrt`, `min`, `max`, `round`, `trunc`, `floor`, `ceil`
Work Towards #2156
> feat(stdlib): Add `copySign`, `sqrt`, `min`, `max`, `round`, `trunc`, `floor`, `ceil` to `Float64`

- compiler/test/stdlib/number.test.gr
- stdlib/number.gr
- stdlib/number.md
- stdlib/runtime/math/kernel/cos.gr
- stdlib/runtime/math/kernel/cos.md
- stdlib/runtime/math/kernel/sin.gr
- stdlib/runtime/math/kernel/sin.md
- stdlib/runtime/math/kernel/tan.gr
- stdlib/runtime/math/kernel/tan.md
- stdlib/runtime/math/rempio2.gr
- stdlib/runtime/math/rempio2.md
- stdlib/runtime/math/trig.gr
- stdlib/runtime/math/trig.md
- stdlib/runtime/math/umuldi.gr
- stdlib/runtime/math/umuldi.md
This pr reintroduces `Number.sin` after it was removed in #2046, this uses the implementation found in [libc](https://git.musl-libc.org/cgit/musl/tree/src/math), with some adaptations made for wasm and grain. It uses a small kernal function that accuratly can compute `sin` for values between `-pi/4` to `pi/4` and a range reduction algorithm to map any values outside the range into the range efficently.
Notes:
* I made a new math folder in the stdlib, as these functions can be used for multiple number types it makes sense to seperate them out so they are easier to understand.
* I am going to make a follow up pr for `gamma` and `factorial`
* I am going to make another follow up pr for `Float32` and `Float64`, `sin`, `cos` and `tan`
Some Notes:
* When it comes to bigints we lose a lot of …
> feat(stdlib): Reimplement `Number.sin`, `Number.cos`, `Number.tan`

- compiler/test/stdlib/float64.test.gr
- stdlib/float64.gr
- stdlib/float64.md
This pr adds `isFinite`, `isClose`, `sin`, `cos` and `tan` to the float64 library. Originally it was just going to add the trig functions, but `isClose` and `isFinite` are dependencies for testing the trig functions, I can seperate them into a seperate pr if desired but i did not see any major benefit.
work towards: #1813
> feat(stdlib): Add `isFinite`, `isClose`, `sin`, `cos`, `tan` to Float64

- compiler/test/stdlib/float32.test.gr
- stdlib/float32.gr
- stdlib/float32.md
This pr adds `isFinite`, `isClose`, `sin`, `cos` and `tan` to the float32 library. Originally it was just going to add the trig functions, but `isClose` and `isFinite` are dependencies for testing the trig functions, I can seperate them into a seperate pr if desired but i did not see any major benefit.
This pr also opened the issue: #2167 as it would make sense to use a float32 optimized set of trig functions in the future for better relative accuracy, Float32.pi != Float64.pi will cause the precision to drift with larger values of x.
work towards: #1813
> feat(stdlib): Add `isFinite`, `isClose`, `sin`, `cos`, `tan` to Float32

- stdlib/number.gr
This removes the old `sin` function from the Number library as it is unused.
> chore(stdlib): Cleanup old trig func from Number lib

- compiler/test/stdlib/number.test.gr
- stdlib/runtime/math/rempio2.gr
- stdlib/runtime/math/trig.gr
I noticed that we were getting a little bit of extra error when computing trig functions, which I traced the values against the c implementation I noticed that the sign bit was not working correctly, this changes the sign to be calculated before clearing the high bits.
For anyone concerned this was not affecting accuracy very much compared to most use cases of trig functions but it is important that we are producing an accurate output if we are using the trig functions to compute other math functions where the error stacks more.
> fix(stdlib): Correct sign bit in `_rempio` when computing trig reduction

- compiler/test/suites/strings.re
- stdlib/runtime/debugPrint.gr
- stdlib/runtime/string.gr
This pr corrects our printing for range values before we were printing `<record value>` and now we print `{ rangeStart: 1, rangeEnd: 2 }`, I know we want to add the range syntax eventually but I think we should hold off on the range Syntax in the output until then.
Closes: #2183
> fix(stdlib): Properly print `Range` values

- compiler/test/stdlib/number.test.gr
- stdlib/number.gr
- stdlib/number.md
This pr re-implements `Number.gamma` and `Number.factorial`.
This pr is blocked on #2181 as the tests will fail due to the precision issue when computing `sin(pi * z) / gamma(1 - z)`
I think we should also open an issue to port the [c version here](https://git.musl-libc.org/cgit/musl/tree/src/math/tgamma.c) in the future as this approximation provides decent accuracy but we accumulate some extra error due to the error in other approximation functions such as `sin`, this should also make things a little faster.
This pr closes: #1478
> feat(stdlib): Reimplement `Number.gamma` and `Number.factorial`

- compiler/test/stdlib/json.test.gr
- stdlib/json.gr
- stdlib/json.md
> feat(stdlib): Json value access utils

- .github/workflows/build-js.yml
- .github/workflows/build-native.yml
- .github/workflows/generate-docs.yml
- .github/workflows/test-pkg.yml
- .github/workflows/upload-binaries.yml
This pr switches the upload artifact from v3 to v4 as v3 is going to deprecated at the end of the month [see here](https://github.com/actions/upload-artifact?tab=readme-ov-file) we were not affected by any of the breaking changes so we just had to change the version.
Separate to this:
Some of our actions are being forced to run with node v20 when we want them to run with node 18 [see here for why](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/) and you can see the deprecation warnings on our tests [here](https://github.com/spotandjake/grain/actions/runs/11785769957?pr=6) we should probably look into upgrading this.
> chore: Update to v4 actions artifacts

- compiler/test/TestFramework.re
This enables color in the output of our test framework on the github actions runners.
Check it out [the test for this pr](https://github.com/grain-lang/grain/actions/runs/11774522218/job/32793241118)
> chore: Enable colors on actions runner

- compiler/test/stdlib/hash.test.gr
- stdlib/hash.gr
- stdlib/hash.md
- stdlib/map.gr
- stdlib/map.md
- stdlib/set.gr
- stdlib/set.md
This pr refactors the hashing function so we do not keep global state, it also implements a new `Hash.makeSeeded` and `Hash.make` function which returns a `HashInstance`. If we want a different api I am happy to change things around.
API:
```
let globalHash = Hash.make()
assert Hash.hash(globalhash, 1) == Hash.hash(globalHash, 1)
assert Hash.hash(globalhash, "a") == Hash.hash(globalHash, "a")
```
```
let seeded1 = Hash.makeSeeded(1)
assert Hash.hash(seeded1, 1) == Hash.hash(seeded1, 1)
assert Hash.hash(seeded1, "a") == Hash.hash(seeded1, "a")
let seeded2 = Hash.makeSeeded(2)
assert Hash.hash(seeded1, 1) != Hash.hash(seeded2, 1)
```
Questions:
* Should we generate a seperate seed on `Hash.make` every time or do we want to use the globalSeed? Maybe if we want a globalSeed we should provide …
> feat(stdlib)!: Seeded hashing

- compiler/src/typed/env.re
I noticed if you get a disambiguation error before it was showing the error position as the top of the module. This corrects it to show the proper location.
> feat(compiler): Use location for `Unbound_label_with_alt` error

- compiler/src/typed/typecore.re
- compiler/test/suites/returns.re
We were losing the state of `in_function` when type checking record properties which caused a the `Impossible` warning to trip. This pr corrects that and adds a regression test.
Closes: #2204
> fix(compiler): Correct `in_function` state when typing record properties

- stdlib/queue.gr
- stdlib/queue.md
- stdlib/stack.gr
- stdlib/stack.md
Fixes documentation for queue and stack, both of which incorrectly mentioned map.
> chore(docs): Fix typos in queue and stack documentation

- compiler/src/typed/printpat.re
This pr improves the way we print exhaustiveness warnings for list constructors an example can be seen below:
As a side note, and without looking into this I wonder if it would make sense or if we should at least open an issue to move from a custom printer here to somehow using the formatter, we do have a function to convert from the typedtree nodes back into the parsetree nodes which we should be able to pipe into the formatter this would maintain a consistent
Closes: #2217
> feat(compiler): Improve exhaustive warning for lists

- compiler/grainlsp/hacks.js
It's deprecated and will result in a warning with the next release of jsoo
> chore(compiler): No longer rely on joo_global_object

- compiler/src/typed/parmatch.re
- compiler/test/suites/pattern_matching.re
I noticed that when we had a non exhaustive pattern including a string such as:
```gr
module Main
match ([]) {
["str"] => void
}
```
we would hit an impossible error upon further investigation i noticed that we convert the constructors from typetree nodes back into ParseTree nodes and that we did not add the quotes back onto the string when we do this, I corrected that and added two small regression tests.
Closes: #2216
> fix(compiler): Prevent impossible string error from pattern matching

- compiler/src/language_server/code_action.re
- compiler/src/language_server/sourcetree.re
- compiler/test/suites/grainlsp.re
```
// Before
let f = () => print("Hi")
// After code action
let f = () => { print("Hi") }
// Before
let f = () => { print("Hi") }
// After code action
let f = () => print("Hi")
```
Implemented only for function bodies as I felt this would be where this would get the most use, and allowing it _everywhere_ would add a lot of noise as this code action would basically show everywhere in code. I'm open to also adding it to a few other specific places like ifs, loops, etc. though
> feat(lsp): Add or remove block braces code action

- compiler/test/stdlib/list.test.gr
- stdlib/list.gr
- stdlib/list.md
This adds functions for combined filtering and mapping along with a findMap function.
Also a few small spelling corrections in the `List` docs got added into this pr.
> feat(stdlib): Add `List.filterMap`, `List.filterMapi`, `List.findMap`

- stdlib/queue.gr
- stdlib/queue.md
This pr adds examples to the `Queue` module. I also noticed a few of the history items were missing so this corrects them and I also moved the `toList` and `fromList` closer to the `toArray` and `fromArray`.
> chore(stdlib): Add examples to `Queue` module

- compiler/test/stdlib/stack.test.gr
- stdlib/stack.gr
- stdlib/stack.md
This pr adds `toList`, `fromList`, `toArray`, `fromArray` to both the `Stack` and `Stack.Immutable` modules.
> feat(stdlib): Add `toList`, `fromList`, `toArray`, `fromArray` to Stack

- compiler/test/stdlib/list.test.gr
- stdlib/list.gr
- stdlib/list.md
This pr adds a `List.Assocative` submodule which contains functions for working with key-value pairs in lists.
```
let data = [
("name", "Alice"),
("name", "Bob"),
("age", "30"),
]
assert List.Associative.get("name", data) == Some("Alice")
```
This is similar to the associative list methods in ocaml https://ocaml.org/manual/5.2/api/List.html#1_Associationlists
I wasn't quite sure if we wanted this in the standard library or not but I think the pattern occurs enough with record information that it makes sense. A few examples being `Map.toList`, `JSONObject`.
Currently duplicates are ignored and the first item is always treated as the one your referring too.
An alternative proposal to this pr is we implement a new `Collection` module, where collections are of type `abstract type …
> feat(stdlib): `List.Associative` Submodule

- docs/contributor/compiler_walkthrough.md
> chore: fix 404 binaryen.ml URL

- compiler/src/codegen/compcore.re
Tiny pr just changing the location of `_gmain` from a `dummy_loc` to the program location which seems slightly more accurate. 
I'm not sure if this counts as breaking or not.
Closes: #2174
> feat(compiler): Use program location for `_gmain`

- compiler/src/formatting/fmt.re
- compiler/test/grainfmt/lambda.expected.gr
- compiler/test/grainfmt/lambda.input.gr
This fixes formatting of single argument tuple function types such as `((a, b) => Void` before they were being formatted to `(a, b) => Void`, this is because we drop parens around single argument lambda's but we need to keep them in the case of a pattern.
Closes: #2229
> fix(grainfmt): Fix formatting of function types with a single tuple arg

- .github/workflows/build-native.yml
- stdlib/README.md
- stdlib/package.json
Small pr with two `qol` npm scripts for `npm run stdlib format` and `npm run stdlib doc`, this ensures consistency when running scripts and ensures that contributors are using the right grain version when generating docs.
> chore: Add scripts for `stdlib format` and `stdlib doc`

- cli/bin/grainrun.js
I don't know if this is the best title for this but before if you tried to run the grain cli with node `v22` or above it would error because the `--experimental-wasm-return-call` flag was used, this just checks if we are on those versions and doesn't apply the flag as the behaviour is the default.
I think this pr might be controversial the goal here isn't to change the version of js we use with the pkg binaries just to allow newer versions of node to be used when you've built the compiler from source.
> feat(cli): Support node v22 and v23

- stdlib/array.gr
- stdlib/array.md
Tiny correction to a spelling mistake found in the docs for the `Array` module.
> chore(stdlib): Correct small spelling mistake in `Array` docs

- compiler/test/stdlib/list.test.gr
- stdlib/list.gr
- stdlib/list.md
This adds `getAll`, `setAll` and `removeAll` to `List.Associative`
> feat: Add `getAll`, `setAll`, `removeAll` to `List.Associative`

- compiler/test/stdlib/path.test.gr
- stdlib/path.gr
- stdlib/path.md
This adds `Path.removeExtension` to the `Path` library as I noticed there wasn't really a great way todo it before
> feat(stdlib): add `Path.removeExtension`

- cli/bin/grain.js
- compiler/grainc/grainc.re
- compiler/graindoc/docblock.re
- compiler/graindoc/graindoc.re
- compiler/src/codegen/linkedtree.re
- compiler/src/compile.re
- compiler/src/compile.rei
- compiler/src/formatting/fmt.re
- compiler/src/language_server/code_file.re
- compiler/src/link.re
- compiler/src/parsing/driver.re
- compiler/src/parsing/driver.rei
- compiler/src/typed/cmi_format.re
- compiler/src/typed/cmi_format.rei
- compiler/src/typed/dependency_graph.re
- compiler/src/typed/dependency_graph.rei
- compiler/src/typed/env.re
- compiler/src/typed/env.rei
- compiler/src/typed/module_resolution.re
- compiler/src/typed/module_resolution.rei
- compiler/src/typed/typemod.re
- compiler/test/runner.re
- compiler/test/suites/foreigns.re
- compiler/test/suites/includes.re
- compiler/test/suites/linking.re
- compiler/test/suites/modules.re
- compiler/test/suites/provides.re
Refactors the `DependenciesCompiled`, `ObjectsLinked`, `Compiled`, and `Assembled` states out of `compile.re` and introduces the `grainc` flag `--single-file` to compile a single dependency. The linker is now completely separate from the process of compilation—compiling a file now only means converting source code into an object file. Linking is the combining a number of object files into a wasm file (and `grainc` will still do both compiling and linking). This allows build tools to handle compilation and linking separately.
The future plan is to make single file mode the default once we have a build tool managing building projects (`silo`). I'm not sure that we should get rid of the dependency compilation _entirely_ since it would be useful for development, but that's a decision for …
> feat(compiler): Enable single-file compilation

- stdlib/array.gr
- stdlib/buffer.gr
- stdlib/bytes.gr
- stdlib/runtime/unsafe/offsets.gr
- stdlib/runtime/unsafe/offsets.md
- stdlib/runtime/utf8.gr
- stdlib/runtime/utf8.md
- stdlib/string.gr
This pr works towards #703 I started with the `string` module, I also changed a few other modules to use the common `offsets` module for their offsets, if we are good with the approach I am taking to this I will do the same to the other modules but I figure that might be best todo in a separate pr.
Notes:
* I found some other utf-8 cleanup that I threw into this pr as it wasn't much.
* I also made the other modules with offsets already defined in variables point to the `Offsets` module for consistency sake.
> chore(runtime): Cleanup offset constants in `String` module

- compiler/src/formatting/fmt.re
- compiler/test/grainfmt/constraints.expected.gr
- compiler/test/grainfmt/constraints.input.gr
This fixes a small bug where `(1: Number): Number` was being formatted into `1: Number: Number` which is a parsing issue.
Closes: #2244
> fix(grainfmt): Correct formatting of nested constraints

- compiler/test/stdlib/char.test.gr
- stdlib/char.gr
- stdlib/char.md
This adds `Char.byteCount` which can be used with a specified encoding to get the encoded length of a char.
Example use case for this is stepping through a byte array when you do `Byte.getChar` you have no clue how far to advance for the next char without this.
> feat(stdlib): Add `Char.encodedLength`

- compiler/test/suites/basic_functionality.re
- compiler/test/suites/gc.re
- stdlib/runtime/gc.gr
This pr prevents stack overflows during the collection of large and extremely large lists.
* Smallest program size decreased because of increased code sharing in `decRefChildren`
* All data structures now support extremely deep nested objects in the final position.
----
While working on #2247 I noticed that `decRef` was overflowing the stack with lists that were only around `1350` elements.
The reason for this is that `decRef` and `decRefChildren` were not tco optimized, so the two options were to either handle lists separately or find a way to optimize `decRef` for tail calls. I decided on the second approach as it is more generic and provides improvements for other data structures as well.
The way I went about this was with a slightly cursed but valid modification where we `free` the …
> feat(runtime): Prevent stack overflow while collecting large lists

- compiler/test/stdlib/pervasives.test.gr
- compiler/test/suites/basic_functionality.re
- stdlib/runtime/equal.gr
This optimizes `==` for specifically for lists and also refactors it to use early return. Instead of the recursive approach used in the general case for adt's because we know lists will always have two elements (item, nextItemPtr) we handle it in an iterative manner avoiding the stack overflow.
**Notes**:
* The smallest program size increased because `==` is bundled to every grain program.
* `==` would now lock with a cyclic list, however from my understanding such a list would be impossible to build in grain. 
* If we want to handle cycles we can but it adds overhead as we need to go back through the scanned items and do the unmarking after.
* This will all need to get refactored with the wasm gc changes we plan to make so I think it's fine to take the perf improvement for now.
* We …
> feat(runtime): Optimize `==` for lists 

- compiler/test/stdlib/array.test.gr
- stdlib/array.gr
- stdlib/array.md
This pr adds an `Array.tryInit` function to make this a bit easier. `Array.tryInit: (length: Number, fn: (index: Number) => Result<a, b>) => Result<Array<A>, b>`. This makes building arrays from result functions quite a bit easier as there was no good alternative before. I do not love the `tryInit` name but I couldn't think of anything better. 
Notes:
* I do not love the `tryInit` name, if anyone has a better one let me know
* If we like the feature and name I am happy to add it to `List` and `Array.Immutable`
* happy todo that in this pr or a separate one
* `Array.tryInit` is the most important as with something like a list you can just build it manually.
* I also noticed we didn't have tests for `Array.make` and `Array.init` so I added those in this pr but I am happy to move those to a …
> feat(stdlib): Add `Array.tryInit`

- compiler/src/formatting/fmt.re
- compiler/test/grainfmt/application.expected.gr
- compiler/test/grainfmt/application.input.gr
Corrects formatting of both infix and prefix functions called with labeled arguments.
ex:
```
(+)(x=1, y=2)
(!)(rhs=true)
```
previously it formatted the bad output of:
```
x=1 + y=2
!rhs=true
```
> fix(grainfmt): correct fmt of operator funcs applied with labeled args

- compiler/src/typed/typepat.re
This corrects the error reporting for the below code:
```gr
module Test
match (true) {
[false, ...rest] => fail "False",
_ => fail "True",
}
```
before it resulted in:
```gr
File "", line 0:
Error: This variant pattern is expected to have type Bool
The constructor [...] does not belong to type Bool
```
now it correctly prints:
```gr
File "test.gr", line 3, characters 2-18:
Error: This variant pattern is expected to have type Bool
The constructor [...] does not belong to type Bool
```
> fix(compiler): Correct location of parmatch mismatch type error

- compiler/src/typed/typemod.re
- compiler/src/typed/typemod.rei
- compiler/test/suites/includes.re
I noticed the error message was still using the `v0.6.0` preview syntax so this updates it to the correct release syntax. 
I'm not a major fan of the fact that in the test where we are including `provideAll` it says `provideAll.gr` but our other tests seem to follow similar behaviour and It would require a lot of rework to improve that.
> fix(compiler): Correct `Include_module_name_mismatch` error

- compiler/src/formatting/fmt.re
- compiler/test/grainfmt/comments.expected.gr
- compiler/test/grainfmt/variants.expected.gr
- compiler/test/stdlib/json.test.gr
This adds a trailing comma on inline record variants
Closes: #2049
> feat(fmt): Add trailing comma on inline records

- compiler/src/language_server/code_file.re
This fixes the issues we were having with the lsp where it wouldn't update when you made changes, upon some investigation and a `git bisect` I noticed that things stopped working in #2105 as we stopped reseting the compiler state when handling changes, this causes the parsetree cache to be hit and our changed module to never be reparsed. 
I wanted to add a regression test for this but It doesn't look like our lsp test suite is setup in a way that would make that easy.
> fix(lsp): Ensure file changes update lsp state

- compiler/grainc/grainc.re
I noticed that `grain compile test.gr -o test.wasm` with any program was failing, it turned out to be a simple issue we were passing the outfile to figure out the name of the objfile when we should be passing the actual file name, and only using the outfile for the wasm output.
Closes: #2269
> fix(grainc): Correct behaviour of `-o` flag

- compiler/src/typed/checkertypes.re
- compiler/src/typed/checkertypes.rei
- compiler/src/typed/disambiguation.re
- compiler/src/typed/typecore.re
- compiler/src/typed/typecore.rei
- compiler/src/typed/typedecl.re
- compiler/src/typed/typemod.re
- compiler/src/typed/typemod.rei
- compiler/src/typed/typepat.re
This just cleans up some legacy errors we had lying around but have not been using.
> chore(compiler): Cleanup unused errors

- compiler/test/stdlib/float32.test.gr
- compiler/test/stdlib/float64.test.gr
- compiler/test/stdlib/int32.test.gr
- compiler/test/stdlib/int64.test.gr
- compiler/test/stdlib/uint32.test.gr
- compiler/test/stdlib/uint64.test.gr
- stdlib/float32.gr
- stdlib/float32.md
- stdlib/float64.gr
- stdlib/float64.md
- stdlib/int32.gr
- stdlib/int32.md
- stdlib/int64.gr
- stdlib/int64.md
- stdlib/runtime/unsafe/offsets.gr
- stdlib/runtime/unsafe/offsets.md
- stdlib/uint32.gr
- stdlib/uint32.md
- stdlib/uint64.gr
- stdlib/uint64.md
This implements the following functions:
- `Int32.reinterpretFloat32`
- `UInt32.reinterpretFloat32`
- `Int64.reinterpretFloat64`
- `UInt64.reinterpretFloat64`
- `Float32.reinterpretInt32`
- `Float32.reinterpretUint32`
- `Float64.reinterpretInt64`
- `Float64.reinterpretUint64`
These act pretty similarly to their lower level wasm counterparts. 
Note: While I was working I also did some cleanup related to #703 though I'm happy to undo that if we decide it doesn't fit into this pr.
Closes: #2250
> feat(stdlib): Implement `reinterpret` between float and int values

- cli/bin/grain.js
I noticed that we the runner options `--dir` and `--env` were apearing in our cli help command for compile, this pr moves them to only appear for `compile-and-run` or `compile`.
> fix(cli): Only accept `--dir`, `--env` on `grain run` or `grain`

- compiler/src/language_server/code_action.re
- compiler/test/suites/grainlsp.re
I noticed that the lsp would sometimes crash in `stdlib/path.gr` with an `Impossible error`, it seems we made the assumption that an `Unlabeled` arg cannot appear in a `TExpApp` argument however this isn't the case, things like patterns and inferred functions (passed as a param) can trigger this case.
A minimal reproduction of this issue is either `a => a(1)`, or `(((a, b)) => a + b)((1, 2))` place your cursor before the parameter in vscode.
> fix(lsp): Correct use argument label code_action with inferred funcs

- compiler/src/parsing/well_formedness.re
- compiler/src/typed/parmatch.re
- compiler/src/typed/typed_well_formedness.re
Just some tiny cleanup, `Location.prerr_warning` checks `Warnings.is_active` [source here](https://github.com/grain-lang/grain/blob/3cf6021b7c7a228542fd300e9bf33c5b63bcc42d/compiler/src/parsing/location.re#L416) before actually emitting the error so doing it in these locations just makes things slower and adds code noise.
> chore(compiler): Clean up duplicate `Warnings.is_active` checks

- compiler/src/typed/parmatch.re
- compiler/src/typed/printpat.re
- compiler/test/input/mixedPatternMatching.gr
- compiler/test/suites/pattern_matching.re
- stdlib/queue.gr
This implements exhaustiveness checking both for regular records and inline records. I split the two into seperate commits as we need the record pattern logic for inline adt's but some additional debugging was needed to get inlines working.
I mostly ported the logic over from [parmatch.ml in the ocaml compiler](https://github.com/ocaml/ocaml/blob/8c52855f31804a86384ba1ea8981b14b7a5f1c02/typing/parmatch.ml), though they are not 1 for 1 as our implementation has diverged a decent bit, the foundational logic is the same.
It was a little weird that previously including a record variant would cause you to get no exhaustiveness info even on non record variants in your enum, it turned out this was because when converting back to our parsetree nodes we were just treating everything as a tuple …
> fix(compiler): Handle non-exhaustive record patterns

- compiler/test/stdlib/path.test.gr
- stdlib/path.gr
- stdlib/path.md
This adds `Path.updateExtension` so users can set the current extension.
Edge Cases:
* Regular, we just chop the extension and then append `.<ext>` to the end
* Directory, we don't set the extension
* Empty extension sets something like `file.ext` to `file.`, this seems weird but I think it's the best option if a user actually wants to clear the extension they should use `removeExtension`.
Note: One thing I noticed is our examples for `Path` omit the `Path.` which means unless you do` use Path.*` (which I don't think we encourage) the examples are not runnable off the bat, I think we should fix this in a seperate pr for consistency across the stdlib.
> feat(stdlib): Add `Path.updateExtension`

- docs/contributor/standard_library.md
I noticed our stdlib contribution guidelines were a little outdated and a bit lacking in terms of actual content, so I did a little rewrite.
One more notable change is I removed our guideline on keeping dependencies to a minimum, this was originally added when grain still used the `js-runner` with dynamic linking and with the switch to object files and good tree shaking I think in general this is a lot less of a concern, while I still believe we as a team want to keep dependencies to a minimum (reduced compile times and less dependency loops), I think having this as a guideline pushes for less code sharing which is something we have been trying to cleanup. If we still think this is important I can add it back but I suggest we rephrase it as `stdlib modules should be as self contained and …
> feat(docs): Update `stdlib` contributor guidelines

- compiler/src/formatting/fmt.re
- compiler/test/grainfmt/comments.expected.gr
- compiler/test/grainfmt/comments.input.gr
This corrects the formatting of cases like:
```gr
module Foo {
foo // foo
}
```
Previously we were adding a new hardline at the end each time the formatter was run, it seems we were not correctly handling the linebreak calculation as were not printing the comment range as if it were at the end of a block. 
Closes: #2287
> fix(grainfmt): Correct formatting of submodules ending with comments

- CONTRIBUTING.md
- stdlib/int32.gr
- stdlib/int32.md
- stdlib/int64.gr
- stdlib/int64.md
- stdlib/number.gr
- stdlib/number.md
Some of our stdlib examples were still using the pre 0.6 syntax this corrects them.
> chore(docs): Clean up pre 0.6 examples

- stdlib/number.gr
- stdlib/number.md
This exposes our equality operators like `<`, `>`, `<=`, `>=` through the number module, this makes code using multiple number types a little more consistent as before you would have needed to pull them from pervasives after switching your operators for other number types.
> feat(stdlib): Expose equality operators through `Number` module

- compiler/src/language_server/driver.re
- compiler/src/language_server/initialize.re
- compiler/src/language_server/message.re
- compiler/src/language_server/message.rei
- compiler/src/language_server/symbol.re
- compiler/src/language_server/symbol.rei
- compiler/src/typed/typedtree.re
- compiler/src/typed/typedtree.rei
- compiler/src/typed/typemod.re
- compiler/test/runner.re
- compiler/test/suites/grainlsp.re
This adds the lsp symbol outline which makes it easier to navigate large files.
> feat(lsp): Implement document symbol outline

- compiler/test/stdlib/buffer.test.gr
- stdlib/buffer.gr
- stdlib/buffer.md
- stdlib/bytes.gr
- stdlib/bytes.md
This adds `Buffer.setChar` and `Buffer.getChar` to complement their bytes counterparts.
Note: We have to read the first byte before `getChar` so we can correctly do the bounds check similar to how its done in `Bytes.getChar`.
Note: I realized we missed a piece of documentation on `Bytes.getChar` so I added it here.
> feat(stdlib): Add `Buffer.getChar`

- compiler/src/typed/cmi_format.re
- compiler/src/typed/cmi_format.rei
- compiler/src/utils/char_utils.re
- compiler/src/utils/wasm_utils.re
- compiler/src/utils/wasm_utils.rei
I noticed that we still had the legacy cmi tooling in `wasm_utils` with the switch to object files this is no longer needed.
> chore(compiler): Cleanup legacy cmi handling
